### ISSUE TITLE
[Report][1.12.2] Simple Report of Analyzer Yields for Tar Items

### ISSUE THREAD

**Issue by Gift-of-Names** [FossilsArcheologyRevival/FossilsArcheologyRevival#1013]
Besides their respective fossil/DNA yields, tar drops only yield coal and volcanic rock, and tar fossils only yield bone meal and volcanic rock. As I am unclear as to what the yields are supposed to be in this new version, I felt it best to simply report it here.

**Comment by Alex-the-666** [comment]
working as intended
