### ISSUE TITLE
terrestrial animals don't pathfind in water

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#1057]
they can swim! but they don't swim anywhere.

**Comment by Alex-the-666** [comment]
![2019-02-04_16 52 21](https://user-images.githubusercontent.com/8662109/52247077-4ab71600-289d-11e9-9635-d2d3e8d18071.png)
Vanilla mobs dont do it either... I believe mojang must have implemented this to stop lag. strange.
