### ISSUE TITLE
coelacanth spawn rate is too low - nautilus spawn rate is too high

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#1064]
can't find any coela, but I've seen more nautilus than squids.

**Comment by lindstheginj** [comment]
correction: i've found one single coela

**Comment by lindstheginj** [comment]
another correction: i've found a handful of coelas but they're all at the water's surface. shouldn't they spawn deeper?

**Comment by Alex-the-666** [comment]
fixed
