### ISSUE TITLE
Velociraptor pounced a baby Triceratops, Raptor glitched into the ground.

### ISSUE THREAD

**Issue by TyrannosaurKing** [FossilsArcheologyRevival/FossilsArcheologyRevival#1070]

**Comment by TyrannosaurKing** [comment]
Was able to replicate it several times, Rest in piece raptors.

**Comment by lindstheginj** [comment]
Pretty sure this is MC's fault, not ours. Will wait for alex to confirm before closing.

**Comment by TyrannosaurKing** [comment]
Testing it out with Deinonychus, They don't glitch deep enough to suffocate but it sure as hell looks off. 
![image](https://user-images.githubusercontent.com/47488903/52528175-53488b80-2ca5-11e9-871a-fbb680b236bb.png)

**Comment by Screwyoumimus** [comment]
I tested it, and Velo does the same too. It phased through when pouncing the new, tiny babies it seems

**Comment by Alex-the-666** [comment]
dupe #1513
