### ISSUE TITLE
Meganeura's sounds is the same as the Myrmex's from Ice and Fire

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1076]
Make your own sounds

**Comment by tyranno66** [comment]
How about you report real bugs before we restrict access for you to post bugs in the first place.

**Comment by mser7** [comment]
I don't know if this is an intended feature, I think they should make their distinct sounds

**Comment by lindstheginj** [comment]
Your opinion does not go on the Issues Tracker.

**Comment by mser7** [comment]
got it
