### ISSUE TITLE
Crash when opening ancient chest

### ISSUE THREAD

**Issue by xReckless** [FossilsArcheologyRevival/FossilsArcheologyRevival#1083]
when players try to put the key from anu in the ancient chest they crash
https://pastebin.com/uNVJtQ5U - Report

**Comment by mser7** [comment]
Strange, I did it and it is fine, got the clock even

**Comment by xReckless** [comment]
https://gyazo.com/5dd82524deed2dee1b22590e7b06e778
Sponge/GP/LP versions

**Comment by mser7** [comment]
Today I opened the chest and mine crashed as well
https://pastebin.com/nfYuqfTG

**Comment by CaptainStalfoss** [comment]
Can confirm, my game crashed as well.
I though it might be due to mod conflicts, but seeing as others has this issue to, maybe not.

**Comment by Draconian4466** [comment]
I also am having this issue im trying to open the chest with the ancient key and my game just crashes.

**Comment by Draconian4466** [comment]
Im just going to assume this is not going to be fixed because nothing has happened in the 3 months almost 4 that this has been open
