### ISSUE TITLE
Chicken soup bucket refund

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1088]
No bucket returned in chicken essence recipe, or when consume raw or cooked chicken soup

**Comment by BlueWither** [comment]
Yes
I was in trouble about the chicken essence.

**Comment by Alex-the-666** [comment]
you will get it back when you eat it now

**Comment by BlueWither** [comment]
How about to when making chicken essence on crafting table?
