### ISSUE TITLE
Crash Caused by: java.lang.NullPointerException: Null string not allowed

### ISSUE THREAD

**Issue by ClockworkFountain** [FossilsArcheologyRevival/FossilsArcheologyRevival#1089]
https://paste.dimdev.org/esasabivam.mccrash

I'm not sure what went wrong, I reinstalled, I read the crash report and Log, but I've got no idea as to where it comes from.

**Comment by ClockworkFountain** [comment]
Update: I believe this is a Bug on the TInker's Construct end of this mod...

**Comment by ClockworkFountain** [comment]
Update2: Nope, no idea.

**Comment by Alex-the-666** [comment]
fixed
