### ISSUE TITLE
Worktable crashing: exception in server tick loop

### ISSUE THREAD

**Issue by viceroy369** [FossilsArcheologyRevival/FossilsArcheologyRevival#1093]
1.12.2 version - crash report:

https://paste.dimdev.org/tageqepume.mccrash

**Comment by viceroy369** [comment]
Here's the same crash with less mods installed:
https://paste.dimdev.org/ucicuvebaf.mccrash

**Comment by ArkenorOakshadow** [comment]
I am getting the exact same crash with a very different mix of mods.:
https://paste.dimdev.org/uzufelimur.mccrash

**Comment by viceroy369** [comment]
I eventually managed to narrow this problem down - it's caused by an incompatibility with Mystcraft.

**Comment by ArkenorOakshadow** [comment]
Oh no! I love Mystcraft. Going to be hard to choose only one of them for now!

**Comment by Sunconure11** [comment]
I'm having this issue as well, and it's fucking up my server.

I'll summon the dev of Mystcraft.

@XCompWiz

**Comment by Sunconure11** [comment]
Report this to Mystcraft's bug tracker.

https://github.com/XCompWiz/Mystcraft-Issues/issues

**Comment by Alex-the-666** [comment]
Not an issue with mystcraft. just an issue with the arch bench.
