### ISSUE TITLE
Plesiosaurs don't have sounds

### ISSUE THREAD

**Issue by Moonlight2811** [FossilsArcheologyRevival/FossilsArcheologyRevival#1096]
1.12.2 possible bugs 
1- no plesiosaur sounds
2- no info in second page of dinopedia 
3-i don’t know if it’s meant but henodus don’t go on land and if you spawn them on land they don’t move I don’t know if that’s a bug because I don’t know if it’s a land/water turtle or just water

**Comment by lindstheginj** [comment]
In the future, please split bug reports into separate issues. The dinopedia issue was already reported, and henodus is a purely aquatic creature.

**Comment by Moonlight2811** [comment]
Okay sry I’m new here

**Comment by lindstheginj** [comment]
Actually, redirecting this. 
Duplicate of #1118
