### ISSUE TITLE
Fish items disappearing from inventories

### ISSUE THREAD

**Issue by Mushroomsock** [FossilsArcheologyRevival/FossilsArcheologyRevival#1098]
Not sure if this is intentional or not, but living fish items like Sturgeons are randomly disappearing from inventories.

**Comment by BlueWither** [comment]
Yes, I also have the same problem...

**Comment by BlueWither** [comment]
It only happens in survival mode.

**Comment by beanaboston** [comment]
I'm having this issue too.

**Comment by BlueWither** [comment]
I found a movie which happening the issue
https://www.youtube.com/watch?v=qA-JiQ0sSKM
5:33~5:42

**Comment by Alex-the-666** [comment]
dupe
