### ISSUE TITLE
Cultivator name

### ISSUE THREAD

**Issue by Raptorofwar** [FossilsArcheologyRevival/FossilsArcheologyRevival#1100]
When crafting a cultivator, the name of the object is {color} cultivator.

**Comment by Alex-the-666** [comment]
screenshot?

**Comment by Raptorofwar** [comment]
![screenshot 42](https://user-images.githubusercontent.com/42446863/52760451-708e9a00-2fc4-11e9-909d-29b31dbf800b.png)

**Comment by Alex-the-666** [comment]
what language translation are you using

**Comment by Raptorofwar** [comment]
English? I haven't changed it from the default.

**Comment by lindstheginj** [comment]
@4f6f3b is this something with localizations, maybe? It's still persisting in 8.0.1.

**Comment by Alex-the-666** [comment]
#1499
