### ISSUE TITLE
Mammoth is restless

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1102]
It is mostly running around. Is this intended?

**Comment by lindstheginj** [comment]
I think this is the herd ai. will let alex decide whether it should be closed.

**Comment by BlueWither** [comment]
Oh I see

**Comment by BlueWither** [comment]
But they shouldn't run too fast.
I made herd, but mammoth ran fast and broke many blocks

**Comment by Alex-the-666** [comment]
#1512
