### ISSUE TITLE
Placing Paleoraphe logs crash/Pouncing mobs do not latch on and only stay in the same location where the player was pounced

### ISSUE THREAD

**Issue by Danigirl23** [FossilsArcheologyRevival/FossilsArcheologyRevival#1104]
"The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=axis, clazz=class net.minecraft.block.BlockLog$EnumAxis, values=[x, y, z, none]} as it does not exist in BlockStateContainer{block=fossil:palm_log, properties=[axis]}" is the Paleoraphe crash

When a velociraptor pounces and latches, the mob does not move, it stays in the air floating until you die and then delatches.

**Comment by Mike-U5** [comment]
Should probably be separate issues?

The Paleoraphe crash happens for me too though.

**Comment by GarchompGirl** [comment]
This happend to me too! plus I spent hours on working on this map and its all gone to waste because of this bug! )=

**Comment by lindstheginj** [comment]
Palaeoraphe crash fixed in 8.0.1.
