### ISSUE TITLE
Request: Config needs spawn rate

### ISSUE THREAD

**Issue by Graywaren** [FossilsArcheologyRevival/FossilsArcheologyRevival#1114]
I'm so excited about this mod as I love dinosaurs and I really love all the models and creatures in this. However, it seems like this mod is spawning all its water entities and causing other mods water entities I have not to spawn much if at all due to animal caps or something, including vanilla squids. I went to the config, but there's no spawn rates to adjust (was mostly looking for nautilis), so I'm requesting that feature be added along with the ability to black/whitelist biomes.

**Comment by MokahTGS** [comment]
Agreed...spawns must be controlled.

**Comment by Graywaren** [comment]
Awesome! Forgive me if there's an obvious answer, but for all my searching I can't find one; is there a way that I can download the files that include that change from github to use in my world? Trying to use the zip file hitting download results in doesn't seem to work. Sorry to ask this here, but I've been unable to google an answer.

**Comment by Alex-the-666** [comment]
just wait a week or two for 8.0.1.

**Comment by Graywaren** [comment]
Okay! Will do. Thanks for addressing this so quickly! Really looking forward to exploring this mod.

**Comment by Graywaren** [comment]
Any update on when this will be coming out?
