### ISSUE TITLE
[Suggestion] The Room Portal - Control where it sends the player

### ISSUE THREAD

**Issue by MokahTGS** [FossilsArcheologyRevival/FossilsArcheologyRevival#1116]
Is it possible to have a config option that allows modpack makers to control where the portal out of the Room takes the player?  Currently it take the player to the overworld, but if a mod pack is not using the overworld in a traditional way this is a problem.

It would be great if you could specify that the portal take the player to a particular dimension and XYZ coords.

**Comment by Alex-the-666** [comment]
added
