### ISSUE TITLE
Chicken essence does not work on dinosaurs.

### ISSUE THREAD

**Issue by LucasDayvid** [FossilsArcheologyRevival/FossilsArcheologyRevival#1117]
Chicken essence does not work on some mobs:

Spinosaurus, Megalania, Tyrannosaurus, Allosaurus, Megalodon, Mosasaurus, Liopleurodon, Sarcosuchus, Quagga....

**Comment by lindstheginj** [comment]
It isn’t supposed to. Chicken essence does not work on anything that is tamed via scarab or is a horse.
