### ISSUE TITLE
why i cant download?

### ISSUE THREAD

**Issue by ghadad** [FossilsArcheologyRevival/FossilsArcheologyRevival#1120]
its stuck every time i try to download

**Comment by lindstheginj** [comment]
Wait, so the file isn't downloading off of the website? Or are you having issues installing it?

**Comment by ghadad** [comment]
i think

**Comment by ghadad** [comment]
its says 1 hour download

**Comment by lindstheginj** [comment]
That isn’t a bug then, it is a problem with your internet. Try checking your connection.
