### ISSUE TITLE
Various sifter "fuels" do not give any outputs

### ISSUE THREAD

**Issue by Mushroomsock** [FossilsArcheologyRevival/FossilsArcheologyRevival#1121]
List of affected fuels which do not give any output:
Dirt
Coarse Dirt
Podzol
Charred Dirt (Ice and Fire)
Charred Grass Path (Ice and Fire)
Charred Gravel (Ice and Fire)
Pile of Gold (Ice and Fire)
Pile of Silver (Ice and Fire)
Volcanic Ash (Fossils and Archeology)
Jungle Myrmex Cocoon (Ice and Fire)
Desert Myrmex Cocoon (Ice and Fire)
Frozen Dirt (Ice and Fire)
Frozen Gravel (Ice and Fire)
Frozen Grass Path (Ice and Fire)
All types of Compressed Dirt (Extra Utilities 2)

**Comment by Mushroomsock** [comment]
Also, it seems a bit strange that grass blocks (and Ice and Fire's charred/frozen variants of grass blocks) can't be used in the sifter.

**Comment by mser7** [comment]
Mo Creatures Wyvern/Ogre lair dirt and grass can also be used
