### ISSUE TITLE
Orange Dinopedia Entry for Megalania

### ISSUE THREAD

**Issue by unicorncatbug** [FossilsArcheologyRevival/FossilsArcheologyRevival#1128]
This only happens when the Megalania is attached to a lead that’s attached to a fence post. It is like a dark orange color but only happens when the Megalania is on a lead.

**Comment by LemonJamTart** [comment]
Experiencing this issue with a leaded Elasmotherium as well. May be an issue with leaded F&A mobs in general.

**Comment by lindstheginj** [comment]
Cannot recreate in 8.0.1.
