### ISSUE TITLE
Bio-fossil don't have all the fossil model of existing mobs

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1130]
I tried getting some of the tar-fossil models by using the bio-fossil, but I couldn't get any, not sure if this is a feature that I am not know

**Comment by lindstheginj** [comment]
Wait, so you were expecting to get tar fossil models using bio-fossils? You can only get tar fossil models from tar fossils.

**Comment by mser7** [comment]
apparently this is a thing since wayback 7.3.2 that I don't know about
https://fossils-archeology.fandom.com/wiki/Fossil_Model
