### ISSUE TITLE
Dig site spawned in a tree

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1131]
![2019-02-12_00 19 06](https://user-images.githubusercontent.com/11862143/52621353-ee836180-2e5b-11e9-9304-a0ee2cd6e32f.png)
I propose a treehouse dig site gets added as an actual feature, with the archaeologist looking for fossilized tree sap or something.

**Comment by lindstheginj** [comment]
That’s not how it works, fool

**Comment by Adsper** [comment]
That's the thing, he never gets anything because he never looks underground.

**Comment by Alex-the-666** [comment]
fixed
