### ISSUE TITLE
Mobs struggle to deal damage

### ISSUE THREAD

**Issue by NightSky64** [FossilsArcheologyRevival/FossilsArcheologyRevival#1134]
I don't know if anyone else has this issue, but at least for me animals are bugged. Carnivores run to their prey but do nothing when they get to it, and instead follow the prey. They only manage to deal damage when their prey gets really close, when pushing their collision box. Same with herbivores when they fight back.

**Comment by Adsper** [comment]
Noticed this too, it makes taming the big carnivores pretty laughable.

**Comment by Alex-the-666** [comment]
fixed
