### ISSUE TITLE
Game freezing

### ISSUE THREAD

**Issue by It4llo** [FossilsArcheologyRevival/FossilsArcheologyRevival#1135]
the game freezes when i play with F/A

**Comment by lindstheginj** [comment]
You need to provide more information. We have no idea why your game freezes and cannot fix it. Does it freeze before the game loads? If it freezes during the game, does it happen after something specific (placing a certain block, being by a certain mob)?

**Comment by It4llo** [comment]
freezes during the game

**Comment by lindstheginj** [comment]
And what happens during the game? Are you playing any other mods? Does your computer usually lag or freeze in Minecraft? We need to have a better idea of what’s happening.

**Comment by It4llo** [comment]
well, i fix, i just open and close the world a lot of times and the freezing bug stop
