### ISSUE TITLE
Allosaurus is missing teeth and pteranodon is making weird sounds

### ISSUE THREAD

**Issue by alfieboris** [FossilsArcheologyRevival/FossilsArcheologyRevival#1136]

**Comment by lindstheginj** [comment]
In the future, divide multiple issues into separate ones. Allosaurus teeth was already reported. What do you mean by "weird sounds?"

**Comment by PCAwesomeness** [comment]
He probably got caught off-guard by the new penguin noises Pteranodon got.

Either way, the former has already been addressed and the latter isn't even an issue; I'd say you can close this down.
