### ISSUE TITLE
Analyzer and Sifter automation

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1143]
I can't seem to attach conduits from Ender IO to those two, however, hopper can extract and insert items just fine
![2019-02-13_13 39 59](https://user-images.githubusercontent.com/22555489/52693892-9e5ee900-2f9a-11e9-9737-b8ab0a5c963b.png)
![2019-02-13_13 56 45](https://user-images.githubusercontent.com/22555489/52693893-9ef77f80-2f9a-11e9-8204-d6f83bbe571f.png)
![2019-02-13_13 37 20](https://user-images.githubusercontent.com/22555489/52693906-a7e85100-2f9a-11e9-9dc1-bc64d3b05c0b.png)
Culture vat seem to be fine for conduits
![2019-02-13_14 04 15](https://user-images.githubusercontent.com/22555489/52693925-b898c700-2f9a-11e9-946d-15e2da935f02.png)

**Comment by Alex-the-666** [comment]
issue with EnderIO
