### ISSUE TITLE
Mod wont work on aternos server?

### ISSUE THREAD

**Issue by Neverisme** [FossilsArcheologyRevival/FossilsArcheologyRevival#1146]
So me and my friend have a aternos server with fossils and arc on it, however spawn eggs simply are labeled "spawn" and no dinos or fossils will spawn in the world. We both tried the mod in single player and it worked fine, We were wondering if there was anyway to fix this or if anyone else has a similar problem?

**Comment by Baloob** [comment]
On my Server it's working

**Comment by Alex-the-666** [comment]
make sure the server has the mod installed. It sounds like its only installed on the clients

**Comment by GarchompGirl** [comment]
I think you have forgotten to add the Fossils and Archeology mod to your aternos server.
