### ISSUE TITLE
Can feed mobs at full health

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1159]
I tried to heal some of my injured mobs, and they still eat the food even as full health. If you do fix this can you make it so they can still eat from players to heal even as full hunger?

**Comment by lindstheginj** [comment]
This sounds like tame-by-feeding kicking in. Try it on a tamed mob of full hunger.

**Comment by mser7** [comment]
Tested on both wild and tamed mobs, yield the same above result

**Comment by Alex-the-666** [comment]
they tame like this
