### ISSUE TITLE
Feeder automation

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1161]
Hopper work fine, cant connect conduits to it

**Comment by Alex-the-666** [comment]
what is a conduit?

**Comment by mser7** [comment]
It is a transporting pipe from Ender IO

**Comment by Alex-the-666** [comment]
that would be an issue with Ender IO then. F/A uses the canInsertItem and canExtractItem methods, which all mods should support

**Comment by tterrag1098** [comment]
That would be true if it were still 2015. However IInventory/ISidedInventory are deprecated since the introduction of [capabilities](https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/). EnderIO stopped supporting IInventory a while ago.
