### ISSUE TITLE
Drum is busted

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1166]
When right clicking, it doesnt show which order it is, and when left click, it broke instantly

**Comment by NightSky64** [comment]
The drum doesn't work since I think 7.3

**Comment by mser7** [comment]
Why did you close this? Isnt it a bug that the drun hasnt working since?

**Comment by NightSky64** [comment]
It's probably intended to not work.

**Comment by lindstheginj** [comment]
^ it was intentionally disabled updates ago.
