### ISSUE TITLE
Megalania can be tamed at birth

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1167]
It's an apex predator. It should use the scarab.

I don't actually know if this is the new intended way to tame them, but from my testing none of the other apex predators are tamed this way so ???

**Comment by PCAwesomeness** [comment]
Keep it that way, honestly.

If I would, I'd suggest that you should actually remove the "beat-down" tame from the megalania; there are dinosaurs that are larger than it IRL, yet still can be tamed through conventional means.

**Comment by Adsper** [comment]
It's massive and can literally kill you in two hits, and it's the only thing with poison in the game. I'm pretty sure it earns its scarab. If there's others without a scarab that should have one then that's a different issue.

**Comment by lindstheginj** [comment]
Evil poison megalograptus should have been scarab tamed tbh. Good thing we fixed him.

**Comment by PCAwesomeness** [comment]
"It's massive and can literally kill you in two hits, and it's the only thing with poison in the game."

That's just it being overpowered. Also, the old Jurassic Park Dilophosaurus is calling; it wants its respect back.

**Comment by Adsper** [comment]
Like I said, that's a different issue. In the state that its in as of right now, it's more than strong enough for you to have to kick its ass.

**Comment by lindstheginj** [comment]
JP Dilo is completely irrelevant to the way the mod is now.

**Comment by PCAwesomeness** [comment]
@Adsper 

I'd prioritize fixing an issue over making it worse, TBH.

@lindstheginj 

I mean, sure, it's out of the picture by now, and this is good. However, my point is that it was able to poison prey and blind them (with its source even being able to spit the venom), and yet it was tamed via normal means. A lizard that is actually less powerful shouldn't be held on such a high pedestal, IMO.
