### ISSUE TITLE
Ticking loop block furnace

### ISSUE THREAD

**Issue by lampyr** [FossilsArcheologyRevival/FossilsArcheologyRevival#1168]
hi each time i add the mod and want to find a village i crash. but the crash didn't mention any mod or i didn't know.

https://gist.github.com/lampyr/3464ba8804a6e2380134cd99b16d5b78

**Comment by Alex-the-666** [comment]
that is quite a few mods you have installed. Try and see if you can narrow down which ones that, when used with F/A, cause this issue

**Comment by lampyr** [comment]
hi i don't have find the conflict but after update lots of mods for the moment it doesn't crash.
