### ISSUE TITLE
Megalodon DNA from Minecraft bone

### ISSUE THREAD

**Issue by NightSky64** [FossilsArcheologyRevival/FossilsArcheologyRevival#1170]
According to JEI, there's a 50% chance you will get megalodon DNA when analizing a bone, but all the other dnas have a 1% chance.

**Comment by NightSky64** [comment]
Similar issue with bone blocks: All the dnas have a 10% chance, except megalodon DNA, which has a 25% chance.

**Comment by Alex-the-666** [comment]
analyzing bones and blone blocks was a debug test that should have been removed. now fixed
