### ISSUE TITLE
Pets don't attack you

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1176]
I tried to have my tyrannosaurus to attack a chicken, but norhing happened

**Comment by NightSky64** [comment]
That's probably because of this issue https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1134

**Comment by mser7** [comment]
Oops, it was supposed to be *for you instead.
About thatl issue, I would expect the t-rex to at least run to the chicken, but in my case, it just stood still. Tested on a vanilla horse as well

**Comment by Alex-the-666** [comment]
fixed
