### ISSUE TITLE
Outer lair islands

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1181]
Travel 1000 blocks away from the Anus mansion to meet them

**Comment by Adsper** [comment]
What?

**Comment by mser7** [comment]
Yes

**Comment by lindstheginj** [comment]
Dude. What? Do they exist or are you asking for them? No one knows what this means and “yes” does not explain anything.

**Comment by mser7** [comment]
Sorry, yes, they do exist, I am as confused as you are

**Comment by Adsper** [comment]
Huh
![2019-02-16_07 58 15](https://user-images.githubusercontent.com/11862143/52902093-b3b55c80-31c0-11e9-9eec-67719b9e0b31.png)

Honestly I think these things should be kept if they aren't intended (and maybe expanded upon like the end islands), they're actually really cool.

**Comment by Alex-the-666** [comment]
not intended but cool so its staying. maybe players can build little hide outs there :)
