### ISSUE TITLE
Spino too strong pls nerf

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1188]
Jesus, 81 hp damage?
![2019-02-16_15 04 07](https://user-images.githubusercontent.com/22555489/52896905-8e484300-3200-11e9-90eb-0029d468f35c.png)
![2019-02-16_15 04 21](https://user-images.githubusercontent.com/22555489/52896906-8ee0d980-3200-11e9-9dfc-3d6382219d46.png)
![2019-02-16_15 04 43](https://user-images.githubusercontent.com/22555489/52896907-8ee0d980-3200-11e9-8167-e0186c60ebcd.png)
![2019-02-16_15 02 39](https://user-images.githubusercontent.com/22555489/52896908-8f797000-3200-11e9-9668-c03554286ed9.png)
![2019-02-16_15 02 41](https://user-images.githubusercontent.com/22555489/52896909-8f797000-3200-11e9-8f4d-9dd99114bb04.png)

**Comment by mser7** [comment]
its strength should be as strong as the T-rex, maybe a little stronger

**Comment by NightSky64** [comment]
T. rex was a bulkier and stronger predator, so it would make more sense to make spino weaker than T. rex.

**Comment by BlueWither** [comment]
I like the current situation.
Tyrannosaurus is simply a strong dinosaur.
However, aquatic large organisms such as Spinosaurus are extremely strong and I think that it is good to have a outstanding feeling.

**Comment by NightSky64** [comment]
No, spinosaurus was not that strong. T. rex had a bone crushing jaw and spino's was made mostly for fishing. Spinosaurus wasn't that much aquatic, anyway.
