### ISSUE TITLE
Buff T-rex a bit

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1193]
Fully grown Tyrannosaur should be able to one should a human, so 20 - 25 damage please

**Comment by NightSky64** [comment]
I'd say T. rex should have 30 damage.

**Comment by lindstheginj** [comment]
Would you please knock it off? This is not a bug. We already asked you to only report bugs. This is ridiculous.

**Comment by mser7** [comment]
Sorry, just that I thought that the T-rex currently is weak, will close this then
