### ISSUE TITLE
Sarcosuchus, Liopleurodon, Spinosaurus, Mosasaurus and Megalodon are all too strong

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1197]
#1188 

![2019-02-16_23 21 57](https://user-images.githubusercontent.com/22555489/52902450-88278600-3243-11e9-8747-e001e5da9a51.png)
![2019-02-16_23 21 58](https://user-images.githubusercontent.com/22555489/52902451-88c01c80-3243-11e9-81f6-0639585052a3.png)
![2019-02-16_23 22 06](https://user-images.githubusercontent.com/22555489/52902452-88c01c80-3243-11e9-8e4f-7546b88e0f18.png)
![2019-02-16_23 11 52](https://user-images.githubusercontent.com/22555489/52902453-8958b300-3243-11e9-93f7-f87712096a38.png)
![2019-02-16_23 12 06](https://user-images.githubusercontent.com/22555489/52902457-89f14980-3243-11e9-9ddf-561cb77888f8.png)
![2019-02-16_23 12 07](https://user-images.githubusercontent.com/22555489/52902458-8a89e000-3243-11e9-92a8-3ea18014fad1.png)
![2019-02-16_23 12 20](https://user-images.githubusercontent.com/22555489/52902459-8a89e000-3243-11e9-84ad-1f0e20b9399c.png)
![2019-02-16_23 13 17](https://user-images.githubusercontent.com/22555489/52902461-8b227680-3243-11e9-89f4-722dca88cffa.png)
![2019-02-16_23 13 20](https://user-images.githubusercontent.com/22555489/52902462-8b227680-3243-11e9-80d5-17580d06b352.png)
![2019-02-16_23 14 11](https://user-images.githubusercontent.com/22555489/52902463-8bbb0d00-3243-11e9-988b-392808a2c8e6.png)
![2019-02-16_23 14 21](https://user-images.githubusercontent.com/22555489/52902464-8c53a380-3243-11e9-9c3a-60c18491892f.png)
![2019-02-16_23 14 22](https://user-images.githubusercontent.com/22555489/52902465-8c53a380-3243-11e9-8408-c63ab1ba6638.png)
![2019-02-16_23 21 12](https://user-images.githubusercontent.com/22555489/52902466-8cec3a00-3243-11e9-9fce-90b05ee2103b.png)
![2019-02-16_23 21 26](https://user-images.githubusercontent.com/22555489/52902467-8cec3a00-3243-11e9-903a-009b1878f3a1.png)
![2019-02-16_23 21 27](https://user-images.githubusercontent.com/22555489/52902468-8d84d080-3243-11e9-98a3-4b973eb2131e.png)
![2019-02-16_23 21 28](https://user-images.githubusercontent.com/22555489/52902469-8d84d080-3243-11e9-9ef0-15a00bb877ea.png)

**Comment by NightSky64** [comment]
That's probably intended, although it doesn't make with spinosaurus and liopleurodon.

**Comment by mser7** [comment]
Here's an idea, I notice Sarco, Megalodon, Spino and Mosa all have a unique "grab attack", hence why sometimes it deal up to 100 - 200 damage in those pics, how about nerf both attacks, normal bitting attacks to be on the same level as the T-rex, and nerf the grab attack to 30-50 damage.

**Comment by NightSky64** [comment]
Sarcosuchus doesn't have a death roll attack anymore because the real animal couldn't death roll.

**Comment by Alex-the-666** [comment]
fixed
