### ISSUE TITLE
Large Herbivores like to have a staring contest with cockatrice from Ice and Fire

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1199]
Tried Anky vs cockatrice, the cockatrice stand still to stare at the charging anky, when the dino get close to the cockatrice, it stand still, gazing into it, instead of hit it with its tail. My assumption would be the anky standing still to wait for the enemy to move close, and swing it, but the cockatrice never did.

**Comment by mser7** [comment]
Not sure if this would happen when vs skeleton, as they don't just charge in like zombies

**Comment by lindstheginj** [comment]
Couldnt most of these issues just be covered by the “mobs are bad at attacking” issue

**Comment by mser7** [comment]
I could does that, but it will have a horrible description, and I remember you guys was telling people to make separated issues

**Comment by lindstheginj** [comment]
But are they separate issues

**Comment by mser7** [comment]
If I find any more, which most likely will, I will compose them into one.

**Comment by mser7** [comment]
Tested with other herbivores like Parasaurolophus, Triceraptops, Stegosaurus, all have the same result
![2019-02-17_10 09 46](https://user-images.githubusercontent.com/22555489/52908036-e3876180-329f-11e9-85f5-9b5a2bab0525.png)
![2019-02-17_10 09 47](https://user-images.githubusercontent.com/22555489/52908037-e41ff800-329f-11e9-9507-84c1e39af534.png)
![2019-02-17_10 09 32](https://user-images.githubusercontent.com/22555489/52908038-e41ff800-329f-11e9-9803-891ac8a5ac90.png)
https://imgur.com/a/uUxxUaZ

**Comment by Alex-the-666** [comment]
fixed
