### ISSUE TITLE
High Nautilus Spawn Rate (ref: #220 Dec2015)

### ISSUE THREAD

**Issue by DVorriose** [FossilsArcheologyRevival/FossilsArcheologyRevival#1223]
Mod looks great, but Nautilus spawn rate appears very high (overrides some other modded mobs, but not squids) and can't be seen or adjusted in config.

Is there any way you could add spawn weights and possibly a dim/biome white/blacklist in config instead of a Boolean?

**Comment by 4f6f3b** [comment]
See #1114.
