### ISSUE TITLE
Dinosaur block breaking issue

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#1224]
In my world, I am keeping two species: dodos, and T-rex, I resurrected the dodos first and put many of them in their pence, then I resurrect T-rex and put its enclosure next to the dodo, I did some testing with the T-rex, and notice they don't break block, my config does turn that to true, but I just leave it. The I resurrect another T-rex, then, the first T-rex begin to break block in its enclosure, I put away the second T-rex, and relog, and it stop, after I put down the second T-rex again, and the first one break blocks again

**Comment by Alex-the-666** [comment]
dupe #1539
