### ISSUE TITLE
Sleeping/Machine/Health/Happiness bugs

### ISSUE THREAD

**Issue by TheDeinonychus** [FossilsArcheologyRevival/FossilsArcheologyRevival#1227]
So, been playing a while with the new update, and here are some stand-out bugs I've noticed so far. 

-Nocturnal animals are always asleep, diurnal animals always awake. Animals will respond to commands as normal, but return to sleeping/awake once set back to 'wander'. Using /set time night doesn't affect animal behavior, though setting the exact time will cause animals to sleep/awaken respective of their cycle. However, nocturnal animals return to always sleeping while diurnal animals are always awake once time progresses naturally.

-Machines do not seem to respond to certain pipes/conduits/ducts as expected. Of note the Ender IO conduits do not connect, while Buildcraft pipes and Thermal Expansion itemducts do, though only from certain faces. Of note Feeders only accept piped items from the sides, not top or bottom. After some digging it seems that FAR is still using an outdated method of handling inserted/extracted items, rather than the newer method used by other mods. Not sure why Buildcraft and Thermal Expansion still work. Assuming they still make use of the older method for legacy compatibility. 

-Animals' max health increases as they mature, though their current health does not regen despite having full hunger. This may be an issue with feeding from Feeders not actually registering as the animals being fed for the purposes of regaining health. 

-Some animals seem to ignore toys (balls, scratching posts, etc.) and do not gain happiness. Currently observed in the Pachy, though may affect others as well. 

Fossils and Archeology Revival v. 8.0.0
Minecraft v. 1.12.2
Forge v. 14.23.5.2772
LLibrary 1.7.17-1.12.2

**Comment by lindstheginj** [comment]
In the future, please split your bug reports into separate issues - at least 3 of these have been reported before, but we cannot close them as duplicates because they are all listed together with potentially valuable info

**Comment by mser7** [comment]
#1225 
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1177
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1160
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1145
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1194

**Comment by TheDeinonychus** [comment]
Alright then. I figured I wouldn't spam multiple issues in separate reports, but if that's preferred, I will keep that in mind.
