### ISSUE TITLE
Game crash when plaeo block is placed

### ISSUE THREAD

**Issue by Coorree** [FossilsArcheologyRevival/FossilsArcheologyRevival#1245]
Hello,

When I placed a Paleo block (not the planks !), my game is just crashing, there is the crash report, I don't know if it's from this mod or from LLibrary but I don't have others mods installed with new blocks so it's could be this mod.

(sorry for my english, It's no my native language ;))

Crash raport:

<<
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 2/24/19 6:39 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=axis, clazz=class net.minecraft.block.BlockLog$EnumAxis, values=[x, y, z, none]} as it does not exist in BlockStateContainer{block=fossil:palm_log, properties=[axis]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:223)
	at net.minecraft.block.BlockLog.func_180642_a(BlockLog.java:47)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2254)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:52)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:223)
	at net.minecraft.block.BlockLog.func_180642_a(BlockLog.java:47)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2254)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:52)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheCore_'/176, l='MpServer', x=-3849.79, y=65.00, z=839.41]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (139,64,309), Chunk: (at 11,4,5 in 8,19; contains blocks 128,0,304 to 143,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1087597 game time, 1232384 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 111 total; [EntitySpider['Spider'/42240, l='MpServer', x=-3774.50, y=25.00, z=886.50], EntityCreeper['Creeper'/42241, l='MpServer', x=-3895.50, y=17.00, z=856.50], EntityCreeper['Creeper'/42242, l='MpServer', x=-3898.50, y=17.00, z=860.50], EntitySheep['Sheep'/23312, l='MpServer', x=-3870.83, y=69.00, z=771.64], EntitySheep['Sheep'/23313, l='MpServer', x=-3866.84, y=69.00, z=785.85], EntityHorse['Horse'/23314, l='MpServer', x=-3851.80, y=66.00, z=875.27], EntityMinecartChest['Minecart with Chest'/277, l='MpServer', x=-3904.63, y=19.00, z=794.58], EntitySheep['Sheep'/278, l='MpServer', x=-3908.30, y=67.00, z=799.48], EntityHorse['Horse'/23319, l='MpServer', x=-3851.06, y=68.00, z=911.15], EntityWolf['Wolf'/23320, l='MpServer', x=-3850.43, y=65.00, z=885.64], EntityCreeper['Creeper'/42265, l='MpServer', x=-3906.21, y=19.00, z=819.41], EntityCreeper['Creeper'/42266, l='MpServer', x=-3894.94, y=19.00, z=811.45], EntityHorse['Horse'/23835, l='MpServer', x=-3784.06, y=70.00, z=826.12], EntityHorse['Horse'/23324, l='MpServer', x=-3828.93, y=67.00, z=813.03], EntityHorse['Horse'/23836, l='MpServer', x=-3790.31, y=70.00, z=823.87], EntityCow['Cow'/23325, l='MpServer', x=-3845.08, y=66.00, z=816.17], EntityHorse['Horse'/23837, l='MpServer', x=-3791.27, y=70.00, z=822.16], EntityCow['Cow'/23326, l='MpServer', x=-3848.93, y=66.00, z=815.07], EntityHorse['Horse'/23838, l='MpServer', x=-3776.10, y=64.00, z=866.00], EntityCow['Cow'/23327, l='MpServer', x=-3846.36, y=66.00, z=818.87], EntityCow['Cow'/23328, l='MpServer', x=-3845.43, y=66.00, z=820.21], EntityBat['Bat'/41760, l='MpServer', x=-3908.99, y=21.29, z=818.63], EntityCow['Cow'/23329, l='MpServer', x=-3846.05, y=66.00, z=815.22], EntityCow['Cow'/23330, l='MpServer', x=-3846.73, y=66.00, z=820.92], EntityCreeper['Creeper'/42275, l='MpServer', x=-3779.50, y=26.00, z=911.50], EntityCreeper['Creeper'/42029, l='MpServer', x=-3924.50, y=20.00, z=837.50], EntityHorse['Horse'/23599, l='MpServer', x=-3825.09, y=64.00, z=862.13], EntityHorse['Horse'/303, l='MpServer', x=-3907.41, y=64.00, z=905.82], EntityZombie['Zombie'/42031, l='MpServer', x=-3924.71, y=20.00, z=836.51], EntityHorse['Horse'/23600, l='MpServer', x=-3824.62, y=66.00, z=913.74], EntityHorse['Horse'/23601, l='MpServer', x=-3833.93, y=66.00, z=909.99], EntityHorse['Horse'/23602, l='MpServer', x=-3826.09, y=66.00, z=909.24], EntityMinecartChest['Minecart with Chest'/23603, l='MpServer', x=-3825.50, y=18.06, z=849.49], EntityCreeper['Creeper'/41782, l='MpServer', x=-3925.50, y=17.00, z=871.50], EntityHorse['Horse'/23863, l='MpServer', x=-3774.02, y=69.00, z=903.86], EntityHorse['Horse'/311, l='MpServer', x=-3921.20, y=67.00, z=910.46], EntitySpider['Spider'/42302, l='MpServer', x=-3774.50, y=25.00, z=888.50], EntityBat['Bat'/42312, l='MpServer', x=-3895.32, y=22.10, z=839.25], EntityBat['Bat'/42314, l='MpServer', x=-3842.25, y=20.03, z=836.63], EntityCow['Cow'/23628, l='MpServer', x=-3822.23, y=64.00, z=868.16], EntitySkeleton['Skeleton'/42318, l='MpServer', x=-3911.50, y=19.00, z=835.50], EntityHorse['Horse'/23631, l='MpServer', x=-3807.95, y=66.00, z=918.03], EntityHorse['Horse'/23634, l='MpServer', x=-3808.07, y=68.00, z=824.00], EntityCreeper['Creeper'/42325, l='MpServer', x=-3815.50, y=29.00, z=919.50], EntityWitch['Witch'/42326, l='MpServer', x=-3908.50, y=19.00, z=830.50], EntitySkeleton['Skeleton'/42327, l='MpServer', x=-3895.50, y=14.00, z=878.50], EntityCreeper['Creeper'/42329, l='MpServer', x=-3783.50, y=27.00, z=812.50], EntityZombie['Zombie'/42330, l='MpServer', x=-3894.50, y=20.00, z=824.50], EntityMinecartChest['Minecart with Chest'/22620, l='MpServer', x=-3894.49, y=19.00, z=812.34], EntitySheep['Sheep'/22621, l='MpServer', x=-3899.70, y=67.00, z=808.31], EntityHorse['Horse'/22622, l='MpServer', x=-3889.68, y=64.00, z=887.19], EntityHorse['Horse'/22623, l='MpServer', x=-3890.97, y=71.00, z=917.00], EntityBat['Bat'/42336, l='MpServer', x=-3874.65, y=24.08, z=889.20], EntityBat['Bat'/42337, l='MpServer', x=-3874.59, y=15.68, z=889.80], EntityBat['Bat'/42338, l='MpServer', x=-3884.60, y=14.02, z=898.60], EntityHorse['Horse'/23652, l='MpServer', x=-3811.83, y=68.00, z=840.74], EntityHorse['Horse'/23654, l='MpServer', x=-3807.26, y=65.00, z=817.54], EntityHorse['Horse'/23655, l='MpServer', x=-3798.53, y=69.00, z=828.33], EntityHorse['Horse'/23656, l='MpServer', x=-3797.29, y=69.00, z=825.65], EntityWolf['Wolf'/23657, l='MpServer', x=-3799.13, y=62.60, z=809.76], EntityZombie['Zombie'/42349, l='MpServer', x=-3823.46, y=21.00, z=862.25], EntitySkeleton['Skeleton'/42350, l='MpServer', x=-3815.50, y=32.00, z=871.50], EntityCreeper['Creeper'/42351, l='MpServer', x=-3781.50, y=37.00, z=872.50], EntityPlayerSP['TheCore_'/176, l='MpServer', x=-3849.79, y=65.00, z=839.41], EntitySpider['Spider'/42370, l='MpServer', x=-3834.50, y=21.00, z=861.50], EntitySkeleton['Skeleton'/42371, l='MpServer', x=-3808.50, y=31.00, z=792.50], EntityZombie['Zombie'/42122, l='MpServer', x=-3784.48, y=39.00, z=877.29], EntitySkeleton['Skeleton'/41611, l='MpServer', x=-3799.50, y=12.00, z=793.50], EntitySquid['Squid'/42392, l='MpServer', x=-3826.06, y=58.75, z=779.92], EntityCreeper['Creeper'/41625, l='MpServer', x=-3919.50, y=17.00, z=873.50], EntitySquid['Squid'/42393, l='MpServer', x=-3819.58, y=57.02, z=780.63], EntitySquid['Squid'/42394, l='MpServer', x=-3814.88, y=57.56, z=781.72], EntityZombie['Zombie'/41629, l='MpServer', x=-3914.50, y=19.00, z=902.50], EntitySpider['Spider'/42147, l='MpServer', x=-3839.50, y=19.00, z=851.50], EntityMinecartChest['Minecart with Chest'/23206, l='MpServer', x=-3879.49, y=20.06, z=779.50], EntityZombie['Zombie'/42406, l='MpServer', x=-3831.50, y=21.00, z=857.50], EntitySheep['Sheep'/23207, l='MpServer', x=-3881.54, y=69.00, z=778.73], EntityCreeper['Creeper'/41639, l='MpServer', x=-3916.50, y=17.00, z=877.50], EntityZombie['Zombie'/42407, l='MpServer', x=-3833.50, y=21.00, z=856.50], EntityMinecartChest['Minecart with Chest'/23208, l='MpServer', x=-3876.50, y=12.06, z=868.50], EntityMinecartChest['Minecart with Chest'/23209, l='MpServer', x=-3886.19, y=13.00, z=908.72], EntitySpider['Spider'/42414, l='MpServer', x=-3821.50, y=31.00, z=867.50], EntitySkeleton['Skeleton'/42415, l='MpServer', x=-3818.50, y=31.00, z=865.50], EntityCreeper['Creeper'/42417, l='MpServer', x=-3781.50, y=37.00, z=873.50], EntityCreeper['Creeper'/42418, l='MpServer', x=-3880.50, y=20.00, z=866.50], EntitySkeleton['Skeleton'/42421, l='MpServer', x=-3821.50, y=31.00, z=868.50], EntitySkeleton['Skeleton'/42422, l='MpServer', x=-3821.50, y=31.00, z=866.50], EntitySquid['Squid'/41917, l='MpServer', x=-3909.60, y=59.00, z=859.60], EntityZombie['Zombie'/41664, l='MpServer', x=-3832.50, y=21.00, z=857.50], EntityZombie['Zombie'/41665, l='MpServer', x=-3830.50, y=21.00, z=856.50], EntityZombie['Zombie'/42179, l='MpServer', x=-3913.50, y=50.00, z=826.50], EntitySkeleton['Skeleton'/42181, l='MpServer', x=-3913.50, y=50.00, z=828.50], EntitySpider['Spider'/42182, l='MpServer', x=-3888.68, y=15.10, z=829.32], EntityBat['Bat'/42439, l='MpServer', x=-3841.05, y=20.39, z=836.96], EntityBat['Bat'/42199, l='MpServer', x=-3873.25, y=19.35, z=847.13], EntityBat['Bat'/42200, l='MpServer', x=-3827.25, y=27.10, z=859.44], EntityBat['Bat'/42204, l='MpServer', x=-3856.75, y=20.10, z=853.75], EntitySkeleton['Skeleton'/41696, l='MpServer', x=-3789.50, y=44.00, z=812.50], EntityCreeper['Creeper'/42214, l='MpServer', x=-3916.50, y=50.00, z=828.50], EntitySkeleton['Skeleton'/41709, l='MpServer', x=-3889.50, y=19.00, z=901.50], EntityEnderman['Enderman'/41710, l='MpServer', x=-3872.50, y=16.00, z=851.50], EntityZombie['Zombie'/42226, l='MpServer', x=-3915.50, y=50.00, z=827.50], EntityZombie['Zombie'/42227, l='MpServer', x=-3913.50, y=50.00, z=827.50], EntitySkeleton['Skeleton'/42228, l='MpServer', x=-3916.50, y=50.00, z=831.50], EntityZombie['Zombie'/42229, l='MpServer', x=-3895.43, y=17.00, z=850.77], EntitySkeleton['Skeleton'/42230, l='MpServer', x=-3773.50, y=25.00, z=886.50], EntityWitch['Witch'/41975, l='MpServer', x=-3908.50, y=19.00, z=834.50], EntityCreeper['Creeper'/41976, l='MpServer', x=-3898.50, y=19.00, z=842.50], EntityBat['Bat'/41720, l='MpServer', x=-3927.25, y=13.10, z=846.75], EntityBat['Bat'/41725, l='MpServer', x=-3929.25, y=19.10, z=815.75], EntityCreeper['Creeper'/42239, l='MpServer', x=-3894.50, y=17.00, z=860.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 509135368 bytes (485 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2773 Optifine OptiFine_1.12.2_HD_U_E3 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID           | Version      | Source                             | Signature                                |
	|:--------- |:------------ |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft    | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp          | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2773.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge        | 14.23.5.2773 | forge-1.12.2-14.23.5.2773.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | llibrary     | 1.7.17       | llibrary-1.7.17-1.12.2 (1).jar     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | fossil       | 8.0.0        | fossilsarcheology-8.0.0.jar        | None                                     |
	| UCHIJAAAA | jei          | 4.8.5.159    | jei_1.12.2-4.8.5.159.jar           | None                                     |
	| UCHIJAAAA | xaerominimap | 1.16         | Xaeros_Minimap_1.16_Forge_1.12.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.73' Renderer: 'GeForce GT 520/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2773
	LWJGL: 2.9.4
	OpenGL: GeForce GT 520/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.73, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.12.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.73
	OpenGlRenderer: GeForce GT 520/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

>>

**Comment by tyranno66** [comment]
Duplicate that is already fixed.
