### ISSUE TITLE
Blank "config"

### ISSUE THREAD

**Issue by ottotrainer445092** [FossilsArcheologyRevival/FossilsArcheologyRevival#1247]
On all of my mods, only this mod had a almost missing "config". It was a darkened button, un-clickable. I know you can do things like feathers or no feathers or, block breaking. But yet I can't get the option to use them. -1.12.2

**Comment by NightSky64** [comment]
You need to go to your .minecraft folder, where you will find the config folder in which you can find the fossil.json. Open the json with notepad.

**Comment by Adsper** [comment]
Think they're saying you should be able to access the config from here.
![config](https://user-images.githubusercontent.com/11862143/53304221-b13dad00-3827-11e9-9911-bce3ba1f83fd.png)

**Comment by Canus8** [comment]
I have a cfg file instead of a json file, and no way of opening it.  Also, the link takes you to their 1.7.10 page on the minecraft forum.  That is also kind of abstract for average players to find to turn off block breaking.  I do believe that it should be accessible from the mod options page.

**Comment by lindstheginj** [comment]
Config can be accessed in game as of 8.0.1.
