### ISSUE TITLE
Some animals may change their sexes while growing up

### ISSUE THREAD

**Issue by Dudelindo** [FossilsArcheologyRevival/FossilsArcheologyRevival#1249]
I created an enclosure with four velociraptors. After all the eggs hatched, I checked if they were male or female with my dinopedia. All of them were females. I considered myself lucky, because I didn't want them to reproduce. When they finally became adults, I noticed that one of them was a male.
Same happened with two meganeuras. Both were male but one of them became a female.

**Comment by NightSky64** [comment]
Looks like someone added frog DNA.

**Comment by Velocihater** [comment]
Life always finds a way
