### ISSUE TITLE
Feeders should display a particle effect when a dinosaur eats

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1255]
This would make it so there's no more questions about "does x animal eat from feeder" and make it easier to test.

This was actually in the mod at some point a long long time ago but it got left behind, you can see it here in a pic I dug up: 
![image](https://user-images.githubusercontent.com/11862143/53553479-a5d1d680-3af2-11e9-9f17-adaf48fc76d1.png)

**Comment by Spinogaming** [comment]
i support this, though maybe the particles that appear should correspond to whats being eaten

**Comment by Alex-the-666** [comment]
not a bad idea ill see to it
