### ISSUE TITLE
Aquatic Apexes Don't Seem to be Tamable

### ISSUE THREAD

**Issue by LialaOkami** [FossilsArcheologyRevival/FossilsArcheologyRevival#1257]
I've tried to tame both a 13 day old Megalodon and a 13 day old Liopleurodon, and neither ever went to sleep, despite getting down to 5 health. I assumed this was merely because they were aquatic, so I tried to use the Aquatic Scarab Gem on them anyway, but that didn't work. I was curious if maybe it was miswritten to be the regular Scarab Gem and tried that, but it didn't work either.
I was able to tame a T-Rex earlier so I'm assuming this is a bug of some sort?
idk it seems like it hasn't been mentioned in any other bug posts. I'm using no other mods (not counting Optifine),and am in Creative mode if that has any affect.

Thank you for reading!

**Comment by Spinogaming** [comment]
Liopleurodon don't need to be tamed that way anymore

**Comment by LialaOkami** [comment]
Oh. How is it tamed now?

**Comment by Spinogaming** [comment]
Just stay near the egg

**Comment by lindstheginj** [comment]
Were you able to get the megalodon to tame?
