### ISSUE TITLE
Nautilus should be immune to fall damage

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1259]

**Comment by Spinogaming** [comment]
but why though? Even if they are in their shells, that should actually still hurt them

**Comment by NightSky64** [comment]
I always wondered if something so soft and boneless could be hurt by fall.

**Comment by Alex-the-666** [comment]
it would hurt, especially being so soft and boneless. alot of their organs would rupture
