### ISSUE TITLE
construct's armory Conflict

### ISSUE THREAD

**Issue by mailleseraph** [FossilsArcheologyRevival/FossilsArcheologyRevival#1265]
using 8.0.0 release, Tar is showing as a missing material in the tinker's construct compatibility(cannot make tar parts, you get an empty tinker's item instead), tar fluid does generate in the smeltery though. I assume this isn't done, and I wouldn't bring it up, but you also have coal and charcoal making liquid tar in the smeltery, which gets in the way of the thermal expansion liquifacted coal recipe. could we get a config to disable the liquid tar from coal/charcoal recipe in the next update?

**Comment by mailleseraph** [comment]
for now I can remove the recipe with crafttweaker/modtweaker but it would be nice to have the config anyway

**Comment by Alex-the-666** [comment]
what do you mean, missing?

You can get tar into the smeltery the same way as you can with lava/water, by clicking on the Smelterly Drain with a Bucket of Tar.

**Comment by mailleseraph** [comment]
any parts cast don't work, if you make a tool rod, for example, it is a textureless item with zeroed stats, but yeah, bucketing it out would work, if every tar drop/coal gave you more than a "nugget" of material(18mB I think?), I removed it by starting a cast and breaking the block.

**Comment by Alex-the-666** [comment]
Hi, i just tested it with a clean minecraft with the following mods, and the tar worked perfectly, I was able to bucket into a smeltery fine with a tar bucket and make it by putting tar drops in the smeltery as well.

mod list

- LLibrary 1.12.2 1.7.17
- Fossils and Archeology Revival 1.12.2 8.0.0
- iChunUtil 1.12.2 7.1.4
- Mantle 1.12.2 1.3.3.39
- Tabula 1.12.2 7.0.0
- Tinkers' Construct 1.12.2 2.12.0.115
- The Betweenlands 1.12.2 3.4.1

I am of the belief that there is a mod conflict with our addition of tar. Is a similar issue present with the F/A added material Ancient Metal?

**Comment by mailleseraph** [comment]
Not sure about ancient metal, I will putter about and see if I can figure out what is causing the interaction

**Comment by mailleseraph** [comment]
OKAY!!!! I think I have this figured out! using the mods you listed above, (minus tabula, minus betweenlands, plus JEI) tar works fine. however, if I add construct's armory, I get the problem listed above where the tar parts are cast as invalid items.

**Comment by mailleseraph** [comment]
opened an issue on constructs armory https://github.com/TheIllusiveC4/ConstructsArmory/issues/149

**Comment by TheIllusiveC4** [comment]
I've investigated this issue and found that the problem can be solved by modifying this section:
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/blob/68b4331ac1efe920de4579ca3ae888dc8af8c393/src/main/java/fossilsarcheology/server/compat/tinkers/TinkersCompat.java#L44-L48

By changing these lines to `TinkerRegistry.integrate(material).preInit` instead, everything works as it should. It should be noted that I also changed the loading order/structure for this entire method beforehand as part of a different test, but I'm not sure that has any bearing on the outcome. I'm also still not sure why only Construct's Armory causes this result, I'd be open to some insight on that aspect.

**Comment by mailleseraph** [comment]
I looked at another mod that adds tool parts(immersive engineering) and they also integrate their parts at TinkerRegistry.integrate(material).preInit() I don't know enough to know what is "standard" but the fix TheIllusiveC4 posted worked for me. (as an aside, and I don't know where to ask this, when I compiled the mod from gradlew I had a bunch of missing textures on the dinopedia, amber item, tar, ancient logs, and a couple other things, is there another step I am missing when building this mod from GitHub?)
