### ISSUE TITLE
Biome fossil:lair of darkness spawning in overworld

### ISSUE THREAD

**Issue by MohawkyMagoo** [FossilsArcheologyRevival/FossilsArcheologyRevival#1268]
I have a biome called Anu spawning in the overworld - I'm assuming its from F&A?  Its all featureless nether like stuff. I cant find any such biome referenced in the F&A config? But NEI tells me its fossil:lair of darkness biome ID 46 anu.  (46 is the dynamic biome ID forge has assigned it) Are you hard coding biome ID's ? Because thats not necessary in 1.12 It seems to be set to Nether / Void / Spooky for spawning - I dont think Spooky is an appropriate setting which might be causing the problem, if its supposed to be a Nether biome?

**Comment by MohawkyMagoo** [comment]
![2019-03-06_02 08 46](https://user-images.githubusercontent.com/2426129/53863171-5b17f900-3fe1-11e9-96ea-43b484fa119e.png)

**Comment by lindstheginj** [comment]
If you go to the config file (.minecraft -> config folder -> fossil.cfg) you should be able to change the biome ID for the lair of darkness to something else. Choose a high number that other mods are not likely to use to prevent conflicts like this from happening.

**Comment by MohawkyMagoo** [comment]
But conflicts like this are not supposed to happen anymore because Forge in 1.12 dynamically assigns biome ID's to ensure it doesnt - are you hard coding your biome IDs?

**Comment by MohawkyMagoo** [comment]
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/148ff36ba6ce9d64e4d8ca055c509b232c55d9a3#diff-aa75b1974730689c57be27c398e97291

**Comment by MohawkyMagoo** [comment]
Still no fix?
