### ISSUE TITLE
My megalodon died and didn't drop anything

### ISSUE THREAD

**Issue by Dudelindo** [FossilsArcheologyRevival/FossilsArcheologyRevival#1269]
It was tamed and died out of the water

**Comment by BlueWither** [comment]
It drops only meat, but it is very rare...
#1075

**Comment by ParasiticSquid** [comment]
Shoot, this an issue with more then megalodon. A lot of the mobs half to time drop nothing and the other half they only drop a few bones but no meat. The ranom item drop was annoying in past versions and it's still annoying now if not more so.

They should set it so all items drop from the prehistoric creatures to prevent issues like these similar to what jurassicraaft has done.. all the bones can do is make bonemeal and get DNA from so kind of useless atm but the fact you can't get certain bones from a LIVING creature that has a fully skeleton is kind of weird.
If it was a fossil you didn't get the full set from that would make more sense
