### ISSUE TITLE
Problems with Spawning in Anubis Dimension

### ISSUE THREAD

**Issue by daforsyth** [FossilsArcheologyRevival/FossilsArcheologyRevival#1271]
Did the ritual to go into the dimension to fight Anubis and it teleported me inside the void. Had to find the location in single player, then use elytra to fly to it. For some reason, it doesn't teleport you the obsidian platform.

**Comment by SureinDragon** [comment]
I can confirm this is also happening in my modpack. Too many mods to list here for bugtesting though.
