### ISSUE TITLE
Trying to place Palaeoraphe logs only places ghost blocks when in multiplayer

### ISSUE THREAD

**Issue by DanTheDetermined** [FossilsArcheologyRevival/FossilsArcheologyRevival#1272]
Alright, so this seems to be the same thing as issue 1109, but that ones almost a month old, and that's crashing in singleplayer. When I place the logs, it seems like I placed them and i can walk on them, but when i leave the area, relog, or try and place a block off of the log, it disappears/gets replaced with the block i'm placing. Typical ghost block behavior. I can still place them using dispensers with quark. Here's the crash report from singleplayer, pretty much the same as 1109: https://pastebin.com/x0QK77WX

**Comment by Alex-the-666** [comment]
fixed
