### ISSUE TITLE
Sarco looks awaken, but it is sleeping when seeing dinopedia

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1273]
![2019-03-09_21 17 05](https://user-images.githubusercontent.com/34153394/54071593-052da480-42b2-11e9-9a37-16b906913cd2.png)
![2019-03-09_21 17 08](https://user-images.githubusercontent.com/34153394/54071597-0bbc1c00-42b2-11e9-88b6-31bb3eb42aff.png)

**Comment by lindstheginj** [comment]
Refer to #1407
