### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by MadRatSRP** [FossilsArcheologyRevival/FossilsArcheologyRevival#1278]
[crash-2019-03-12_10.00.14-server.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/2955509/crash-2019-03-12_10.00.14-server.txt)
[crash-2019-03-12_09.56.08-server.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/2955510/crash-2019-03-12_09.56.08-server.txt)

**Comment by Darkfiend009** [comment]
Same here. Identical crashlog.

**Comment by Alex-the-666** [comment]
fixed
