### ISSUE TITLE
Fossils Tar overwrites Betweenlands Tar

### ISSUE THREAD

**Issue by SureinDragon** [FossilsArcheologyRevival/FossilsArcheologyRevival#1281]
- It looks like the Fossils Archeology Revival mod tar replaces the betweenlands tar. When I pick up tar in the betweenlands, in both a regular bucket and a weedwood bucket, the tar is registered as "fossils" type tar. Betweenlands tar does not seem to exist in the game anymore.
- So far, it does not seem to cause any issues with tar beast spawning (when generating chunks), or tar jar spawning. But it does alter the physics so it matches Fossils tar instead of betweenlands, which is an issue for players fighting tar beasts.

I noticed this issue first in my very big modpack, but when I just have Forge, LLibrary, Fossils, and Betweenlands installed on a fresh instance the issue still occurs.

![tarconflict](https://user-images.githubusercontent.com/48839033/54844575-7ac34880-4c94-11e9-992c-1e127a368bdf.PNG)

As a side note, alligator gar also spawn in the betweenlands. :( Would it be possible to add dimensional blacklists for water mobs?

**Comment by Sluggasaurus** [comment]
Can confirm FA removing Betweenlands tar completely from the game, and word on when this might be fixed?

**Comment by BlueWither** [comment]
Betweenland's tar is generate only in the underground, and it is rare.
You should search it again.

**Comment by Alex-the-666** [comment]
fixed in 8.0.2
