### ISSUE TITLE
incomplete source code

### ISSUE THREAD

**Issue by aglarcz** [FossilsArcheologyRevival/FossilsArcheologyRevival#1283]
Hi, would it be possible to add full source code including latest fixes to this github? I would like to build new jar myself to test those new fixes and provide feedback but source looks incomplete as some of those closed issues dont have their commits and i found some bugs which are not in current release but are present after building the jar from github.

I am java beginner but would like to contribute by translating into czech language and by helping with some basic stuff. I would also like to make custom build of this mod for my server with some minor tweaks.

**Comment by Alex-the-666** [comment]
the full source code is here...
