### ISSUE TITLE
Ankylosaurus do not eat from anything except a feeder

### ISSUE THREAD

**Issue by MultiDavid2** [FossilsArcheologyRevival/FossilsArcheologyRevival#1284]
I am playing on a server in 1.12 and I left an Ankylosaurus near an area with plants, small trees and a decent amount of ferns, I came back an hour or so later and it hadn't eaten anything whilst its hunger had sharply dropped. They seem to refuse eating anything but stuff fed to them manually or with feeders. I haven't tested this out on any other herbivore yet.
Edit: The server has a selection of other mods, I can name them if it is needed.

**Comment by Alex-the-666** [comment]
fixed
