### ISSUE TITLE
[Suggestion] Improve Dino Model Creation

### ISSUE THREAD

**Issue by Mike-U5** [FossilsArcheologyRevival/FossilsArcheologyRevival#1287]
Currently, you get a random dinosaur model by right-clicking the ground with a fossil. This is a little weird.  
  
A way cooler way to handle this would be to make each model a separate craftable item. In order to craft them, you'd have to collect every dino bone of the species' model you want to craft.  

I do believe there were some plans to do this in the 1.7.10. version, but that never happened.

**Comment by TropicalYeti** [comment]
perhaps you just use one of the specific bones already implemented for the specific dinosaur.

**Comment by lindstheginj** [comment]
Will change when we do the Paleontology update.
https://fossils-archeology.fandom.com/wiki/User_blog:ASDFGirl/The_Future_of_Fossils_and_Archeology:_Revival
