### ISSUE TITLE
Gallimimus refuses to eat from a feeder after being ridden

### ISSUE THREAD

**Issue by MultiDavid2** [FossilsArcheologyRevival/FossilsArcheologyRevival#1290]
After I had ridden a gallimimus into a small pen with a parasaurolophus in it and a feeder, I left and came back an hour later with the gallimimus hungry and the parasaurolophus well fed, the feeder had about 5000 food on it so that was not the problem.
Edit: It does actually eat from a feeder after being ridden, just it doesn't eat plants, only meat.

**Comment by Alex-the-666** [comment]
#1512
