### ISSUE TITLE
Dryosaurus Dinopedia Entry Errors

### ISSUE THREAD

**Issue by joshwpike** [FossilsArcheologyRevival/FossilsArcheologyRevival#1294]
-missing space between "dryosaurus'" and "speed"
-"semi-arid" needs to be switched with "the"
-missing period at the end of the second paragraph
-not sure if it should be semiarid or semi-arid. I would opt for the dash.

**Comment by lindstheginj** [comment]
That’s weird. Looks like we missed this entry when updating them for the Mort. I’ll make sure to change it soon.
