### ISSUE TITLE
Palaeoraphe logs crash game.

### ISSUE THREAD

**Issue by Bantoo1231** [FossilsArcheologyRevival/FossilsArcheologyRevival#1309]
When ever I try to place down the logs my game crashes. The saplings seem to work fine but not the logs for some reason.
[crash-2019-04-09_19.31.40-client.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/3060443/crash-2019-04-09_19.31.40-client.txt)

**Comment by tyranno66** [comment]
Duplicate that has been fixed indev.
