### ISSUE TITLE
Deinonychus jumps into walls and suffocates

### ISSUE THREAD

**Issue by joshwpike** [FossilsArcheologyRevival/FossilsArcheologyRevival#1310]
Not sure if this happens with adults, but when baby deinonychus' interact with scratching posts or tethered logs they occasionally go flying and glitch into walls, suffocating.

**Comment by Canus8** [comment]
This happened to my first baby deinonychus, too.  it hatched, and instantly tried to climb a mossy cobble boulder, and wouldn't stop trying, and ultimately died.  I have also seen, in creative worlds, deinonychus adults doing this, too.  I think Velociraptor has a similar issue, but it is not as bad or frequent as it is for deinonychus.  They also can't kill anything when they try to.

**Comment by Alex-the-666** [comment]
#1513
