### ISSUE TITLE
Dinosaurs don't listen to "mob griefing" gamerule

### ISSUE THREAD

**Issue by Canus8** [FossilsArcheologyRevival/FossilsArcheologyRevival#1313]
The gamerule "mobGriefing" refers the ability for mobs (such as creepers, ghasts, endermen, the ender dragon, and the wither) to break blocks.  By default, it is set to "true", so when a creeper explodes, it takes a crater of the ground with it.  If set to "false", mobs, including the ender dragon, can't break blocks.  This would be an excellent back-up for a non-accessible "block breaking" config for the dinosaurs in the mod...except, the dinosaurs (and other creatures in the mod) don't listen to it.

I was trying to make a clone of my main survival world, and used spawn eggs to place my Allosaurus where they were in the original version of the world, and they immediately ran into the mountain and smashed a hole into it.  I quickly typed the command /gamerule_mobGriefing_false (_ replaced by space, of course), expecting it to stop them from destroying the glorious savanah hill, but the Allosaurus continued to drill, like a Whispering Death, into the mountain, even with mob griefing off.  I know that the mod doesn't have to follow the default minecraft commands, but at least in this case, while the config in the mod options page doesn't exist, I feel that they really, for the sake of the terrain, should listen to the mob griefing command.  And some of the species that curently break blocks (such as elasmotherium, Allosaurus, Stegosaurus, Therizinosaurus, Parasaurolophus, Megalodon, and Megalania) shouldn't be able to break blocks, as it seems a little OP for them.

Just some thoughts and observations...

**Comment by Canus8** [comment]
Kind of a follow-up recommendation, Why not re-insert the eye-height method of determining block breaking hat used to exist for brachiosaurus, but include other block-breakers under that system, as well.

**Comment by NightSky64** [comment]
You can disable block breaking in the config.

**Comment by Canus8** [comment]
What config?  This comes up when I try to find the configs.  I can't access the configs through .minecraft folder, either.
![Screenshot (515)](https://user-images.githubusercontent.com/49524173/55990627-23ead680-5c76-11e9-9b13-8e098bd0bc8e.png)

**Comment by Canus8** [comment]
![Screenshot (517)](https://user-images.githubusercontent.com/49524173/55990712-68767200-5c76-11e9-9300-7f4b61eb4e5d.png)

**Comment by lindstheginj** [comment]
Open the fossil.cfg with notepad.

**Comment by Canus8** [comment]
notepad?  I don't think I have notepad...  Does a dell inspiron 1500 series have that by default?

**Comment by lindstheginj** [comment]
Click "more apps" and it should be in the list.

**Comment by Canus8** [comment]
I found it.  Really inconvenient though.  I still, though, think that the dinosaurs should listen to mob griefing command.  That is still a bug.

**Comment by lindstheginj** [comment]
It isn't a bug if it's intentional. Marked as suggestion.

**Comment by Canus8** [comment]
Thank you for your help, by the way.

.    .
\__/

**Comment by Canus8** [comment]
Well, my elasmotherium, after I thought I had reset the config to no block breaking, proceeded to break blocks...

**Comment by lindstheginj** [comment]
Did you save the change?

**Comment by Canus8** [comment]
![Screenshot (520)](https://user-images.githubusercontent.com/49524173/55991483-5ac1ec00-5c78-11e9-87de-8b00ae110774.png)

**Comment by Canus8** [comment]
yes

**Comment by Canus8** [comment]
DO I have to close the notepad thing first?  I have it open to recheck, it still says block breaking false.

**Comment by Canus8** [comment]
Yeah, I closed it, and pushed him into the wall, and he still drilled into it.

**Comment by lindstheginj** [comment]
Did you save and close your world since you made the change? If not, it may not have registered the change.

**Comment by Canus8** [comment]
I actually, after first changing it and saving it, went to my creative mode copy, where I took the screenshot.  The one in the main world kept trying to get in my face while I was trying to take a picture.  do I have to completely restart Minecraft?

**Comment by lindstheginj** [comment]
I'd recommend it. Worth a shot.

**Comment by Canus8** [comment]
Oddly enough, I noticed that Brachiosaurus seem to actually try to AVOID breaking blocks, like they don't want to break them.  Kind of funny, actually.   And, restarting minecraft, not just re-opening the world, works.  Now, I can wait for the HTTYD mod to come out before I worry about holes in my world!

**Comment by Canus8** [comment]
and it saved my village and base, so thank you!

**Comment by lindstheginj** [comment]
No problem. For future reference, make sure to separate issues. "Mobs don't follow mob griefing false," "can't access config," and "mobs break blocks even if set to false" would be three different issues, even if they end up being user-error.

**Comment by Canus8** [comment]
Well, the problem started with one that was already brought up, that wasn't explained very well, so I tried to fix it the only way I could think of, which didn't work, and then the rest is just the progression of solving the original however possible, and the steps used in doing so.  The subject change mostly occurred through the development of details and problem solving.  It was originally supposed to just be about the commands.  Solving it took it to other places, but to avoid repeating topics, those places were kept here.  I struggle to explain, so I hope this makes sense and explains how the changes happened.
