### ISSUE TITLE
T rex doesn't look like T rex?

### ISSUE THREAD

**Issue by Canus8** [FossilsArcheologyRevival/FossilsArcheologyRevival#1314]
This is more a comment then an issue, but the current T rex model and skin looks a lot more like a Torvosaurus in shape than a T rex.  The are very small, their head is abnormally flat, and (although I, as a JP rex fan and creationist, don't mind this), they don't actually look feathered at all.  I have seen the videos of Poet Plays on youtube, and I remember the last update's rex looked good, even to me, and was confused by the rather bland and odd-looking new model.  I was wondering if there was a chance that the model could be changed back to the previous version.  I don't mind a Torvosaurus that thinks it's a T rex, but I do think that it would still be better if that Torvosaurus was actually a Torvosaurus, and not a T rex by code.

This is the 1.12.2 minecraft version of the mod.

**Comment by Canus8** [comment]
![Screenshot (509)](https://user-images.githubusercontent.com/49524173/55964750-40b9e680-5c43-11e9-80f7-4c242428fbb9.png)
![Screenshot (510)](https://user-images.githubusercontent.com/49524173/55964751-40b9e680-5c43-11e9-862d-222d7dfd90a1.png)
![Screenshot (511)](https://user-images.githubusercontent.com/49524173/55964752-40b9e680-5c43-11e9-8582-ae5ad9571e5d.png)

**Comment by NightSky64** [comment]
Real life trex was proven to be scaly. Dunno why the trex is too small, though.

**Comment by lindstheginj** [comment]
The issues tracker does not exist for feedback on art preferences.
