### ISSUE TITLE
Nautilus shouldn't close their shell around players in creative mode

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1316]

**Comment by Raptorofwar** [comment]
Why not?

**Comment by Adsper** [comment]
Because creepers don't explode in creative mode and carnivores won't try to hunt you in creative mode. It's inconsistent.

**Comment by NightSky64** [comment]
Or, for a better comparison, ocelots don't run away from you on creative.
