### ISSUE TITLE
Plesiosaurus probably needs rebalancing

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1317]
It does 12 damage (6 full hearts), so it can kill you in two hits.

My suggestion would be halving it, that way it can still kill fish pretty easily but it won't be a murder machine.

**Comment by NightSky64** [comment]
It also shouldn't attack players when hungry.

**Comment by PCAwesomeness** [comment]
TBH, Ichthyosaurus also needs rebalancing; I put an Ichthyosaurus and a Plesiosaurus together, and the Ichthyosaurus was able to kill the Plesiosaurus easily.

The most that I'd want is a damage reduction.
