### ISSUE TITLE
Crash when spawning Anu from egg, and Treasure dimension killing in creative

### ISSUE THREAD

**Issue by katubug** [FossilsArcheologyRevival/FossilsArcheologyRevival#1319]
Hi! I'm using Fossils and Archaeology in a relatively big pack (modlist: http://bit.ly/ECModlist) and encountered this error today when testing some things:

https://paste.dimdev.org/qucubipepi.mccrash

I spawned Anu in the overworld using an egg, and was immediately disconnected. I was able to reconnect and killed him (crazy fight btw, even in creative haha). I right button clicked his body to loot it, and it teleported me to the treasure dimension, where I was apparently stuck in a block or something, as it was pitch black and I was taking damage. Bizarrely, I was in creative, but it still killed me.

Thanks for your time!

**Comment by Canus8** [comment]
The only thing that can kill a player in creative mode is the Void, so it sounds like, when Anu is defeated in the overworld, the map of the treasure dimension does not load.  That stinks!  Maybe I will try it myself to verify, but definitely interesting.

**Comment by Canus8** [comment]
I didn't crash, But it definitely put me outside the room and into the void.

**Comment by Alex-the-666** [comment]
fixed
