### ISSUE TITLE
[Suggestion] future creatures

### ISSUE THREAD

**Issue by Canus8** [FossilsArcheologyRevival/FossilsArcheologyRevival#1321]
I would would like to suggest some creatures for the next update to the mod.  These creatures don't have to be added, and they don't have to be added in the same update as each other.  This is merely a suggestion list.

* indicates a creature that I would personally love to see added

1. * Diplodocus
2. Iguanodon
3. Ouranosaurus
4. * Styracosaurus
5. * Nasutoceratops
6. Protoceratops
7. * Nanotyrannus
8. Carcharodontosaurus
9. * Dakotaraptor (if added, I would like the males to have plumage resembling an Indian warbonnet)
10. Dimorphodon
11. * Acrocanthosaurus (JPOG colors would be nice, too)
12. Tsintaosaurus
13. Shunosaurus
14. Amargasaurus
15. Pyroraptor
16. Troodon
17. * Quinkana
18. Thylacosmilus
19. Edmontonia
20. * Carnotaurus
21. Utahraptor
22. Zuniceratops
23. Tenontosaurus
24. * Oxalaia
25. Basilosaurus
26. Levietan
27. * Kaprosuchus
28. Nigersaurus
29. Quetzelcoatlus (if added, allow them to be rideable and flyable, like the pterosaurs of old)
30. Hetzagopteryx (if added, allow them to be rideable and flyable, like the pterosaurs of old)
31. Ornithocheirus
32. Edmontosaurus
33. Maiasaura
34. trilobites
35. * Tusoteuthis (if added, please make it look like an actual squid and not a Minecraft "squid")
36. Torvosaurus
37 * Saurosuchus
38. * Postosuchus
39. * Smok (archosaur)
40. Herrarasaurus
41. Placerias
42. Notthosaurus
43. Tanystropheus
44. Giganotosaurus
45. Kentrosaurus
46. Cryolophosaurus
47. Moa
48. * Steppe Bison (or some kind of extinct bison)
49. * Cave Bear (or some kind of extinct bear)
50. * Haart's Eagle (or some similar kind of extinct bird of prey)

This list is just a suggestion, but I would like you to consider it.

**Comment by lindstheginj** [comment]
This is NOT a suggestion forum.

**Comment by Adsper** [comment]
Also, half of these are confirmed: https://fossils-archeology.fandom.com/wiki/User_blog:Adsper/All_Possible_Mobs
