### ISSUE TITLE
Sarcosuchus' right leg floats off its body when it's sleeping

### ISSUE THREAD

**Issue by PCAwesomeness** [FossilsArcheologyRevival/FossilsArcheologyRevival#1323]
![2019-04-14_16 24 01](https://user-images.githubusercontent.com/8507148/56099394-ea160c00-5ed1-11e9-94a3-9da5b39ac098.png)

**Comment by lindstheginj** [comment]
What, you mean your leg DOESN’T float off when you sleep?

**Comment by Alex-the-666** [comment]
i think i fixed this
