### ISSUE TITLE
Placed Biofossils usually delete blocks placed next to them

### ISSUE THREAD

**Issue by katubug** [FossilsArcheologyRevival/FossilsArcheologyRevival#1325]
I'm playing on fossilsarcheology-8.0.0, forge version 12.23.5.2825, and the placed Biofossil skeletons are deleting objects placed beside them, in all directions. Seems to happen with all the skeleton types except Plesiosaur.

I tested it in a fresh instance of MC with only F&AR and LLibrary installed.

**Comment by Alex-the-666** [comment]
fixed
