### ISSUE TITLE
Mammoth lag

### ISSUE THREAD

**Issue by Canus8** [FossilsArcheologyRevival/FossilsArcheologyRevival#1326]
I believe that there is an infinite loop glitch with mammoths which is causing them to create immense lag.  This kind of lag I have already experienced from Jurassicraft's Brachiosaurus and naturally-spawning dinosaurs, and in the latter it gets bad enough to cause crashes.  I didn't notice it until I was trying to mine directly under the mammoths, who appear to be suffering the same in-activity glitch my raptors are experiencing and which I have brought up in another issue.  However, the raptors didn't cause any lag from this.  When it occurred with the Jurassicraft Brachiosaurus, the only way I could stop it was by killing them (I chose by fire).

![Screenshot (530)](https://user-images.githubusercontent.com/49524173/56149593-e7232600-5f7a-11e9-8902-8f30b8cfe465.png)
![Screenshot (531)](https://user-images.githubusercontent.com/49524173/56149594-e7232600-5f7a-11e9-94d9-488df1854874.png)

**Comment by Canus8** [comment]
After removing the mammoths, my FPS jumped from about 3 to at least 60, so it was definitely them causing the lag.

**Comment by lindstheginj** [comment]
@Canus8 herd ai was tweaked in 8.0.1 - are you still experiencing this lag in the newest version?

**Comment by Alex-the-666** [comment]
#1512
