### ISSUE TITLE
Game crashed when opening ancient chest

### ISSUE THREAD

**Issue by VioletWyvern** [FossilsArcheologyRevival/FossilsArcheologyRevival#1327]
When I finally defeated Anu, I teleported to the treasure room normally, But when I opening the ancient chest with ancient key, My game crashed, After tried several times, ant this still happened...

I'm make sure I'm installed the newest Forge, But this issue still happened...

**Comment by xGarionx** [comment]
Can confirm same issue (can provide log if needed) , there seems to be some incompability with BoP & Natura aswell, i suppose the used Hell biome ID causes it and spawns vines and Bloodwood trees (when not blacklisted) in the lair dimension .

**Comment by kreezxil** [comment]
Ok, I have this issue too, but I disabled the hellboats because it was happening far too much. I have more time on my hands now. I'll re-enabled the hellboats and I should have a ton of a good reports to add to this.

**Comment by Draconian4466** [comment]
some more reports of this here #1083

**Comment by kreezxil** [comment]
You see that's why I had the hell boats deactivated.

**Comment by GatoLeyo** [comment]
https://pastebin.com/3j3PbbTC
