### ISSUE TITLE
Trouble downloading the mod

### ISSUE THREAD

**Issue by edgyspork** [FossilsArcheologyRevival/FossilsArcheologyRevival#1328]
dunno if it's just because i'm new and doing something wrong, but the mod isn't showing up in my minecraft mod list. done everything right and followed the forge tutorial all the way up to chucking the mod file and the llibrary file into the mods folder, but i open minecraft and only the minecraft, minecraft coder pack, forge mod loader, minecraft forge and llibrary 'mods' show up in the mod list, nothing else. put in the newest llibrary update (says llibrary 1,7,17-1.12.2), and the newest mod file (fossilsarcheology 7.3.2). random folder came up in the mods file called memory_repo, don't know what that is or means. if anyone could help be that'd be very much appreciated, i absolutely adore this mod with all my heart and it'd make me so happy to be able to finally get it :'))

**Comment by NightSky64** [comment]
That's because you need the 8.0.0 version of the mod
