### ISSUE TITLE
Inconsistent meat names

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1330]
Tiny issue: vast majority of the meats in the mod are named along the lines of "x Meat" and "Cooked x Meat".

For dryosaurus, therizino, parasaur, heno, and ichthyo, it's "Raw x" or "Cooked x", without the 'meat'.

**Comment by NightSky64** [comment]
This was already resolved: https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/c45dad4a44c5ffb6bc8075d325fc479a587e0cb2

**Comment by Adsper** [comment]
What that guy said
