### ISSUE TITLE
There are two project names that do not appear correctly.

### ISSUE THREAD

**Issue by qq512065439** [FossilsArcheologyRevival/FossilsArcheologyRevival#1335]
> jurassicraft\lang\en_us.lang
> tile.cultivate.name={color} Cultivator
> fossil\lang\en_us.lang
> tile.cultivate.name=Culture Vat

> fossil\lang\en_us.lang
> item.shell.name=Nautilus Shell
> flansmod\lang\en_us.lang
> item.shell.name=AP Tank Shell

It seem because use the same ID with other MOD

**Comment by Alex-the-666** [comment]
#1499
