### ISSUE TITLE
items/dinos not appearing help?

### ISSUE THREAD

**Issue by GaleTheGalli** [FossilsArcheologyRevival/FossilsArcheologyRevival#1346]
so i just downloaded the mod and started a server for it. everything went well until we tested items and they did not appear and the dino eggs didnt appear either aswell as fossil ore not spawning in the world. im using minecraft version 12.2 with library 1.7.17 anybody knwo what to do?

**Comment by lindstheginj** [comment]
@GaleTheGalli did you ever figure it out? from what i've heard, it seems like the mod wasn't installed on the server end.
