### ISSUE TITLE
Disabling dinoBlockBreak causes dinos to permanently sleep. 

### ISSUE THREAD

**Issue by KangaliaV** [FossilsArcheologyRevival/FossilsArcheologyRevival#1347]
Hi,

Whenever I disable the 'dinoBlockBreak' option in the fossils config, any dinosaurs on my server suddenly sleep and never wake up. For example, if I spawn in a Compsognathus, it will instantaneously go to sleep, even if I spawn it at night. The only dinosaurs that don't seem to be effected are those that are cathemernal. This nearly always results in the dinosaurs starving to death if I can't feed them in time. I have checked to ensure that it wasn't just the spawn eggs and found this issue to occur whenever I spawn the dinosaurs by hatching them or through the spawn egg. I have also tried it on multiple worlds on my server and the same thing happens. The only thing that fixes it is enabling 'dinoBlockBreak'. 

Many thanks,

-Kang

**Comment by Alex-the-666** [comment]
fixed, config mem leak issue
