### ISSUE TITLE
Dinosaurs starving while surrounded by food/feeders

### ISSUE THREAD

**Issue by Monshinix** [FossilsArcheologyRevival/FossilsArcheologyRevival#1349]
Dinosaur independent feeding does not appear to be working correctly, all of my dinosaurs seem to prefer starving to eating and herbivores will not eat grass or ferns without being handfed. I only observe/hear eating when I lead a dino directly to a feeder and then place new food in it (which leads to frenzied feeding as if all nearby dinos suddenly remembered how to eat) but then they will continue not eating until they starve or I "remind" them again.
I have had to turn dino starving off because of this, I see several other similar threads have been closed as "solved" but I am still experiencing the issue. I am playing the latest version with no other mods.
Thanks

**Comment by lindstheginj** [comment]
The reason they’d be closed as solved is because they are fixed for the next update.

**Comment by Alex-the-666** [comment]
should be fixed
