### ISSUE TITLE
Crashing on Startup (Custom Modpack)

### ISSUE THREAD

**Issue by Explode007** [FossilsArcheologyRevival/FossilsArcheologyRevival#1350]
Usually I Can solve these on my own but i have no clue whats happening
[crash-2019-05-17_15.39.25-client.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/3192879/crash-2019-05-17_15.39.25-client.txt)

**Comment by Alex-the-666** [comment]
crash with betweenlands. will be fixed in 8.0.1

**Comment by Explode007** [comment]
But like in the beggining of developing the pack i had both mods present and it was fine, only now is it causing issues
