### ISSUE TITLE
Disabling Nautilus via config does not prevent them from spawning.

### ISSUE THREAD

**Issue by katubug** [FossilsArcheologyRevival/FossilsArcheologyRevival#1352]
Just what the title says. In the config, I have spawn-nautilus set to "false" (I love them but they horrendously overspawn), but they're still spawning in my world.

Versions: 
fossilsarcheology-8.0.0
llibrary-1.7.19-1.12.2
forge-1.12.2-14.23.5.2838-universal

**Comment by Alex-the-666** [comment]
fixed in 8.0.1 i believe
