### ISSUE TITLE
Mushrooms cannot be used as cultivator fuel

### ISSUE THREAD

**Issue by CactusKingIII** [FossilsArcheologyRevival/FossilsArcheologyRevival#1354]
Afaik the only condition for fuels is that it’s a protein so mushrooms should count

**Comment by Sunconure11** [comment]
I can implement this. I was fixing textures, let me make sure they are working right in a workspace now.

**Comment by Sunconure11** [comment]
Looking at it now, this would require more code changes to it. It is not set up to take blocks as fuel.
