### ISSUE TITLE
Tiktaalik is surprisingly nasty for such a relatively small fish

### ISSUE THREAD

**Issue by PCAwesomeness** [FossilsArcheologyRevival/FossilsArcheologyRevival#1356]
![2019-06-07_16 33 04](https://user-images.githubusercontent.com/8507148/59135082-41b97c80-8943-11e9-964d-2246c132ed0c.png)

To confirm the DinoPedia info, it attacks you on sight, too.

**Comment by lindstheginj** [comment]
I don't mind the aggression, but maybe a less strong attack is in order.

**Comment by PCAwesomeness** [comment]
@lindstheginj 

Can it at least be territorial?
