### ISSUE TITLE
Meganeura cannot damage other mobs

### ISSUE THREAD

**Issue by PCAwesomeness** [FossilsArcheologyRevival/FossilsArcheologyRevival#1359]
![2019-06-07_17 58 16](https://user-images.githubusercontent.com/8507148/59137536-eb057000-894d-11e9-9032-e36447bc752f.png)

It is struggling to attack this Confuciusornis, as it can't deal any damage to it.

This also happens with other small mobs that happen to be prey for Meganeura.

**Comment by Alex-the-666** [comment]
fixed
