### ISSUE TITLE
Analyzer not working

### ISSUE THREAD

**Issue by Ceetron** [FossilsArcheologyRevival/FossilsArcheologyRevival#1360]
The analyzer, for the most part, does not analyze items and if it does its very sporadic in its frequency,

**Comment by Ceetron** [comment]
From testing it seems to appear that when analyzing biofossils It will full the bar, but not do anything. Once it fills the bar it will reset like it did analyze the bio fossil. But from testing it seems that the biofossil will repeat this until it finally is analyzed into DNA, which then it will register and you will lose a biofossil.

**Comment by Dinosnoring** [comment]
I get two DNA from meat and dino bones then the analyzer starts to eat what is going in, while producing no more than 2 dna. Frozen meat seems to work alright. Regular fossils, relic scraps, and plants seem to work for the most part with a low turnover. Tar fossil and drops are so low I would say they don't work at all.
For the relic scraps, fossils, and plants it seems like there is a decay. They work for a short while then stop all together.

**Comment by sa13103** [comment]
so i was experiencing the same issue, where the analyzer was not doing anything with the tar drops. i noticed something odd when i was looking up what the yield was for them, all the recipes are blank, like they are all there but they show no item as a yield . to solve this issue i just reinstalled the mod and its working properly again.
