### ISSUE TITLE
Dig sites now spawn underwater

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#1373]
Also reports of them spawning in trees still

**Comment by nephatrine** [comment]
Yeah I've been seeing them at the bottom of deep ocean biomes even.

**Comment by DevilKitten** [comment]
I can attest to this as well, with a few screenshots. There was 3 of them all in close proximity of each other.
![2019-06-09_09 22 08](https://user-images.githubusercontent.com/31811686/59160160-d1bd0a80-8a98-11e9-808c-a48f2009e775.png)
![2019-06-09_09 21 52](https://user-images.githubusercontent.com/31811686/59160162-d681be80-8a98-11e9-972b-3c0c6c38d1fa.png)

**Comment by BrisingrAerowing** [comment]
This seems to be happening again in 8.0.4.

![2020-05-15_14 43 38](https://user-images.githubusercontent.com/250409/82085953-c4060100-96bb-11ea-9cd7-5c778603907d.png)

I placed the dirt so the villager could get into the tent.
