### ISSUE TITLE
Tar Slime Bug

### ISSUE THREAD

**Issue by DunalN2** [FossilsArcheologyRevival/FossilsArcheologyRevival#1376]
I've noticed tar slimes occasionally spawn and immediately despawn while in Peaceful Mode. Normally this wouldn't bother me, but they also briefly attack and cause blindness while I'm harvesting tar drops, and the blindness popup appears to the side and never goes away until death, preventing sprinting. Is this perhaps a bug for Minecraft itself, or a F/A bug?? I'm not entirely sure, but the infinite blindness thing should be taken care of.

**Comment by darthvader45** [comment]
Using version 8.0.3, and have the same issue with the Blindness debuff popup still there, and never goes away.  Thus, I am stuck with no sprinting until I die.  What the heck?
