### ISSUE TITLE
NOSUCHMETHODError

### ISSUE THREAD

**Issue by kreezxil** [FossilsArcheologyRevival/FossilsArcheologyRevival#1383]
8.0.1 crashes dedicated server Forge 1.12.2 build 2838

Notes:
     on startup

crash report:
http://paste.ubuntu.com/p/m633dRzjRH/

fml server latest:
http://paste.ubuntu.com/p/SmS3qqgpd3/

**Comment by 4f6f3b** [comment]
Duplicate #1358
