### ISSUE TITLE
Doesn't work on my server

### ISSUE THREAD

**Issue by VBenedekN** [FossilsArcheologyRevival/FossilsArcheologyRevival#1386]
I made a server with the mod and it crashes. When I remove the mod the server is working without any crash.

Version of the mod: 8.0.1

**Comment by ArkenorOakshadow** [comment]
An issue for this bug is already open. https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1358

**Comment by lindstheginj** [comment]
Duplicate of #1358
