### ISSUE TITLE
Foozia renamed paleopanax

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#1389]
Foozia should be its own plant still and paleopanax should be added as a separate plant.

**Comment by Alex-the-666** [comment]
![image](https://user-images.githubusercontent.com/8662109/59396071-93646b80-8d76-11e9-8496-8d228a0af629.png)

**Comment by lindstheginj** [comment]
I double checked all of our messages and don't see a mention of Palaeopanax anywhere, so I figured this was a mistake? I can't recall renaming Foozia ever coming up

**Comment by Alex-the-666** [comment]
fixed
