### ISSUE TITLE
Dino block breaking false does not prevent block breaking

### ISSUE THREAD

**Issue by isagamingn3rd** [FossilsArcheologyRevival/FossilsArcheologyRevival#1394]
hello i am here to report a bug why does the sarco still break blocks after i said dino block breaking false

**Comment by lindstheginj** [comment]
If you are using 8.0.1, are you using the fossils.cfg file or the in-game config?

**Comment by lindstheginj** [comment]
Also for future reference, please make the title of your issue state the specific bug.

**Comment by Alex-the-666** [comment]
dupe #1539
