### ISSUE TITLE
Raptors constantly climb without end and can get stuck

### ISSUE THREAD

**Issue by Bastion14** [FossilsArcheologyRevival/FossilsArcheologyRevival#1400]
Raptors will start climbing a short surface with something blocking the top. For me, they will reach the top and constantly climb. Sometimes I will have to hit them to stop but they will either return to climbing, sleep, or feed themselves and climb. They aren't supposed to be kept in small enclosures but some sort of limit to block climbing or will give up after being stuck on the top would be nice. They will sometimes keep doing this and ignore any needs.

**Comment by Alex-the-666** [comment]
dupe #1513
