### ISSUE TITLE
Henodus should have the same AI as tiktaalik

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1406]
Involved #1301

**Comment by lindstheginj** [comment]
Uh, why?

**Comment by BlueWither** [comment]
Because its AI is very buggy.
It stops moving, and not to go on feeder.

**Comment by lindstheginj** [comment]
Well considering that Henodus should not go on land, but Tiktaalik can, it’s probably a better idea to fix Henodus’ AI instead of copying.

**Comment by BlueWither** [comment]
OK, I see.
