### ISSUE TITLE
Baby Plesiosaurus is proportionally too big

### ISSUE THREAD

**Issue by NightSky64** [FossilsArcheologyRevival/FossilsArcheologyRevival#1412]
Would a plesio be capable of giving birth to something this big? Plus all the other baby mobs are a lot smaller.
![2019-06-20_22 04 20](https://user-images.githubusercontent.com/47564922/59878395-7815e380-93a8-11e9-913a-005a8c5321e4.png)

**Comment by CactusKingIII** [comment]
Yes because fossil evidence shows that baby Plesiosaurs were at this scale with their mother.
