### ISSUE TITLE
Bouncing aquatic creatures

### ISSUE THREAD

**Issue by Vyeriss** [FossilsArcheologyRevival/FossilsArcheologyRevival#1413]
I'm using vers. 8.0.1
I've spawned an Ichthyosaurus, meganeura, and a henodus, and all of them have the same issues. All of them bounce on the top of the water and won't go past the surface, and this has caused my ichthyosaurus to 'fall from a high place' every time I sleep in my bed. The first time this happened my ich had died, but now I just keep getting the message and seeing him still alive the next day. My meganeura grew up fully and phased through the glowstone I keep on top of the enclosure; It is still bouncing despite being a flying mob.

**Comment by lindstheginj** [comment]
Is this problem still occurring in 8.0.2, and if so, are you by chance playing with Lucraft core?

**Comment by Vyeriss** [comment]
Hi, I upgraded to 8.0.2 and still had the issue. However, I uninstalled
Lucraft Core and the issue stopped, but now all of my dinosaurs are showing
as pregnant.

**Comment by TropicalYeti** [comment]
known problem, just so you know

**Comment by Alex-the-666** [comment]
dupe #1226
