### ISSUE TITLE
Dinopedia will no longer work on vanilla animals pregnant with prehistoric embryos.

### ISSUE THREAD

**Issue by KangaliaV** [FossilsArcheologyRevival/FossilsArcheologyRevival#1416]
Hi,

When trying to use the Dinopedia on a pregnant vanilla animal, right clicking results with no action whatsoever. This means I cannot check the progress of the pregnancy anymore. I have tested this with all of the prehistoric embryos and all available vanilla animals and this issue is consistent throughout. I have tested this on both 8.0.0 and 8.0.1 and this problem is wit both versions. The older 1.7.10 version works normally.

Many thanks,

Kang

**Comment by lindstheginj** [comment]
Do you have any other mods installed? I have not encountered this when playing with just F/A and Llib.

**Comment by KangaliaV** [comment]
I do have a large amount of other mods installed. I wasn't aware they could interfere with things like this. I will do some tests to see which mod is causing it.
