### ISSUE TITLE
Anu Dimension and Biomes O' plenty conflict

### ISSUE THREAD

**Issue by glintshark** [FossilsArcheologyRevival/FossilsArcheologyRevival#1417]
When using the Lair portal to transport to the Anu dimension, a biomes o plenty biome may be located in the same position as the castle, leading to some problems such as spawning in midair and spawning inside blocks that you cannot break due to the "kill anubis to break blocks" restriction

**Comment by katubug** [comment]
One of my players has also had this issue. I was not sure what has caused it, but twice now my players have reported falling into the void upon spawn or spawning inside blocks they couldn't escape.
