### ISSUE TITLE
The dinopedia thinks all mobs are pregnant...

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1418]
![2019-07-04_19 56 01](https://user-images.githubusercontent.com/11862143/60695197-c1306200-9e95-11e9-94af-18796f21803a.png)

Tested with a bunch of others. ~~Can we beta test for the next build~~

**Comment by BlueWither** [comment]
I have a same problem...

**Comment by KangaliaV** [comment]
I am also having this issue. I've checked and it's with all of the mobs, not just the new ones.

**Comment by qq512065439** [comment]
same too

**Comment by snazziboy10** [comment]
So basically the Dinopedia is broken. It is a very important art of the mod and should be fixed as soon as possible. Also, is anyone not having this problem?

**Comment by GarchompGirl** [comment]
only fix is jumping back to the fossils update where it added megalania megalodon etc

**Comment by lindstheginj** [comment]
I wouldn't say the "fix" is to use other bugged updates. Just wait for 8.0.3.

**Comment by GarchompGirl** [comment]
well ok then =P even though im impatient

**Comment by MadridCastillo** [comment]
No saben si existe una solución?

**Comment by FlamersKilho** [comment]
Having the same issue. Any possible fixes? Best of luck to the devs!

**Comment by Alex-the-666** [comment]
fixed
