### ISSUE TITLE
Some aquatics not suffocating on land

### ISSUE THREAD

**Issue by Ponytaco** [FossilsArcheologyRevival/FossilsArcheologyRevival#1421]
Every update I spawn every single creature in from the mod, just like all the past ones I did it this time. But I noticed something, Plesiosaurus, Ichthyosaurus, Mosasaurus, Liopleurodon, and (possibly*) Nautilus. Now that I'm searching these creatures up it seems like only Mosa and Lio are supposed to suffocate but I'll include the others just in case. *The possibly because It's always in its shell on land and I'm not sure whether that would do anything. Thanks for reading this waste of time and if I actually helped, that's pretty cool.

**Comment by NightSky64** [comment]
They don't suffocate because they're reptiles. But yeah, they should still get damage as they weren't built for surviving on land. As for nautilus, I think it's because it hides inside its shell.
