### ISSUE TITLE
The calamites slab doesn't have a recipe

### ISSUE THREAD

**Issue by alfieboris** [FossilsArcheologyRevival/FossilsArcheologyRevival#1422]

**Comment by Angery-Balaur** [comment]
This a larger problem for us to work around in Minecraft 1.12. You see, in vanilla 1.12, there were only "Wooden" and "Iron" trapdoors, and making a trapdoor out of any wood made the same trapdoor with the same oak texture. This mod adds new trapdoors for it's wood, but this version of Minecraft doesn't have a way of realizing that, and defaults to "Wooden trapdoors". I think that a port to 1.14 (The next version with a working Forge) will be quite a ways away, so I think that the coders should make a route from modded wood to modded wooden trapdoors on their own in the immediate future (Theoretically, you could add all the vanilla wood trapdoor variants at the same time, but I think that would be very unnecessary)

**Comment by Angery-Balaur** [comment]
Actually, Quark seems to have added trapdoors for all the wood variants of vanilla 1.12. Maybe one could learn from them (I have no idea how that stuff works though so)

**Comment by alfieboris** [comment]
I meant plank slab not trapdoor
