### ISSUE TITLE
Flowerpots.

### ISSUE THREAD

**Issue by Angery-Balaur** [FossilsArcheologyRevival/FossilsArcheologyRevival#1426]
We should be able to put prehistoric plants in flowerpots. To my knowledge, none of the current mod plants can be put in a flower pot. But we really should be able to do this with most of them, as in vanilla you can put in a flowerpot anything from flowers to mushrooms to saplings to cacti.
I suggest that these plants should be able to be placed in flowerpots: Paleoraphe and Calamites saplings, Cephalotaxus, Dillhoffia, Ephedra, Florissantia, short Horsetails, Archaeosigillaria, Vaccinium, Welwitschia, Zamites, and a smaller representation of the Ancient Ferns (like how cacti in pots get so teeny). I think that this is a good selection of the plants that would fit in a flowerpot (vanilla 2 block high flowers can't go in flowerpots). Stretch idea: a glass variant, which would must fill with water, letting you place the future aquatic plants inside them. But maybe that last on is a bad idea. I know the first is, by comparison, and awesome idea though.

**Comment by Alex-the-666** [comment]
no
