### ISSUE TITLE
Dinopedia does not let me see if my dinos are tamed or what food should i give them

### ISSUE THREAD

**Issue by MinyGoji** [FossilsArcheologyRevival/FossilsArcheologyRevival#1427]
i am in single player and for some reason when i use my dino pedia to see if my dinos need food or not,it appears nothing,i can see if its tamed,i cant see what food it needs or what item it needs to follow the rules (like sitting,wandering and following)

**Comment by lindstheginj** [comment]
Does it say they’re pregnant at 0%?

**Comment by Alex-the-666** [comment]
fixed
