### ISSUE TITLE
Calamites Sapplings vanish upon growth.

### ISSUE THREAD

**Issue by Bantoo1231** [FossilsArcheologyRevival/FossilsArcheologyRevival#1429]
Calamites sapplings which are obtained in survival vanish when they're meant to grow into the full tree. This happens when they grow naturally and when bone mealed. When a sappling from creative mode is used, however, the tree seems to work fine.

**Comment by Angery-Balaur** [comment]
This is an odd one. On a multiplayer server, I was in survival mode and growing Calamites just fine.
Maybe I should test it myself, although this could be a mod conflict

**Comment by lindstheginj** [comment]
What mods are you using, bantoo?

**Comment by Bantoo1231** [comment]
A bit of a List, I'm useing the Paleocraft modpack... https://www.curseforge.com/minecraft/modpacks/paleocraft/files/all

**Comment by Angery-Balaur** [comment]
Yeah, I just tested it. I can grow them fine (I don't have any world-changing mods, just stuff like Journeymaps and Dynamic Surroundings)

**Comment by Bantoo1231** [comment]
It's weird then because I can grown them on the server, but only when the sappling has been gotten out of the creative tab

**Comment by Angery-Balaur** [comment]
Oh I didn't test the obtaining part of it.

**Comment by damonbig** [comment]
So i was talking to one of your workmates on twitter and they told me to write down my issue here.

So I'm building a skypark (141blocks high) and i built my first enclosure and tried to plant and bonemeal a calamites sappling and it dissappear then tried by letting it grow naturally with no bonemeal same result. 

So i tried it at different levels, below 120blocks they will grow normally above that height they dissappear, so if you could, can you look into this bug and hopefully get it resolved.

(Also all types of saplings in the mod did this the other mod sapling and stock saplings grew normally)

Sincerely,
damonbig
