### ISSUE TITLE
Certain mobs won't tame upon hatching.

### ISSUE THREAD

**Issue by dragondrawsdragons** [FossilsArcheologyRevival/FossilsArcheologyRevival#1440]
A certain set of mobs won't tame when they hatch when they usually should, and have to be hand fed/whipped to tame. Despite current bug with the encyclopedia I can tell when they are and aren't tamed thanks to the minimap. This has been happening in both survival and creative, and in every world I've been in (which I should add, have all been created AFTER the recent update)
Did some testing, the mobs that I can currently tell that are affected by this are:
-pteranodon
-velociraptor
-gallimimus
-dryosaurus
-compsagnathus

EDIT: I get the feeling this would explain the recent issue added about dryosaurus attacking. I play in peaceful so I don't know if these mobs will also be aggressive too.

**Comment by alfieboris** [comment]
Yeah I've built an enclosure for dryosaurus and when I tried to order them to sit they didn't do it. And after some time the female became aggresive towards me.

**Comment by Alex-the-666** [comment]
THOSE GUYS NEED TO BE TAMED BY FEEDING THEM.

**Comment by Alex-the-666** [comment]
sorry capslock
