### ISSUE TITLE
Bubble blower can work outside water

### ISSUE THREAD

**Issue by an0nimu5** [FossilsArcheologyRevival/FossilsArcheologyRevival#1441]
![2019-07-14_10 41 06](https://user-images.githubusercontent.com/49610831/61185925-2129c400-a65f-11e9-96d9-11cd7cdc7abd.png)

**Comment by Angery-Balaur** [comment]
And this is a problem why? No harm in blowing bubbles above ground (texture could get changed above ground tho)

**Comment by an0nimu5** [comment]
I'm not sure it's intentional or not but I think it's not very possible to get bubbles using water turbine outside water xd
+ you can create bubbles with /particle command for same or better effect :)

**Comment by lindstheginj** [comment]
https://images-na.ssl-images-amazon.com/images/I/713xsbiXujL._SX425_.jpg
Seems like it would work the same as this
