### ISSUE TITLE
Pathing still bugged for some mobs (mostly larger ones)

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1445]
The smaller mobs seem to be alright for the most part in my experience and some of the bigger mobs like tyrannosaurus too, but for others, not so much.

Video example: https://www.youtube.com/watch?v=RqH5NXyjgUI&feature=youtu.be

**Comment by Adsper** [comment]
Also disregard what I said about the tyranno having fixed pathing, they're screwed up too

**Comment by alfieboris** [comment]
This is happening also to platybelodon.

**Comment by Alex-the-666** [comment]
fixed
