### ISSUE TITLE
[Suggestion] DNA on banners 

### ISSUE THREAD

**Issue by alfieboris** [FossilsArcheologyRevival/FossilsArcheologyRevival#1448]

**Comment by lindstheginj** [comment]
What does this even mean

**Comment by NightSky64** [comment]
Maybe they want animal icons from their respective dna item as a banner pattern.

**Comment by alfieboris** [comment]
Yeah I meant DNA pattern on the banner for every creature

**Comment by Alex-the-666** [comment]
yeah no thats incredibly time consuming.
