### ISSUE TITLE
Raptor hunting ai still semi-broken

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1453]
Raptors don't pounce enough when they actually want to hunt. It seems that specifically velociraptors are much more screwed on this than deinonychus', I haven't seen a velo successfully kill something once this update.

Video of deino for example: https://www.youtube.com/watch?v=dP3sDrSxI2s&feature=youtu.be

It takes the raptor ten seconds to kill a cow. ~~Honestly why are special attacks even still a thing they don't work half the time~~

**Comment by Alex-the-666** [comment]
#1513
