### ISSUE TITLE
Mammoths still doing their circling of death

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#1454]
Can we please kill the herd ai

For what its worth, this doesn't seem to be too big a problem for gallimimus anymore, it still happens occasionally but their herds are able to move around, while mammoths will simply circle in one spot forever.

Video example: https://www.youtube.com/watch?v=1YSu1nGxfAg&feature=youtu.be

**Comment by Alex-the-666** [comment]
#1512
