### ISSUE TITLE
Semi-aquatics (Spino, Sarco, Tiktaalik) keeps in underwater mode and can't move when landing

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1468]
I think it is as same as #1384 
When it go up from water, or land to water, they always stop between land and water, then never move.
On this form, it makes voices as if it were in the water.

**Comment by BlueWither** [comment]
It happened on sarcos too.

**Comment by BlueWither** [comment]
![2019-07-21_15 03 59](https://user-images.githubusercontent.com/34153394/63942156-18267200-caa8-11e9-9cab-46dfc3feea4a.png)
Thus, when it is stopped, it is between water and land.
Because it does not move, makes underwater sounds, and does not sleep, this is considered to be like being underwater on land.
In 8.0.0, this bug did not occur.

**Comment by BlueWither** [comment]
This is my expectation, but I think it is because the aquatic mobs stopped moving on land in 8.0.2.
-Fixed fully aquatic mobs moving on ground
Semi-aquatic mobs are treated the same as aquatic mobs only in the water, and the judgment that they are underwater does not disappear when they enter the land.

**Comment by BlueWither** [comment]
When I pushed or attacked these mobs, they began to move again.
But they stopped again when going into water.

**Comment by Alex-the-666** [comment]
fixed
