### ISSUE TITLE
Dryosaurus breeding without other mate

### ISSUE THREAD

**Issue by LoganCreeper50** [FossilsArcheologyRevival/FossilsArcheologyRevival#1478]
My friend and I started a dino world together. We decided to put our dryosaurus on an island, only one. While we were working around our house we saw a message in chat. The message said, "A prehistoric egg has hatched." or something like that. We didn't know what it was and just thought it was a bug. Then my friend found the baby dryo. I checked the wiki and it said that there needs to be a male and a female dryo present for them to have children, soon our island was overrun by Dryos. I just want to know if this was normal or not.

**Comment by Lycaon3214** [comment]
I've had the same problem(the gestation period thing not the laying eggs) but with every creature that can breed so i think that this is a bug that can possibly destroy your world

**Comment by TropicalYeti** [comment]
just turn breeding off.

**Comment by Lycaon3214** [comment]
Ok. thank you

**Comment by Lycaon3214** [comment]
So I turned off breeding and checked the dinopedia but it still shows:
Pregnant (dinosaur) 
Embryo Progress: 0%

**Comment by lindstheginj** [comment]
@Lycaon3214 that’s a separate issue. #1418.
