### ISSUE TITLE
Dinopedia txt files missing?

### ISSUE THREAD

**Issue by FurdenFuhrer** [FossilsArcheologyRevival/FossilsArcheologyRevival#1479]
So uh, when I use my Dinopedia on any dino when I go to the next page it just says "dinopedia/en_ca/stegosaurus.txt File not Found."

**Comment by lindstheginj** [comment]
Which mod version are you using?

**Comment by FurdenFuhrer** [comment]
fossilsarcheology-8.0.2.jar

**Comment by BlueWither** [comment]
I have the same problem

**Comment by Alex-the-666** [comment]
#1541
