### ISSUE TITLE
Archeology Workbench eats vanilla magic

### ISSUE THREAD

**Issue by Gift-of-Names** [FossilsArcheologyRevival/FossilsArcheologyRevival#1480]
Repairing an enchanted scarab tool using a relic scrap in the Archeology workbench results in an unenchanted scarab tool.

**Comment by TropicalYeti** [comment]
Thats normal, all default tools do that

**Comment by tyranno66** [comment]
Intentional, if you want to keep the enchants repair it with a scarab gem in an anvil.
