### ISSUE TITLE
Sarco don't do death roll(one hit attack) in water

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1481]
Of course it shouldn't do out of the water

**Comment by Adsper** [comment]
This was intentionally removed because it was inaccurate.

Just hope that a crocodile that doesn't suck gets added at some point.

**Comment by CactusKingIII** [comment]
.....and then people discovered that all known crocodilians are capable of it.

**Comment by Adsper** [comment]
Is that a dig on that sarcosuchus isn't a real crocodile or does that mean the death roll was actually removed for no reason?

**Comment by NightSky64** [comment]
Last time i heard, real sarcosuchus was incapable of death rolls

**Comment by BlueWither** [comment]
Oh I see

**Comment by CactusKingIII** [comment]
Last you heard is outdated and unnecessary to an already resolved issue
