### ISSUE TITLE
Duisbergia has the name of item.fossilseed_duisbergia.name

### ISSUE THREAD

**Issue by Ryanisstillthesame** [FossilsArcheologyRevival/FossilsArcheologyRevival#1482]

**Comment by lindstheginj** [comment]
Which mod version are you using

**Comment by Angery-Balaur** [comment]
I have actually experienced this problem before as well (I'm so forgetful I hate myself). In version 8.0.2 the fossilized seeds of Duisbergia have a file name like that, instead of a normal name. Can't remember if it was the case for the unfossilized seeds, tho

**Comment by Gift-of-Names** [comment]
Can confirm this is the case with fossilized seeds as well.
