### ISSUE TITLE
Dino Pedia = Broken

### ISSUE THREAD

**Issue by CougarTC** [FossilsArcheologyRevival/FossilsArcheologyRevival#1484]
all it says is embryo progress and no other info even though it was the only Dino in the pen is is 2 seconds old.
![2019-08-01_17 59 30](https://user-images.githubusercontent.com/53557936/62276873-4f453b80-b488-11e9-9f1b-ab250429945d.png)
![2019-08-01_18 02 38](https://user-images.githubusercontent.com/53557936/62276880-5409ef80-b488-11e9-8386-7c6af9dad441.png)

**Comment by TropicalYeti** [comment]
Known Bug.  Already has been reported like eight times

**Comment by lindstheginj** [comment]
Duplication of #1418.

**Comment by CougarTC** [comment]
when will it be fixed ?

**Comment by BlueWither** [comment]
It will be fixed. F/A teams won't show the time of update.

**Comment by Angery-Balaur** [comment]
Considering this is such a serious bug, yes it is a big priority. I think the plan is to fix it in the next update (8.0.3). You have to be patient though, no one ever really knows when the update will be done until... it's done. (_But I would also very much like them to do some dedicated beta-testing on 8.0.3 before they release it_)

**Comment by lindstheginj** [comment]
Jokes on you because we did beta test and the Dinopedia worked fine.

**Comment by Angery-Balaur** [comment]
Aha! So somebody released the wrong build, or the beta test came before the addition of the variable pregnancies that probably had something to do with the bug (Maybe)

**Comment by Angery-Balaur** [comment]
Anyway XP rewards for 8.0.3 pls?

**Comment by lindstheginj** [comment]
This is NOT a chat room. Keep conversation to a minimum and don’t carry over issues into others unless necessary.
