### ISSUE TITLE
Tethered Log making mobs dle

### ISSUE THREAD

**Issue by geeman152** [FossilsArcheologyRevival/FossilsArcheologyRevival#1485]
I noticed that whenever I put a tethered log in my Dino's pen they would idle in the same spot opening and closing there mouth, I kinda noticed it with the ball too but it seemed to only happen to 1 of the mobs, and it stopped when i removed it, noticed it on a terror birds and dryosaurus, probably happens to other mobs too tho.

**Comment by Alex-the-666** [comment]
dupe #1511
