### ISSUE TITLE
Dinopedia not working

### ISSUE THREAD

**Issue by SwissNinja** [FossilsArcheologyRevival/FossilsArcheologyRevival#1488]
We never use my dinopedia it says the dinosaur is pregnant at 0% even on the babies that just hatched. Any ideas on what to do?

**Comment by TropicalYeti** [comment]
Known issue, multiple duplicates. Its fixed in the next version, so just sit tight for a while til its released.

**Comment by Alex-the-666** [comment]
fixed

**Comment by CaatChan** [comment]
mine not fixed yet

**Comment by TropicalYeti** [comment]
It doesn't update automatically silly
