### ISSUE TITLE
henodus does not move at all

### ISSUE THREAD

**Issue by sevvervvater** [FossilsArcheologyRevival/FossilsArcheologyRevival#1494]

**Comment by Liam-dinogirl34** [comment]
Have you tried putting it in the water first? They're sea turtles.

**Comment by sevvervvater** [comment]
It stays still in the water on top of its feeder, I have three and they just sit there and I tried using the stick to have it follow me and it moved up a block or two after I moved far away,,

**Comment by BlueWither** [comment]
Yes they stops. There is something wrong on their AI...

**Comment by doggusaurus** [comment]
i fixed this by setting to wandering

**Comment by Alex-the-666** [comment]
#1511
