### ISSUE TITLE
Dinopedia Diplocaulus Bug

### ISSUE THREAD

**Issue by DragonGrimoire** [FossilsArcheologyRevival/FossilsArcheologyRevival#1497]
Using a dinopedia on a Diplocaulus to look at it's status simple says "Pregnant Diplocaulus" and "Embryo Progress 0%" even right as it hatches

**Comment by Angery-Balaur** [comment]
It is a widely known and reported bug that the dinopedia is only displaying nonexistent pregnancies. This happens with every animal (Except for, ironically, pregnant mammals). Copy of... god I don't know which report but yeah, somebody's gonna have to take this down
