### ISSUE TITLE
Villager on dig site often spawning in underground or sky

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1498]
Both will die

**Comment by BlueWither** [comment]
Just like this
![2019-09-22_20 31 24](https://user-images.githubusercontent.com/34153394/65386760-880fdb80-dd7a-11e9-992b-0769219fe582.png)
![2019-09-22_20 40 41](https://user-images.githubusercontent.com/34153394/65386762-9100ad00-dd7a-11e9-9b03-72fec5c9fd82.png)

**Comment by Velocihater** [comment]
I can back this up, structures in general are buggy

![2019-09-21_14 18 09](https://user-images.githubusercontent.com/40730042/65391542-1874fe80-dd30-11e9-9716-d78493c728ae.png)
![2019-08-22_18 50 31](https://user-images.githubusercontent.com/40730042/65391555-380c2700-dd30-11e9-88cc-92dea52e2af9.png)
![2019-08-08_12 39 18](https://user-images.githubusercontent.com/40730042/65391570-4bb78d80-dd30-11e9-80c7-6a2adb0403eb.png)

**Comment by lindstheginj** [comment]
Seems to have improved in the 8.0.4 beta.

**Comment by V-Boy** [comment]
![2020-04-03_14 29 47](https://user-images.githubusercontent.com/40730042/78398230-5644c080-75b8-11ea-8675-acf4cfdfdac9.png)
It seems to still happen
