### ISSUE TITLE
Menu flashing and not able to interact with

### ISSUE THREAD

**Issue by Dejotah** [FossilsArcheologyRevival/FossilsArcheologyRevival#1510]

**Comment by Dejotah** [comment]
IN ENGLISH: Menu fleshing all animations without let me click in the buttons. :/

**Comment by Dejotah** [comment]
GUYS GOOD NEWS DO IT: Go to .minecraft/config/fossils.cfg and set custom main menu to false 

This worked to me, thx Mshroomsock.

**Comment by Alex-the-666** [comment]
dupe
