### ISSUE TITLE
Bug: "item.fossilseed_duisbergia.name" instead of the actual name of seed

### ISSUE THREAD

**Issue by MrWashingToad** [FossilsArcheologyRevival/FossilsArcheologyRevival#1514]
![2019-08-28_17 01 46](https://user-images.githubusercontent.com/15614249/63901183-80565480-c9d1-11e9-8b2d-37df60800b7c.png)

Normal name not showing for the Duisbergia seeds.

**Comment by Gift-of-Names** [comment]
Already fixed for 8.0.3, duplicate of #1482
