### ISSUE TITLE
[1.12.2] Conflint with 'Mine Addons 2'. Autosmelt Tinkers Trait smelts Sand into Glass Pile instead of Glass.

### ISSUE THREAD

**Issue by Z-Tunic** [FossilsArcheologyRevival/FossilsArcheologyRevival#1520]
Refer'd Issue:
https://github.com/iamshift/MineAddons2/issues/11

Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 6
fossilsarcheology-8.0.2
jei_1.12.2-4.15.0.279
llibrary-1.7.17-1.12.2
Mantle-1.12-1.3.3.55
MineAddons-v2.10-mc1.12.2
TConstruct-1.12.2-2.12.0.157

-----

Having both Fossils & Mineaddons installed with Tinkers causes the Trait "Autosmelt" to smelt Sand into Glass Piles. In order to get Glass Piles... you would need to put Glass into a furnace to melt it down into Glass Piles.

Before adding Fossils... Autosmelt Trait would smelt Sand into Glass. Removing Mineaddons while keeping Fossils would cause Autosmelt Trait to smelt Sand into Glass.

I am unsure if this would be the place to post this but being that I just added the mod 'Fossils' and tried to get some Glass with the Autosmelt Trait... only it gave me Glass Piles instead so figure I give it a mention.

Configs are at their defaults.

**Comment by Alex-the-666** [comment]
How is this our issue? What would Fossils have to do with this?

**Comment by Z-Tunic** [comment]
I'm confused about it as well. I wasn't really sure where to post the issue exactly hence why I opened up the issue here & for the other mod to see which one's conflicting.

Unless it could also occur on Tinker's side perhaps? It works fine with either one of them are installed though.
