### ISSUE TITLE
Two-block tall plants can multiply by using bone meals, since others cannot

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1521]
This system should be changed.
For example, how about having a chance to get seeds and spores by using bone meal on plants?

**Comment by wolf653** [comment]
This is normal with tall plants like with the rose bush, etc

**Comment by BlueWither** [comment]
I know about that

**Comment by BlueWither** [comment]
This may suggestion, so I'll close this
