### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Stonka2115** [FossilsArcheologyRevival/FossilsArcheologyRevival#1526]
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: fossilsarcheology/client/model/prehistoric/ModelTriceratops 

Please help me :/

**Comment by TropicalYeti** [comment]
you know, error isnt a very good way to describe your problem. What exactly happened? Was it a crash? did the game never load?

**Comment by lindstheginj** [comment]
Sounds like someone forgot to install Llibrary.

**Comment by Alex-the-666** [comment]
^
