### ISSUE TITLE
No ensure way to get Flying creatures on the ground

### ISSUE THREAD

**Issue by kihgy** [FossilsArcheologyRevival/FossilsArcheologyRevival#1535]
Flying creatures are very hard to get a hold on when they start flying, I have a few suggestions on how to solve this. The only flying mobs atm are pterosaurs and flying insects like the Meganeura. For the pterosaurs, I suggest escort AI similar to the dragons from I/F, and for the meganeura, I suggest pixie following AI, if they follow you, they should tp to you even on air blocks. The next problem is gather them at one place, there is no way to calm down pterosaurs nor the insects, I suggest to be a mode in the drum when hitting, will put them into sitting mode, and bring them down, so you can place a drum near your escaped pterosaur to call it down. I am aware that the drum is currently broken, so maybe implement this once it is fixed?

**Comment by lindstheginj** [comment]
Pteranodon now lands more often in 8.0.4 beta. Closing bc of that and also because drum was intentionally disabled.
