### ISSUE TITLE
everything pregnant

### ISSUE THREAD

**Issue by cowboyluigi** [FossilsArcheologyRevival/FossilsArcheologyRevival#1540]
basicly everything is pregent with embryo at 0% and i ment everything. from gars to babys dinos as well. also it is stuck on 0% 
![bug](https://user-images.githubusercontent.com/55820452/65653610-cb608900-dfca-11e9-8f83-e883e645b28a.png)

**Comment by TropicalYeti** [comment]
Dupppppeeeee

**Comment by Alex-the-666** [comment]
dupe
