### ISSUE TITLE
Machine RF not working

### ISSUE THREAD

**Issue by Ceetron** [FossilsArcheologyRevival/FossilsArcheologyRevival#1555]
I enabled in the config that machines require RF to function, and replicated the preview that was shown. The GUI for RF shows but no RF is transferred from a mekanism energy cube

![2019-09-29_17 09 05](https://user-images.githubusercontent.com/16466291/65834643-75972400-e2dd-11e9-9df8-2c472a1fc365.png)
![2019-09-29_17 09 14](https://user-images.githubusercontent.com/16466291/65834649-847dd680-e2dd-11e9-8e3c-85eb2cc5cb89.png)

**Comment by Alex-the-666** [comment]
you need to install redstone flux for it to work

**Comment by Ceetron** [comment]
My bad i apologise

**Comment by Alex-the-666** [comment]
np
