### ISSUE TITLE
Growing different trees.

### ISSUE THREAD

**Issue by NatalTadPole** [FossilsArcheologyRevival/FossilsArcheologyRevival#1556]
Hello dear F/A Revival team, I recently experienced a bug after the new update for 1.12.2 that the mod saplings when placed down and then grown with bonemeal would sometimes grow an entirely different tree. For example if I put down a palaeoraphe tree it would sometimes spawn a cordaites tree instead, or any of the other mod trees. I hope you found this information useful, otherwise if it were lacking information you can just email me.

**Comment by TropicalYeti** [comment]
dupe of #1546

**Comment by Alex-the-666** [comment]
fixed
