### ISSUE TITLE
Baby pigs spawning next to EVERY EntityLiving

### ISSUE THREAD

**Issue by TheWoodenWizard** [FossilsArcheologyRevival/FossilsArcheologyRevival#1557]
Hey,

I just downloaded the new version and a player's stuck "pregnant" dryosaurus started progressing the rate of pregnancy. Once it gave birth, all the living entities in the world that had to do with the player that hatched the dryosaurus gave birth to a baby pig (my entities and wolves didn't). I logged on a day after, and now I noticed that all my animals (wolves, cows, chickens, horse, etc.) also gave birth to a baby pig each...

Playing on Dedicated Minecraft Server, not Integrated.

Please fix this bug as soon as possible, thanks!

Below I attached some screenshots of the pigs, idk if they're of use to you.
If you need any more information, please feel free to ask and I'll do my best to answer.

Thanks!

Danfinite
![2019-09-29_12 53 11](https://user-images.githubusercontent.com/22728348/65835791-75386200-e2b8-11e9-9ca4-cb37c35b2f8b.png)
![2019-09-29_12 53 04](https://user-images.githubusercontent.com/22728348/65835793-7a95ac80-e2b8-11e9-9c68-b2ca42210ee2.png)
![2019-09-29_12 52 39](https://user-images.githubusercontent.com/22728348/65835794-7c5f7000-e2b8-11e9-947e-f5faaeda236d.png)
![2019-09-29_12 52 21](https://user-images.githubusercontent.com/22728348/65835797-81242400-e2b8-11e9-859f-f07cc7d0fa89.png)

**Comment by Raptorofwar** [comment]
Dupe issue.

**Comment by TheWoodenWizard** [comment]
Nope, not fake... I wouldn't waste my time trying so hard to fit baby pigs everywhere.

**Comment by Raptorofwar** [comment]
I didn't say it was fake. I said it was a duplicate issue, in that it's already been reported. I believe Alex said it was the only way to fix the infinite pregnancy thing in 8.0.2. So just have fun cutting some chops I guess.

**Comment by TropicalYeti** [comment]
enjoy the pork.

**Comment by TheWoodenWizard** [comment]
Alright xD
Thanks guys

**Comment by katubug** [comment]
I did some searching and I did not see any duplicates of this issue, open or closed. Can you provide a link?

In the meantime, this is causing some issues on our multiplayer server due to the excessive number of piglets. Several times I've run `/forge entity list` and the amount of pigs was 75-150. To compare, the next most common passive mob was only at 14. And even the hostile mobs were only at about ~50 each, maximum. If there's a way to fix this, we'd really appreciate it.

**Comment by Velocihater** [comment]
This is intended to solve the pregnancy bug

**Comment by katubug** [comment]
So it's intended behavior that every creature on the server will spawn baby pigs?

That doesn't sound like a great solution imo.

**Comment by Velocihater** [comment]
It's supposed to be a one time thing yes.

**Comment by katubug** [comment]
Ah, okay, that makes so much more sense. I was under the impression that it was something that would keep happening, and I was totally baffled! Lol.

I'll assume that the reason it seemed to happen twice was just a matter of new chunks with dinos getting loaded for the first time. Thank you very much!
