### ISSUE TITLE
Dinosaurs going into corners enclosures walls and then die from suffocating inside them.

### ISSUE THREAD

**Issue by dinosaurking999** [FossilsArcheologyRevival/FossilsArcheologyRevival#1558]
Ever since I installed fossils and archaeology 8.0.3, I went back into my park my one stegosaurus died then a message appeared saying that stegosaurus suffocated in wall, and there weren't any holes in them. So then I made a new stegosaurus and the next thing that happened was another dinosaur suffocated in a wall, but this time it was one of my triceratops. So then I made another triceratops and then I started to keep my eye on all of my creatures in their enclosures and then when everything seems fine, my one of my ankylosaurus suffocated in a wall and again none of my enclosures had any holes in them, and I turned dino block breaking off. So if any mod devs are looking at this please look into it to see if it's a bug, or if your not then at lest give me some ideas on how to put an end to this problem.

**Comment by acolytess** [comment]
Mine are doing the same thing. I hadn't seen any suffocate in walls before updating, but after updating I've had 7 creatures, from Smilodon to Triceratops suffocate in walls, corners, and trees.

**Comment by ThatOneGaymer** [comment]
I've had this issue a lot. My friend wanted to mass produce megalodons for her 'shark army' so she made little growing cages under an ocean, only to find that 75% of them were dead when she went to tame them. Eventually she did a bit of a stakeout and figured out that they would swim up to a top corner and just sit there, stuck, to grow and suffocate
