### ISSUE TITLE
Almost every creature doesn't eat from feeder

### ISSUE THREAD

**Issue by alfieboris** [FossilsArcheologyRevival/FossilsArcheologyRevival#1562]

**Comment by BlueWither** [comment]
I saw mobs sometimes eating from feeder

**Comment by PartySwine** [comment]
I kinda agree on this one. My Gallis aren't eating. Meganuera, Crassygyrinus, Diplocaulus, Sarcosuchus...almost all the dinos are having this problem in my world.

**Comment by katubug** [comment]
Just as another data point, I have a juvenile Parasaurolophus who seems to be eating wheat from her feeder. She doesn't seem to eat past 132/175 hunger, though, despite the feeder being completely full.

**Comment by katubug** [comment]
Ah! So we discussed this today on my server, and apparently the feeders now need to be placed above ground in order to be eaten from. I'm not sure if this change is intentional, but at least it's an easy workaround for now.

**Comment by katubug** [comment]
Just wanted to add an additional report from one of my players:

> FYI, I have an herbivore (Citipati) in my workshop with enrichment and a feeder off the ground to test if he'll end up feeding himself. No water, so he shouldn't drown. So far he's not feeding himself but I'll give it a little while, then update you!
> 
> Okay, here's an update on the Citipati with screenshots.
> Here's his dinopedia entry currently. Hunger is 98/120, and he won't eat from the feeders.

![2019-10-06_10 18 39](https://user-images.githubusercontent.com/20935286/66273514-4c751700-e83a-11e9-9634-3da9e52346a4.png)

> Here's the placement of the feeders. I have two at two different heights off the ground in case it's finicky about the precise height.

![2019-10-06_10 18 47](https://user-images.githubusercontent.com/20935286/66273523-5a2a9c80-e83a-11e9-9ede-c922a827d9a5.png)

> Inside one of the feeders. Full of food. (Ignore the fact that the carnivore side is also full. This is a feeder I was using for one of my carnivores previously.)

![2019-10-06_10 19 26](https://user-images.githubusercontent.com/20935286/66273535-6adb1280-e83a-11e9-92ca-8c58c2ae7e70.png)

> Additional information: I noticed when I would fly around and check on each of my dinos (before I lassoed them all up), the carnivores (T-Rex and Spinosaurus) would rarely have hunger issues, whereas all of the herbivores would be starving. However, when I had my deinonychus out in my workshop (like the Citipati here), she wouldn't eat from the feeder either, so. I dunno.
> 
> Granted, with the herbivores, some of my feeders were on the ground, but some were also off the ground on the trees in the enclosure.

Also fwiw, in my singleplayer tests my feeder was sitting *on* the ground but not *in* the ground, and she'd eat from it. When Fish said it had to be above ground, I thought she meant like, not flush with the ground.

**Comment by ExaltedFossil** [comment]
Glad I'm not the only one who noticed this bug. I thought I was going crazy for a second.

**Comment by katubug** [comment]
I have another update:

```
Citipati (dinosaur in my workshop) update: He's eating from the feeder! Not sure if this would remain consistent across dinosaurs (both species and individual), but it seems like he's only bothering to eat from the feeder when his hunger drops below 90 (out of 120).
```

This is consistent with my findings, where the Parasaurolophus eats from a feeder but only until 132/175 hunger. Never above that.
