### ISSUE TITLE
[8.0.3] Game Crash [Server and Client] when killed by Tar Slime

### ISSUE THREAD

**Issue by JoelZBub** [FossilsArcheologyRevival/FossilsArcheologyRevival#1563]
Forge Versions Tested: **14.23.5.2838**, **14.23.5.2840**, **14.23.5.2847**
Fossils and Archeology: Revival Version: **8.0.3** 
LLibrary Version: **1.7.19-1.12.2**

**Summary**: When killed by a Tar Slime, the game hangs in single player and exits with a crash report indicating integrated server crash. When playing on a dedicated server, being killed by a Tar Slime results in a client crash and dedicated server crash.

This issue was discovered playing a single-player world and tested using multiple versions of Forge and then tested on a dedicated server. A clean instance of the game was created, as well as a clean server instance using only fossilarcheology-8.0.3 and llibrary-1.7.19. New worlds were generated.

**Steps to reproduce**: Play Minecraft in multi-player or single-player. Get killed by a Tar Slime.

Link to single-player (client playing on integrated server) crash report:
[https://hastebin.com/ibomanexuy.sql](url)

Link to multi-player (client playing on dedicated server) crash report:
[https://hastebin.com/axopaquxen.coffeescript](url)

Link to dedicated server crash report:
[https://hastebin.com/toborugozu.sql](url)

**Comment by Tarod7** [comment]
Same
https://paste.dimdev.org/fawewasisu.mccrash
