### ISSUE TITLE
Culture vats being Strange/popping new saplings out

### ISSUE THREAD

**Issue by SheepABeep** [FossilsArcheologyRevival/FossilsArcheologyRevival#1564]
After most current update, culture vats are spitting the fossilized saplings back at me.  

Been trying to cultivate the new saplings. (Sigillaria, Cordaites) 

When I try to put it in with a protein item that the recipe claims is valid, the vat won't consume the item and start cultivating, and when I leave the UI, the fossilized item returns to my inventory. Have tried attaching levers in the odd case it's a redstone signal issue, have used the vats prior to this update and Calamites and etc still work.

For courtesy, here is my (gargantuan) mod list.  Running on a remote server.
![modlist](https://user-images.githubusercontent.com/54867587/65916610-48a94680-e39b-11e9-93f1-a92d7e069358.png)

**Comment by Alex-the-666** [comment]
fixed
