### ISSUE TITLE
DinoPedia isn't Showing Mood of Dinosaurs or Other Prehistoric Creatures

### ISSUE THREAD

**Issue by DragonInASuit** [FossilsArcheologyRevival/FossilsArcheologyRevival#1565]
The DinoPedia isn't working as it should, which I feel like might hinder taming certain animals since no one on my server will know what the mood of their dinosaur is. It's not that big of a deal, but I would like to let the creators of the mod know that it isn't working.

**Comment by lindstheginj** [comment]
Seems to be working fine for the 8.0.4 beta
