### ISSUE TITLE
Aquatic Mobs Jumping to Death 8.0.3

### ISSUE THREAD

**Issue by Shinyanorith** [FossilsArcheologyRevival/FossilsArcheologyRevival#1567]
The aquatic mobs when on land or in water keep jumping, high enough to take three hearts of damage each time. Really weird! 
Tested with Megalodon, Mosasaurus, Megalograptus, Ichthyosaurus.

**Comment by lindstheginj** [comment]
Were you using the mod Lucraft when this was occurring?
