### ISSUE TITLE
*insert dino, prehistoric animal name here* has suffocated in a wall

### ISSUE THREAD

**Issue by panthera** [FossilsArcheologyRevival/FossilsArcheologyRevival#1575]
that is what i get when my animals like my citipati, megaloceros, and mammoth drown in a 1 block deep source of water, i think this is a bug because all 3 are too tall to have their heads submerged in that shallow of water and they were adults too........

**Comment by katubug** [comment]
Are they drowning or suffocating? If the chat log says they "suffocated in a wall," that means they clipped into a solid block and couldn't breathe. If they drowned, it would say "[entity] drowned" right?

**Comment by lindstheginj** [comment]
Duplicate of #1558 
Closing this issue to keep the list of issues concise.
