### ISSUE TITLE
Dinos sometimes won't eat from feeders and slowly starve to death

### ISSUE THREAD

**Issue by ExaltedFossil** [FossilsArcheologyRevival/FossilsArcheologyRevival#1587]
I've noticed in my creative world that sometimes the dinosaurs won't eat from feeders that are near them and they slowly die from starvation but once in a while they do eat weirdly. Both carnivores and herbivores are affected by this, however, the herbivores just eat the grass, whereas the only storage of food in the enclosures for the carnivores are in the feeders, in which by comparison the carnivores suffer much more from this bug. Luckily it's not too big a deal since this is a creative world, but I hope it gets fixed soon.

Edit: Forgot to mention that nearly all my carnivorous land dinosaurs have died, which as I stated before this wasn't really a big deal in creative mode since I can easily spawn them back, but please fix this as soon as possible. It makes for a terrible creative mode issue and an even worse survival mode issue.

**Comment by katubug** [comment]
Maybe related to this issue: https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1562

**Comment by Immaculala** [comment]
I only have 1 Galli and have the same problem (which is why I've not yet incubated any more dinos). I have feeders at various levels and she doesn't take one scrap. I've had to hand feed her to keep her alive.

**Comment by Alex-the-666** [comment]
fixed
