### ISSUE TITLE
Scratching post issues

### ISSUE THREAD

**Issue by EmperorPlebpatine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1593]
- Tyrannosaurus and spinosaurus struggle to interact with the scratching post
- Citipati and edaphosaurus either don't have an attacking animation or don't use it
- Deinonychus and velociraptor break the scratching post when they try to use it
- After using the scratching post, ceratosaurus just kind of keeps trying to push against it
- Dilophosaurus, compsognathus, and gallimimus ignore the scratching post (although maybe gallimimus ignores it because of its incredible speed and herding A.I.)
- Smilodon try to use the scratching post but then end up pushing against it
- Pteranodon constantly attack the post again and again but nothing happens

**Comment by Immaculala** [comment]
Some of my dinos also break scratching post.
