### ISSUE TITLE
Prehistoric Trees disappear when growing on Biomes o Plenty dirt

### ISSUE THREAD

**Issue by Charmanth** [FossilsArcheologyRevival/FossilsArcheologyRevival#1609]
It took me two hours or so to figure out why my prehistoric trees were not growing and were actually disappearing from the world as they were supposed to grow.  Apparently they're not compatible with the Biomes o Plenty dirt, such as silty dirt and loamy dirt.  This is latest version of F/A (8.0.3) on 1.12.2 mc with Biomes o Plenty 7.0.1.2441

To replicate:
Plant prehistoric tree sapling on silty, sandy, or loamy dirt.
Wait or bonemeal until "growth" happens.
Watch as sapling disappears.

I can get around this by moving regular dirt to the biomes I want to plant these trees in, but it would be nice if there was some compatibility with Biomes o Plenty. :)

**Comment by Alex-the-666** [comment]
fixed
