### ISSUE TITLE
Sifter Crafttweaker Support Broken

### ISSUE THREAD

**Issue by mxnmnm** [FossilsArcheologyRevival/FossilsArcheologyRevival#1610]
fossils 8.0.3

I tried adding a recipe to the sifter with 1% odds but it ends up giving that item every time.  When I set it to 0.01 the JEI says it's 1% when looking at it by hitting u on the input item but when I looked up the recipe for the output item it would say 0%.  I changed the value to 0.02 and nothing changed.  For context I'm trying to turn advanced rocketry oxidized ferric sand into a custom item from content tweaker.  Hopefully the JEI weirdness can help you figure out what's wrong.  If you need more info let me know.

**Comment by Alex-the-666** [comment]
your entering it wrong.

the weight should usually be an integer. 1 = 1%, 0.5 = 0.5%, 30 = 30% etc.
