### ISSUE TITLE
suggestion: meats from I/F should be able to put in the culture vat

### ISSUE THREAD

**Issue by kihgy** [FossilsArcheologyRevival/FossilsArcheologyRevival#1616]
Dragons flesh and hearts, death worm flesh or ever more, idk

**Comment by lindstheginj** [comment]
The issues tracker is not a suggestion forum, its for bug reports. Please use the wiki for that.

**Comment by kihgy** [comment]
can you link me to the suggestion forum on the wiki?

**Comment by lindstheginj** [comment]
https://fossils-archeology.fandom.com/wiki/Special:Forum
