### ISSUE TITLE
Character inside Allosaurus when riding

### ISSUE THREAD

**Issue by Ekatii** [FossilsArcheologyRevival/FossilsArcheologyRevival#1619]
When getting on a tamed Allosaurus the character is horse height with the ground it seems. Tames just fine and also follows directions perfectly. Just..a little lower seated than expected. 

![Allosaurus ticket](https://user-images.githubusercontent.com/57613178/68565036-f63a5b80-0417-11ea-8e8d-99ba5ba8fd5c.png)

**Comment by Alex-the-666** [comment]
fixed
