### ISSUE TITLE
Tar slimes causing server lag and rubber-banding

### ISSUE THREAD

**Issue by darthvader45** [FossilsArcheologyRevival/FossilsArcheologyRevival#1622]
Fossils and Archaeology version 8.0.3

For some reason, whenever I encounter tar slimes in the swamps, I get intense lag and rubber banding issues that build up until eventually the game itself freezes.  Not only that, but tar slimes that latch on to my head stay there and damage me even if I'm not touching them until they are killed.  I've had this happen far too many times now to count, and would very much like this fixed.  I'm going to have to kill all tar slimes around me to make swamp visits bearable, as I cannot disable the tar pits and slimes entirely (I'd miss out on a cool feature).

**Comment by darthvader45** [comment]
Only real workaround right now is disabling them outright.  I'd suggest extending the vanilla slime classes and such for animation and things like that.  Might make it a bit easier to work with and less buggy.  No way the vanilla slime could be that buggy.

**Comment by MokahTGS** [comment]
Also causing client crashes:

https://paste.dimdev.org/azoyabipob.mccrash
