### ISSUE TITLE
Title Screen

### ISSUE THREAD

**Issue by HermanSlug** [FossilsArcheologyRevival/FossilsArcheologyRevival#1623]
Main menu flashes through many images and no buttons are clickable, the llibrary is installed, any known incompatibilities? I cannot even get to choose a world with this mod installed, let alone play it and test it out, which I really would like to.

**Comment by Mushroomsock** [comment]
This is an incompatibility with Obsidian Animator. You can fix it by disabling this mod's custom main menu in the config file.

**Comment by HermanSlug** [comment]
Thank you very much!!

**Comment by lindstheginj** [comment]
Video of issue in #1094
