### ISSUE TITLE
nautilus, creepvine and ice and fire interaction cause lag spike and crash

### ISSUE THREAD

**Issue by Biviho** [FossilsArcheologyRevival/FossilsArcheologyRevival#1638]
nautilus, interacting with creepvine, and ice and fire, will cause a pretty big lag spike with occasional crash with this crash log: 
[crash-2020-01-14_00.49.45-server.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/4100226/crash-2020-01-14_00.49.45-server.txt)

-tested with fossil and archeology, ice and fire, better diving: lag spike with occasional crash
-tested without fossil and archeology, with ice and fire and better diving: no lagspike nor crash
-tested without nautilus natural spawning: no lagspike nor crash, if set them to spawn after the world is loaded they will not cause any lag or crash for some reason (?)
-tested without better diving with nautilus natural spawning and ice and fire: no lagspike or crash
-tested without ice and fire with nautilus natural spawning and better diving: no lagspike or crash

**Comment by Alex-the-666** [comment]
issue is with

better diving. tell their devs
>
java.lang.NullPointerException
    at meldexun.better_diving.block.AbstractBlockCreepvine.setCreepvine(AbstractBlockCreepvine.java:32)
