### ISSUE TITLE
Sturgeon, gar, coelacanth and nautilus, vanishing in water

### ISSUE THREAD

**Issue by Xaurii** [FossilsArcheologyRevival/FossilsArcheologyRevival#1640]
I'm playing on a modded server with a modpack I've created with friends.
in getting my first set of sturgeon eggs, and trying to spawn it, i found it vanished after roughly 4 seconds of being in the water. 
They're also fine when on land, and will survive until they suffocate, but as soon as i push them into water, they will vanish after a few moments
aquatic dinosaurs are fine, but the fish seem effected by something. (i tested them all in creative, and only the fish +nautilus are broken)
I thought it could be Animania, and even after removing the mod, its still broken. 
(can provide mod list +a recording)

**Comment by assasinwar9** [comment]
so i am getting something "close" to this on 1.12 (if that really matters atm) and i noted its... only when IM in the water with them.... and its all strictly small aquatic creatures ... so all the fish, plus the nautilus... plus a good portion of the "small" aquatics from the "Prehistoric Nature" mod.... and can confirm this happens in survival.... i even went and found multiple live nautilus's that spawned and tried to "grab them" but... they flee and then just "vanish" .... but i noted that all the mobs iv "incubated/cultivated" would stay around... till i was "near them IN the water".... then they would ALSO flee and "vanish" aka despawn


sadly i cant find any clue on WHAT is causing this.... help would be appreciated ofc
