### ISSUE TITLE
Spinosaurus spinning constantly

### ISSUE THREAD

**Issue by GalacticNarwal** [FossilsArcheologyRevival/FossilsArcheologyRevival#1642]
I'm not 100% sure if this is a bug, but in my survival world, I have a Spinosaurus enclosure with a large pond in the middle of it. She spends most of her time in the pond, but the main problem is that she just does nothing but spin around in circles until I nudge her, at which point she will stop, but after a couple seconds, she'll start doing it again.

**Comment by BlueWither** [comment]
I think almost semi-aquatic mobs do so...

**Comment by GalacticNarwal** [comment]
Seems like a bug to me.
