### ISSUE TITLE
Please help ALL my dinos are giving birth to vanilla baby pigs

### ISSUE THREAD

**Issue by scarletwolf134** [FossilsArcheologyRevival/FossilsArcheologyRevival#1644]
I just updated and  ALL my dinos are giving birth to vanilla baby pigs baby pigs even males and egg layers the only way I found to stop it is to kill everything but I've been working on my main world for 7 months! I really can't do that.

**Comment by Mushroomsock** [comment]
This should only happen for each mob once when you first update, it’s related to the bug from the previous version where every dinosaur showed up as pregnant in the dinopedia, and this was a side-effect of the fix.
