### ISSUE TITLE
My dinos keep starving because they wont eat from feeders

### ISSUE THREAD

**Issue by scarletwolf134** [FossilsArcheologyRevival/FossilsArcheologyRevival#1645]
^ after I updated the ai somehow got way worse they wont eat from feeders or play with toys until I push them on top pf them

**Comment by GalacticNarwal** [comment]
There's an option in the config file to turn off starving dinos.

**Comment by scarletwolf134** [comment]
ok but where is this config file the mod only came with one file the mod it self I have no idea how to do any file editing

**Comment by GalacticNarwal** [comment]
While you're in the game menu, click Mods, find F/A, click it, click config

**Comment by scarletwolf134** [comment]
that solves the dieing but the issue still stands what happened to the ai and why are my dinos seemingly now about as smart as vanilla mobs and interact with nothing

**Comment by ohyeahboieatmyfeijoada** [comment]
Spinosaurus is one of them? They don't eat from feeders.

**Comment by Alex-the-666** [comment]
fixed tall mobs not eating from it
