### ISSUE TITLE
Tiktallik cannot move in land.

### ISSUE THREAD

**Issue by ohyeahboieatmyfeijoada** [FossilsArcheologyRevival/FossilsArcheologyRevival#1652]
They cannot move inland! None land, dirt, glass, grass; etc.

**Comment by Raptorofwar** [comment]
This is intentional.

**Comment by ohyeahboieatmyfeijoada** [comment]
> This is intentional.

"Tiktaalik are semi-aquatic, which means they can stay in both water and land. They are pretty slow on land, but fast in water. They prey on most small mobs. They will not play with bubble blowers."

**Comment by Angery-Balaur** [comment]
The Tiktaalik are meant to be able to crawl on land, it's the other two amphibians who are fully aquatic.

**Comment by ohyeahboieatmyfeijoada** [comment]
> meant

Yes!

**Comment by BlueWither** [comment]
#1468
