### ISSUE TITLE
Config option overlap

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#1668]
There's an option for Palaeoraphe Spawning and an option for Prehistoric Tree Spawning, so the Palaeoraphe option could be removed.

**Comment by ohyeahboieatmyfeijoada** [comment]
I don't see any problem with that.

**Comment by lindstheginj** [comment]
We are testing the 8.0.4 version. Please do not compare these bugs to 8.0.3.

**Comment by Alex-the-666** [comment]
@lindstheginj this is normal, delete your config to fix it
