### ISSUE TITLE
Allosaurus and tyrannosaurus don't seem to attack stegosaurus and triceratops respectively

### ISSUE THREAD

**Issue by EmperorPlebpatine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1688]
Despite being hungry, tyrannosaurus doesn't seem to go after triceratops, nor allosaurus after stegosaurus. I would suggest for allosaurus to go after stegosaurus but only when starving, while tyrannosaurus should see triceratops as a regular prey item.

**Comment by Alex-the-666** [comment]
fixed
