### ISSUE TITLE
Wonky Structure Spawning for the Academy and Fossils

### ISSUE THREAD

**Issue by BugmanBugman** [FossilsArcheologyRevival/FossilsArcheologyRevival#1711]
![2020-04-02_19 08 08](https://user-images.githubusercontent.com/40730042/78311067-71aabf80-7515-11ea-8b9e-a6dbc10de788.png)
![2020-04-02_19 05 48](https://user-images.githubusercontent.com/40730042/78311072-74a5b000-7515-11ea-87d0-ef54b1d9f4d8.png)
![2020-04-02_19 05 47](https://user-images.githubusercontent.com/40730042/78311073-75d6dd00-7515-11ea-9e9b-70fba462fccc.png)
![2020-04-02_19 05 43](https://user-images.githubusercontent.com/40730042/78311076-77080a00-7515-11ea-8e4e-f68b537176d2.png)

**Comment by lindstheginj** [comment]
Try deleting your config and letting it regenerate, then make a new world. Is spawning still funky?

**Comment by V-Boy** [comment]
![2020-04-03_14 49 55](https://user-images.githubusercontent.com/40730042/78400658-c0f7fb00-75bc-11ea-8a65-2cddf2ec7433.png)
![2020-04-03_14 49 29](https://user-images.githubusercontent.com/40730042/78400663-c2c1be80-75bc-11ea-8ce3-2fc2e45ea193.png)
![2020-04-03_14 52 26](https://user-images.githubusercontent.com/40730042/78400665-c35a5500-75bc-11ea-906b-61032a062640.png)
![2020-04-03_14 53 24](https://user-images.githubusercontent.com/40730042/78400669-c3f2eb80-75bc-11ea-9f8e-f1ebdca88157.png)
reset config and did a new world but it still seems to be funky. I couldn't find an academy to check but i did find a jungle temple with weird spawning.
