### ISSUE TITLE
Culture Vat is not Taking Fuel

### ISSUE THREAD

**Issue by AetherVoided** [FossilsArcheologyRevival/FossilsArcheologyRevival#1713]
I have just downloaded 8.0.4 to play and it was going well until I wanted to create a dilophosaurus and found that I can not place any type of fuel into the cultivator (milk, eggs, or any meat). I've restarted my world and my game to try and see if it would fix it, but no luck.

**Comment by Mushroomsock** [comment]
Have a look at the changelog, culture vats now use a new item called Bio-Goo.

**Comment by lindstheginj** [comment]
These items are no longer accepted as fuel. They've been replaced with Bio-Goo (mentioned in the changelog). Shapeless crafting: milk bucket, egg, wheat, and rotten flesh/failuresaurus flesh. Only one goo needed per cultivation.
