### ISSUE TITLE
Un-Craftable Cultivator

### ISSUE THREAD

**Issue by HDgamerDino** [FossilsArcheologyRevival/FossilsArcheologyRevival#1715]
The Cultivator is currently unusable and you can only use bio-goo to create eggs.

**Comment by Mushroomsock** [comment]
This is intended.

**Comment by Raptorofwar** [comment]
Did you know the Culture Vat is now only craftable with slimeballs instead of cactus green? You can also substitute tar drops or failuresaur flesh for the cactus green.

Bio-goo is now the sole fuel for Culture Vats. We must now worship our goo overlords.
