### ISSUE TITLE
Crash when summoned Anu from Coffin

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1718]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-04-03 19:28:17 JST
Description: Ticking entity

java.lang.IllegalArgumentException: value already present: net.minecraft.client.audio.PositionedSoundRecord@3e43057c
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
    at net.minecraft.client.audio.SoundManager.playSound(SoundManager.java:430)
    at net.minecraft.client.audio.SoundHandler.playSound(SoundHandler.java:258)
    at fossilsarcheology.client.ClientProxy.playSound(ClientProxy.java:255)
    at fossilsarcheology.server.entity.monster.EntityAnu.onLivingUpdate(EntityAnu.java:264)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbd000(World.java:4118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: fossil:fossil.anu (fossilsarcheology.server.entity.monster.EntityAnu)
  Entity ID: 2947
  Entity Name: アヌ
  Entity's Exact location: -1987.50, 71.00, -2908.50
  Entity's Block location: World: (-1988,71,-2909), Chunk: (at 12,4,3 in -125,-182; contains blocks -2000,0,-2912 to -1985,255,-2897), Region: (-4,-6; contains chunks -128,-192 to -97,-161, blocks -2048,0,-3072 to -1537,255,-2561)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Attributes:[{Base:600.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.35d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:40.0d,Name:"generic.followRange"},{Base:2.0d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,AttackMode:0,FallDistance:0.0f,DeathTime:0s,ForgeCaps:{"dsurround:emojidata":{as:0,es:0,et:0},"llibrary:extendedentitydatacapability":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Motion:[0.0d,0.0d,0.0d],Leashed:0b,UUIDLeast:-7003627750782910643L,Health:600.0f,VFAABB:[-1988.0d,71.0d,-2909.0d,-1987.0d,72.79999995231628d,-2908.0d],LeftHanded:0b,Air:300s,OnGround:0b,Dimension:0,Rotation:[0.0f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:-453478273093644835L,Pos:[-1987.5d,71.0d,-2908.5d],Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Nonname114'/0, l='MpServer', x=-1985.31, y=71.28, z=-2907.22]]
  Chunk stats: MultiplayerChunkCache: 154, 154
  Level seed: 0
  Level generator: ID 06 - quark_realistic, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (216,64,164), Chunk: (at 8,4,4 in 13,10; contains blocks 208,0,160 to 223,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 56839 game time, 4942 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 62 total; [EntitySkeleton['スケルトン'/1538, l='MpServer', x=-1985.50, y=14.00, z=-2963.50], EntityZombie['ゾンビ'/2307, l='MpServer', x=-1954.50, y=17.00, z=-2885.50], EntityDiplodocus['Diplodocus'/1032, l='MpServer', x=-1961.81, y=62.41, z=-2854.55], EntityBat['コウモリ'/2325, l='MpServer', x=-1944.30, y=25.10, z=-2933.30], EntityDiplodocus['Diplodocus'/2078, l='MpServer', x=-1970.82, y=71.00, z=-2894.28], EntityDiplodocus['Diplodocus'/2084, l='MpServer', x=-1976.63, y=71.00, z=-2890.40], EntityCreeper['クリーパー'/2853, l='MpServer', x=-1986.50, y=14.00, z=-2976.50], EntityCrab['カニ'/52, l='MpServer', x=-1989.23, y=67.00, z=-2865.29], EntityMinecartChest['チェスト付きトロッコ'/57, l='MpServer', x=-1959.50, y=24.06, z=-2930.50], EntityZombie['ゾンビ'/1594, l='MpServer', x=-2022.50, y=18.00, z=-2973.50], EntityMinecartChest['チェスト付きトロッコ'/63, l='MpServer', x=-1946.50, y=14.06, z=-2931.50], EntityFrog['カエル'/832, l='MpServer', x=-2013.50, y=24.04, z=-2892.50], EntityBat['コウモリ'/2114, l='MpServer', x=-1943.75, y=16.10, z=-2958.36], EntitySkeleton['スケルトン'/2378, l='MpServer', x=-1995.48, y=40.00, z=-2831.87], EntityEnderman['エンダーマン'/2379, l='MpServer', x=-2017.50, y=19.00, z=-2854.50], EntityBat['コウモリ'/2916, l='MpServer', x=-1977.66, y=36.87, z=-2977.66], EntitySturgeon['チョウザメ'/612, l='MpServer', x=-2039.45, y=58.40, z=-2855.75], EntityBat['コウモリ'/2921, l='MpServer', x=-1992.86, y=13.08, z=-2836.25], EntityCrab['カニ'/111, l='MpServer', x=-1912.33, y=73.00, z=-2910.50], EntityCrab['カニ'/112, l='MpServer', x=-1906.20, y=70.00, z=-2909.68], EntityCreeper['クリーパー'/2160, l='MpServer', x=-2045.50, y=20.00, z=-2863.50], EntitySkeleton['スケルトン'/2161, l='MpServer', x=-2046.50, y=20.00, z=-2864.50], EntityCrab['カニ'/114, l='MpServer', x=-1905.22, y=70.00, z=-2909.48], EntityOrnitholestes['Ornitholestes'/1911, l='MpServer', x=-1954.19, y=71.00, z=-2891.10], EntityAnu['アヌ'/2947, l='MpServer', x=-1987.50, y=71.00, z=-2908.50], EntityCrab['カニ'/644, l='MpServer', x=-2030.50, y=67.00, z=-2940.50], EntityMinecartChest['チェスト付きトロッコ'/139, l='MpServer', x=-1940.49, y=22.00, z=-2951.94], EntityCreeper['クリーパー'/2704, l='MpServer', x=-2016.50, y=19.00, z=-2854.50], EntitySkeleton['スケルトン'/1936, l='MpServer', x=-2032.53, y=19.00, z=-2848.73], EntityCreeper['クリーパー'/2705, l='MpServer', x=-2016.50, y=19.00, z=-2853.50], EntitySkeleton['スケルトン'/1949, l='MpServer', x=-1951.50, y=27.00, z=-2987.50], EntityMinecartChest['チェスト付きトロッコ'/159, l='MpServer', x=-1932.50, y=22.06, z=-2951.50], EntityZombie['ゾンビ'/1951, l='MpServer', x=-1947.50, y=27.00, z=-2987.50], EntityBat['コウモリ'/1953, l='MpServer', x=-1946.25, y=19.93, z=-2987.70], EntityBat['コウモリ'/1954, l='MpServer', x=-1948.50, y=19.10, z=-2980.50], EntitySkeleton['スケルトン'/1958, l='MpServer', x=-1952.50, y=27.00, z=-2985.50], EntityStoneling['ストンリング'/1960, l='MpServer', x=-2026.50, y=19.00, z=-2982.50], EntityCrab['カニ'/1704, l='MpServer', x=-2034.50, y=64.00, z=-2938.50], EntityZombie['ゾンビ'/2219, l='MpServer', x=-2046.50, y=21.00, z=-2867.50], EntityMinecartChest['チェスト付きトロッコ'/1964, l='MpServer', x=-1971.50, y=27.06, z=-2983.50], EntityZombie['ゾンビ'/2478, l='MpServer', x=-2018.50, y=42.00, z=-2961.50], EntityDweller['ドゥワラー'/1969, l='MpServer', x=-1961.50, y=16.00, z=-2874.50], EntityStoneling['ストンリング'/2742, l='MpServer', x=-1965.50, y=20.00, z=-2958.50], EntityCreeper['クリーパー'/2743, l='MpServer', x=-1957.50, y=32.00, z=-2962.50], EntityBat['コウモリ'/2232, l='MpServer', x=-1958.25, y=25.10, z=-2929.94], EntityStoneling['ストンリング'/1721, l='MpServer', x=-2042.50, y=18.00, z=-2923.50], EntityPlayerSP['Nonname114'/0, l='MpServer', x=-1985.31, y=71.28, z=-2907.22], EntitySpider['クモ'/1728, l='MpServer', x=-2036.30, y=19.00, z=-2848.70], EntityNautilus['オウムガイ'/1729, l='MpServer', x=-2042.12, y=57.08, z=-2850.73], EntityBat['コウモリ'/2765, l='MpServer', x=-2053.50, y=14.10, z=-2839.50], Swordfish['Swordfish'/2768, l='MpServer', x=-2054.50, y=57.00, z=-2876.50], Swordfish['Swordfish'/2773, l='MpServer', x=-2055.50, y=57.00, z=-2876.50], Swordfish['Swordfish'/2778, l='MpServer', x=-2053.50, y=57.00, z=-2877.50], CommonFish['Fish'/2791, l='MpServer', x=-2056.50, y=51.00, z=-2828.50], EntityOrnitholestes['Ornitholestes'/1769, l='MpServer', x=-1962.18, y=71.00, z=-2884.47], EntityBat['コウモリ'/2542, l='MpServer', x=-1971.81, y=55.98, z=-2911.56], EntityBat['コウモリ'/2543, l='MpServer', x=-1986.70, y=38.00, z=-2907.09], EntityAnuDead['死んだアヌ'/2799, l='MpServer', x=-1959.49, y=62.61, z=-2920.21], EntityStoneling['ストンリング'/2294, l='MpServer', x=-2028.50, y=21.00, z=-2830.50], EntityCrab['カニ'/759, l='MpServer', x=-2021.60, y=70.00, z=-2895.34], EntityCrab['カニ'/760, l='MpServer', x=-2021.48, y=70.00, z=-2897.22], EntityBat['コウモリ'/1534, l='MpServer', x=-2036.01, y=17.03, z=-2960.07]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3217155016 bytes (3068 MB) / 4277534720 bytes (4079 MB) up to 4277534720 bytes (4079 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 32 mods loaded, 32 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version           | Source                                          | Signature                                |
       |:------ |:------------------------ |:----------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2            | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                      | 9.42              | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | unicodefontextensioncore | 1.12.2-2.6        | minecraft.jar                                   | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4             | minecraft.jar                                   | None                                     |
       | LCHIJA | dsurroundcore            |                   | minecraft.jar                                   | None                                     |
       | LCHIJA | unicodefontextension     | 1.12.2-2.7        | UnicodeFontExtension-1.12.2-2.7.jar             | None                                     |
       | LCHIJA | abyssaldepths            | 1.12.2-0.2.1      | AbyssalDepths-1.12.2-0.2.1.jar                  | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCHIJA | jei                      | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                       | None                                     |
       | LCHIJA | quark                    | r1.6-177          | Quark-r1.6-177.jar                              | None                                     |
       | LCHIJA | autoreglib               | 1.3-32            | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCHIJA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.zip                          | None                                     |
       | LCHIJA | betterbuilderswands      | 0.12.0            | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
       | LCHIJA | clarity                  | 1.1               | clarity-1.1.jar                                 | None                                     |
       | LCHIJA | cosmeticarmorreworked    | 1.12.2-v1         | CosmeticArmorReworked-1.12.2-v1.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | ctm                      | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
       | LCHIJA | fastleafdecay            | v14               | FastLeafDecay-v14.jar                           | None                                     |
       | LCHIJA | foamfix                  | 0.10.7-1.12.2     | foamfix-0.10.7-1.12.2.jar                       | None                                     |
       | LCHIJA | llibrary                 | 1.7.19            | llibrary-1.7.19-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                   | 8.0.4             | fossilsarcheology-8.0.4.jar                     | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.0      | journeymap-1.12.2-5.7.0.jar                     | None                                     |
       | LCHIJA | mantle                   | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LCHIJA | mobbattle                | 2.3.3             | MobBattleMod-1.12.2-2.3.3.jar                   | None                                     |
       | LCHIJA | naturescompass           | 1.5.0             | NaturesCompass-1.12.2-1.5.0.jar                 | None                                     |
       | LCHIJA | quarkoddities            | 1                 | QuarkOddities-1.12.2.jar                        | None                                     |
       | LCHIJA | tconstruct               | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                | None                                     |
       | LCHIJA | torohealthmod            | 1.12.2-11         | torohealth-1.12.2-11.jar                        | None                                     |
       | LCHIJA | treecutter               | 1.0.3             | TreeCutter_1.12-v1.0.3.jar                      | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-98.jar                        | None                                     |
       | LCHIJA | dsurround                | 3.4.10.5          | DynamicSurroundings-1.12.2-3.4.10.5.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | presets                  | 3.4.10.5          | DynamicSurroundings-1.12.2-3.4.10.5.jar         | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.7-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-98.jar)
                                        
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
                                        bre.ufex.asm.Transformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4264' Renderer: 'Intel(R) HD Graphics'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Suspected Mods: Fossils and Archeology Revival (fossil)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics GL version 4.3.0 - Build 10.18.14.4264, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: MaidIcon_forVoxelMap.zip, Ice_ink ja_jp.zip, Shota_voice.zip, Grimoire-of-Gaia-3-Soundpack-1.0-1.12.zip, DragononMap.zip, ZAWALANG.zip
  Current Language: 日本語 (日本)
  Profiler Position: N/A (disabled)
  CPU: 2x Intel(R) Celeron(R) 3205U @ 1.50GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by ohyeahboieatmyfeijoada** [comment]
Maybe your PC is bad.

**Comment by BlueWither** [comment]
Is that really?
Although my PC is not good...
