### ISSUE TITLE
Cathemeral mobs almost not like to move

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1721]
Sarcosuchus and Diplodocus hardly move once they sleep.
They can get up, but they fall asleep quickly and practically do not move.

**Comment by Conclure** [comment]
This is a known issue which mosty likely be patched in the next update. For a detailed answer you may read what I wrote [here](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1776#issuecomment-622600846).
