### ISSUE TITLE
Cathemeral AI might need a bit of tweaking

### ISSUE THREAD

**Issue by EmperorPlebpatine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1722]
Cathemeral mobs (Sarcosuchus and diplodocus) have a much higher rate of sleeping than activity; however, due to the nature of the AI, RNG seems to be at play here. In some occasions people report a single dippy among a small herd up and about, other times people tell of how it starved to death in its sleep.

**Comment by ohyeahboieatmyfeijoada** [comment]
Nope, megalagapratus is to.
