### ISSUE TITLE
[Suggestion] Make the shovel a primary tool to mine the ash.

### ISSUE THREAD

**Issue by alfieboris** [FossilsArcheologyRevival/FossilsArcheologyRevival#1724]
It would be nice to mine it a lot quicker.

**Comment by lindstheginj** [comment]
This is not the appropriate place for suggestions. This is the ISSUES tracker. Please direct suggestions to the wiki forum. 
https://fossils-archeology.fandom.com/wiki/F/A_Mod_Revival_Wiki
