### ISSUE TITLE
Can´t put milk into a culture vat

### ISSUE THREAD

**Issue by icewallowkome** [FossilsArcheologyRevival/FossilsArcheologyRevival#1726]
Am playing on a save made with f/a 8.0.3 and haven´t played on it in a while. I replace the mod with 8.0.4 and try to put milk into a culture vat and it just denies it.

**Comment by TropicalYeti** [comment]
intended, you need bio-goo now

**Comment by icewallowkome** [comment]
Thank you so much! and god damn that was a fast response
