### ISSUE TITLE
Tiktaalik and Sarcosuchus can't jump at land

### ISSUE THREAD

**Issue by BlueWither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1727]
Although Spino could

**Comment by Mushroomsock** [comment]
Creatures going onto land is working fine for me, are you sure you're not just unlucky?

**Comment by BlueWither** [comment]
![2020-04-04_08 11 20](https://user-images.githubusercontent.com/34153394/78412096-11b73480-764d-11ea-8a28-44a5d1c9d8d0.png)
Sarco can't attack pig, because it can't jump.
Tikataalik was able to get out if it can jump a single step, but it didn't get out.
