### ISSUE TITLE
Some mob movement issues

### ISSUE THREAD

**Issue by EmperorPlebpatine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1730]
Many mobs not only move spastically, but they never stop moving like they're having a sugar rush either. I'd suggest they could be slowed down and given the ability to stay still for a bit.

The following mobs are affected by the non-stop movement:
- Gallimimus
- Mammoth
- Velociraptor
- Deinonychus
- Mosasaurus
- Liopleurodon
- Ichthyosaurus
- Plesiosaurus

**Comment by SandwichHorror** [comment]
Sarcosuchus constantly swims and turns spasmodically when in water like a hyperactive minnow.

**Comment by G3V52B** [comment]
Also the gallimimus AI could use some improvement, when it comes to a cliff it will stop too late becouse it's so fast and will fall to it's death
