### ISSUE TITLE
8.0.4 - Compatibility Issue with OTG on Existing Worlds

### ISSUE THREAD

**Issue by dragonshardz** [FossilsArcheologyRevival/FossilsArcheologyRevival#1734]
The addition of the new Volcano biome breaks this mods ability to work with OTG on existing worlds. See attached crash log.

It would be excellent if there was a way to pick the exact biome ID or for the biome ID to not attempt to register if generation of the biome is disabled.

[crash-2020-04-04_18.34.42-server.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/4432844/crash-2020-04-04_18.34.42-server.txt)

**Comment by SakuraWuhen** [comment]
I am an OTG user, I have encountered your problem, but this problem is very easy to solve, just delete the OpenTerrainGenerator under the world folder to regenerate it

**Comment by dragonshardz** [comment]
> I am an OTG user, I have encountered your problem, but this problem is very easy to solve, just delete the OpenTerrainGenerator under the world folder to regenerate it

This works, though anyone using this workaround should make sure to back up their config.yaml file for OTG.
