### ISSUE TITLE
feeders

### ISSUE THREAD

**Issue by almut1105** [FossilsArcheologyRevival/FossilsArcheologyRevival#1738]
the feeders don't work the dinos wont eat out of them

**Comment by lindstheginj** [comment]
No one else seems to be having this issue. Can you attach a picture of your feeder setup? Also something to note: our mobs will only eat if their hunger drops below 75%. So if they’re at like 80% of their hunger, then there is no issue.

**Comment by rauwebieten** [comment]
having the same problem, but not for all species. For about 50% of the species i have
