### ISSUE TITLE
tar seethrough 

### ISSUE THREAD

**Issue by geeman152** [FossilsArcheologyRevival/FossilsArcheologyRevival#1740]
not sure how to explain but in f5 looking at myself i can see through some parts of tar pit, image prob floating around on discord

**Comment by lindstheginj** [comment]
“Image on Discord” isn’t very helpful, considering this bug might not be looked at for fixing for months. Please attach an image when you have a chance.

**Comment by geeman152** [comment]
![image](https://user-images.githubusercontent.com/53543661/78577458-18d07500-77fc-11ea-8403-2d200a2a3324.png)

**Comment by geeman152** [comment]
that
