### ISSUE TITLE
Dromaeosaurids pouncing bug

### ISSUE THREAD

**Issue by EmperorPlebpatine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1742]
Deinonychus and velociraptor struggle with dealing damage to mobs that they've successfully clung to. They can only kill mobs if they use their alternative bite attack.

![image](https://user-images.githubusercontent.com/41919574/78581351-64cdea80-77f9-11ea-9b2f-ad95222f7772.png)

**Comment by SandwichHorror** [comment]
Seconded. In 5 trials, a whole pack of deinonychus could only kill 1 llama. The rest ran out of aggro range after successfully bucking the RPR attempt, which dealt no damage.
