### ISSUE TITLE
Some mobs struggle to attack prey

### ISSUE THREAD

**Issue by EmperorPlebpatine** [FossilsArcheologyRevival/FossilsArcheologyRevival#1744]
Some mobs occasionally follow what would be potential prey around, but don't seem to manage to hurt them; this applies to some carnivores like tyrannosaurus, spinosaurus, megalodon, ichthyosaurus, and plesiosaurus.

**Comment by KangaliaV** [comment]
I have observed this behaviour with a few land mobs, including a t-rex (it wasn't fully grown but had been following a lone pig around it's enclosure for 3 minecraft days and had not been able to kill it) and a spinosaurus (wouldn't even try to kill a cow, even when starving, and would only follow it around, only to give up, then start following it again, etc.). Not sure if this is related or not but I thought'd I'd put it here.
