### ISSUE TITLE
Male Mammoths Giving Birth?

### ISSUE THREAD

**Issue by YdnasLouisa-80** [FossilsArcheologyRevival/FossilsArcheologyRevival#1746]
So I have a park on a server my friend hosts and I made a mammoth enclosure with 1 male and 3 females. Every time I'd come back to the enclosure there would be multiple adult mammoths in there, so they were giving birth to adults. So I decided to isolate the male. After that it seemed that it was the male mammoth that was giving birth to the babies.

**Comment by Conclure** [comment]
You can read about the mammoth [here](https://fossils-archeology.fandom.com/wiki/Mammoth). "Adult mammoths can breed every five minutes as if there is a male and female present. The breeding probability is handled by how many individuals are nearby", taken from the wiki. However most F/A related mobs only require a male and a female in present for breeding freely.
