### ISSUE TITLE
Raptor not taming when hatching from an egg

### ISSUE THREAD

**Issue by Ashley123477** [FossilsArcheologyRevival/FossilsArcheologyRevival#1747]
Fossils 8.0.4 when placing a raptor egg and standing within 6 blocks of it hatching, it comes out untamed despite the wiki saying otherwise, feeding it with meat however still tames it

**Comment by LialaOkami** [comment]
This bug seems to be affecting most prehistoric animals. It happened to me on a LAN world with my datefriend for Gallimimus and Kelenken. Henodus seems to be taming just fine for now though.

**Comment by ChaonicTheDeathKitten** [comment]
I can confirm that the whip doesn't register and taming is impossible.
I've been patient with my Triceratops for 2 real life days now, only hand fed in that time and tried the whip countless times.
It doesn't even have a mood effect on it. Unless I start left clicking it with it. Which.. I am pretty sure, you're not supposed to tame a dino anyways.

Would love it if this got fixed.
