### ISSUE TITLE
all small herbivores not eating ferns

### ISSUE THREAD

**Issue by dinoman00** [FossilsArcheologyRevival/FossilsArcheologyRevival#1762]
all the small herbivores not eating ferns or grasses

**Comment by dinoman00** [comment]
all herbivores not eating ferns

**Comment by B-Wither** [comment]
I tried, but they ate.
In 8.0.4, creatures won't eat when hunger is over 75%.

**Comment by dinoman00** [comment]
so i just tested it the Megaloceros , dodo , Woolly rhinoceros will not eat when there hunger is below 75%
