### ISSUE TITLE
Dryosaurs not eating

### ISSUE THREAD

**Issue by ghost** [FossilsArcheologyRevival/FossilsArcheologyRevival#1766]
I left my dryosaurs with a log & ball toy, a feeder stocked full with plants and several fern patches, and after a few days their health was declining, so I checked them with the dinopedia and it turns out they were at 0% hunger. I checked the feeder and the numbers hadn't decreased.

**Comment by ohyeahboieatmyfeijoada** [comment]
idk







send whith enter geeeeijfosdf
![RobloxScreenShot20200425_002122612](https://user-images.githubusercontent.com/62614498/80553360-f3b8c780-899f-11ea-8d9b-b9b699fd7491.png)

**Comment by mEgstad69420** [comment]
Its a current issue in the mod with most herbivores. I recommend going into the config file to disable dino starvation.
