### ISSUE TITLE
Raptors breaks toy

### ISSUE THREAD

**Issue by B-Wither** [FossilsArcheologyRevival/FossilsArcheologyRevival#1770]
I gave Deinonychus a Scratching Post and a Tethered Log, but both were destroyed and turned into items.

**Comment by Conclure** [comment]
Read [here](https://fossils-archeology.fandom.com/wiki/Deinonychus). It's said that it will occasionally break both scratching posts and tethered logs. Read [here](https://fossils-archeology.fandom.com/wiki/Tethered_Log).

**Comment by B-Wither** [comment]
Oh now I noticed only raptor(Velociraptor and Deinonychus) breaks toy
