### ISSUE TITLE
Aquatic Dinos jump to their death

### ISSUE THREAD

**Issue by TheJN101** [FossilsArcheologyRevival/FossilsArcheologyRevival#1773]
Hey iam playing the new 8.0.4 and wanted to build an enclosure for my spino when it finally hatched it started jumping and taking damage until it died. Same with all water related dinos marine or amphibious they jump so high and bugged trough their aquarium ceelings.

pls fix and safe lives

**Comment by lindstheginj** [comment]
Are you playing with Lucraft Core? For some reason these mods are incompatible and it makes our aquatics bounce. Remove Lucraft and any dependent mods and the problem will go away.

**Comment by TheJN101** [comment]
Oh yes i do... thats sad my fav mods dont match... maybe one day they will
