### ISSUE TITLE
diplodocus breaks cultivators

### ISSUE THREAD

**Issue by PaxxXE** [FossilsArcheologyRevival/FossilsArcheologyRevival#1774]
i put diplodocus dna in a cultivator, and nothing was happening, so i replaced the cultivator with a new one, the dna went in but i couldn't put in any fuel. no matter how many times i replace the cultivator, it still won't work.

**Comment by lindstheginj** [comment]
Are you using bio-goo?

**Comment by PaxxXE** [comment]
no, i wasn't. thank you very much. i didn't know that the cultivators didnt accept things like beef and milk in the new update
