### ISSUE TITLE
Diplodocus Eternaly Sleeping, and geting up when it wants to.

### ISSUE THREAD

**Issue by dinosaurking999** [FossilsArcheologyRevival/FossilsArcheologyRevival#1776]
Ever since the diplodocus was introduced into this mod, i wanted to see what they were like so i tested it out in creative mode and spawned one in and for some reason after it sat down, and then proceded to fall asleep, and it wasn't even night time, so i came around to woundering that if this was intentional, or a form of behavior related bug, after a few weeks, it turned out to be a bug, so yeah i'm likely to not add diplodocus into my survival park any time soon until this bug is fixed. Has anyone else been having this issue, or is it just me?

**Comment by Conclure** [comment]
This is a known issue and it will most likely be patched in the next update. In the code it's said the Diplodocus should be able to go and sleep whenever it wants meaning it's not diurnal or nocturnal. But this feature was never really "implemented" what I've seen when looking into the code causing it to go and sleep immediately.
