### ISSUE TITLE
My game crashes on start (game wont load)

### ISSUE THREAD

**Issue by wkn311** [FossilsArcheologyRevival/FossilsArcheologyRevival#1785]
I have the 1.7.19 version of LLibrary and version 8.0.4 of Fossils, here is the crash log.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GSHooksLoader (GalaxySpace-1.12.2-2.0.13.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.5.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.1-core.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 5/27/20 8:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Midnight (midnight)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id -23, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.mushroom.midnight.common.registry.ModDimensions.register(ModDimensions.java:12)
	at com.mushroom.midnight.Midnight.preInit(Midnight.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6534686520 bytes (6231 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 5 total; -Xms7168m -Xmx7168m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                    | Signature                                |
	|:----- |:------------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                             | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                             | None                                     |
	| LCH   | FML                 | 8.0.99.99                | modpack.jar                               | None                                     |
	| LCH   | forge               | 14.23.5.2847             | modpack.jar                               | None                                     |
	| LCH   | micdoodlecore       |                          | minecraft.jar                             | None                                     |
	| LCH   | damageindicatorsmod | 1.0                      | [1.12.2]DamageIndicatorsMod-3.5.1.jar     | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |
	| LCH   | asmodeuscore        | 0.0.14                   | AsmodeusCore-1.12.2-0.0.14.jar            | None                                     |
	| LCH   | battletowers        | 1.6.5                    | BattleTowers-1.12.2.jar                   | None                                     |
	| LCH   | bettercaves         | 1.12.2                   | bettercaves-1.12.2-2.0.3.jar              | None                                     |
	| LCH   | forgelin            | 1.8.4                    | Forgelin-1.8.4.jar                        | None                                     |
	| LCH   | betterportals       | 0.3.7.7                  | betterportals-0.3.7.7.jar                 | None                                     |
	| LCH   | buildcraftlib       | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCH   | cfm                 | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                    | None                                     |
	| LCH   | customspawner       | 3.11.4                   | CustomMobSpawner-3.11.5.jar               | None                                     |
	| LCH   | mocreatures         | 12.0.5                   | DrZharksMoCreaturesMod-12.0.5.jar         | None                                     |
	| LCH   | llibrary            | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | fossil              | 8.0.4                    | fossilsarcheology-8.0.4.jar               | None                                     |
	| LCH   | galaxyspace         | 2.0.13                   | GalaxySpace-1.12.2-2.0.13.jar             | None                                     |
	| LCH   | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar               | None                                     |
	| LCH   | ichunutil           | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest           | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar           | None                                     |
	| LCH   | jei                 | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                 | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar               | None                                     |
	| LCH   | stevekung's_lib     | 1.1.5                    | SteveKunG's-Lib-1.12.2-1.1.5.jar          | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | moreplanets         | 2.1.12                   | More-Planets-1.12.2-2.1.12-GC251 (1).jar  | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | morph               | 7.2.0                    | Morph-1.12.2-7.2.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | mutantbeasts        | 1.12.2-0.7.2             | MutantBeasts-1.12.2-0.7.2.jar             | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LCH   | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar     | None                                     |
	| LCH   | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar     | None                                     |
	| LCH   | thebetweenlands     | 3.6.1                    | TheBetweenlands-3.6.1-universal.jar       | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCE   | midnight            | 0.3.5                    | themidnight-0.3.5.jar                     | None                                     |

	Loaded coremods (and transformers): 
GSHooksLoader (GalaxySpace-1.12.2-2.0.13.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.5.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Conclure** [comment]
That’s not F/A it’s an error with Midnight mod.

**Comment by wkn311** [comment]
How do I fix it?

**Comment by Conclure** [comment]
You may contact the devs of the Midnight mod as it seems to be an issue with their biome registry.

**Comment by wkn311** [comment]
ok thanks!

**Comment by Alex-the-666** [comment]
> Failed to register dimension for id -23, One is already registered
