### ISSUE TITLE
Dinos ignores feeders, Meganeura despawn, Mosasaurus cannot kill cows, Velociraptor stun-locks T.rex.

### ISSUE THREAD

**Issue by SpookyDilong316** [FossilsArcheologyRevival/FossilsArcheologyRevival#1797]
**Hello, here is some issues I encountered playing with the latest mod update:**

- Most of prehistoric mobs does not eat from feeders, they usually ignore them, some species eat and others not; maybe some carnivores like to prey on live animals and does not like feeders, I don't know about that.
Ornitholestes did not eat from the feeder. Deinonychus too, and did not attack other mobs to eat (uncertain).

- Some mobs like Mosasaurus chases other mobs like cows (and mobs from other mods) and get really close to them but they can't eat or damage them, although they do eat squid. No problem with Ichtyosaurus.

- I hatched a Meganeura once, it did not fly but remained standing still all the time as I remember, so I placed it right on the feeder to let it eat, and it did, then I went checking some time later and it disappeared.

- If Velociraptor attacks T.Rex, T.rex gets stuck while taking damage and cannot attack back.

- Every figurine drops Pristine Steve figurine when hit to collect.

**Did somebody else got these bugs too? Thanks for reading**

**Comment by ChaonicTheDeathKitten** [comment]
I didn't do extensive testing, but my Triceratops won't eat from the feeder.
So I haven't bothered with any other dinos.

**Comment by rauwebieten** [comment]
Having similar problems. 

About 50% of the dino species do not eat from the feeders. They ignore them, get hungry, get angry and die after a while.

My titanis doesn't eat from feeders, but also, it doesn't attack other dino's to eat.

Some dino species get stuck a lot of of the time:
- in landscape that is not completely flat
- next to the playing toys
- my brachiosauri "sink" into the ground

**Comment by Bolushi** [comment]
All raptors stunlock any dino, test it on mobs like the triceratops or even the sarcosuchus, they die quickly against raptors.

**Comment by lindstheginj** [comment]
Please remember that individual bugs should be reported separately. That allows us to close specific issues once they are fixed. We don’t have an efficient way of dealing with four bugs in one issue.
