### ISSUE TITLE
teen dinosaur with adult texture

### ISSUE THREAD

**Issue by gatoTop** [FossilsArcheologyRevival/FossilsArcheologyRevival#1798]
I recently saw a bug in the mod, when the dinosaur becomes young, the texture changes to adult, instead of staying with the young texture.This bug only happens with the triceratop and velociraptor deinonic stegosaurus

**Comment by gabrielnido** [comment]
eu acho q isso e normal

**Comment by Nargilis** [comment]
Eu acho que um biug
