### ISSUE TITLE
Tar slimes break screen when optifine is installed

### ISSUE THREAD

**Issue by ghost** [FossilsArcheologyRevival/FossilsArcheologyRevival#1801]
the title says it all when tar slimes are on the screen and Optifine has been installed the game breaks.

**Comment by lindstheginj** [comment]
What does “the game breaks” mean? Does it crash? If so, we need a crash report.

**Comment by hailsquidking** [comment]
The screen goes black, everything flashes red, GUI is gone...

This happens every time I have a tar slime near me and have optifine installed.

**Comment by lindstheginj** [comment]
What version of optifine are you using?
