### ISSUE TITLE
wont load into minecraft stuck on building terrain

### ISSUE THREAD

**Issue by thisiguess** [FossilsArcheologyRevival/FossilsArcheologyRevival#1805]
i have the right llibrary  and the newest version of the mod and it wont load i have no other mods and minecraft has enough memory.

**Comment by Gift-of-Names** [comment]
Could you post a log, please?

**Comment by thisiguess** [comment]
> Could you post a log, please?

??? it does not crash so i dont know where the log would be

**Comment by Gift-of-Names** [comment]
Same folder, should be a file named "latest"

**Comment by Gift-of-Names** [comment]
Or rather, should be in the "logs" folder
