### ISSUE TITLE
Dinopedia Is Broken

### ISSUE THREAD

**Issue by Tesseractt123** [FossilsArcheologyRevival/FossilsArcheologyRevival#1807]
This has probably happened before, however, for my dinopedia, every time I check a dinosaur, it says "Pregnant _______" and nothing else, any way to fix this? I run 1.12.2
![2020-08-09_20 53 25](https://user-images.githubusercontent.com/69441119/89745809-26d12380-da84-11ea-9280-ac521d1d11f3.png)

**Comment by lindstheginj** [comment]
Looks like you’re using an old version. This problem was fixed by 8.0.4.

**Comment by Tesseractt123** [comment]
Ok, thank you
