### ISSUE TITLE
Fish AI Server Lag

### ISSUE THREAD

**Issue by mxnmnm** [FossilsArcheologyRevival/FossilsArcheologyRevival#1813]
https://spark.lucko.me/#tMJu24r0hn

**Comment by mxnmnm** [comment]
Another one https://spark.lucko.me/#SoGnYpgCUW

**Comment by tyon2006** [comment]
If you drill down into that it looks like the fish's AI is causing chunk generation. If you pregen around the affected area, does it improve?
