### ISSUE TITLE
1.15.2??

### ISSUE THREAD

**Issue by AnonymousWolf1** [FossilsArcheologyRevival/FossilsArcheologyRevival#1830]
would you been able to do the mod to 1.15.2 version. this is the best mod i have played i would really love it to be for 1.15.2. if not its fine but it would be amazing if you could. thank you for reading

**Comment by lindstheginj** [comment]
Please do not use the ISSUE tracker for random questions. We use it to keep track of bugs we need to fix. A port will come eventually.
