### ISSUE TITLE
Mosasaurus constant starvation

### ISSUE THREAD

**Issue by youngstergaming** [FossilsArcheologyRevival/FossilsArcheologyRevival#1843]
So i was testing the breaching and the mosa just kept dieing on me so i gave it some food and cheaked the dinopad and its food never went up i also spawned a baby and same thing

**Comment by SoraTogaGaming** [comment]
Hi I have had this issue for a long time also I have just tried a few things and found out that if you go down to version fossilsarcheology-8.0.4.jar they will start eating again you might lost some stuff as they might of added some new things to the newest version but this will fix your issue hope this helps.
