### ISSUE TITLE
Incompatibility with ZAWA; Breaks Water Spawns

### ISSUE THREAD

**Issue by sable-king** [FossilsArcheologyRevival/FossilsArcheologyRevival#1844]
Pretty much the title. When F&A is used in conjunction with Zoo And Wild Animals, in bodies of water, only the water creatures from F&A will spawn. Even the Squid spawns break.

**Comment by JoelZBub** [comment]
This is a worthless report. 
Add version numbers at the very least. sheesh

**Comment by accountforcommenting23** [comment]
I also have the same problem. When I load (ocean biomes) chunks by flying/walking in game, it only spawns F/A and Ice&Fire mobs. It only spawns ZAWA mobs when I relog (and it only spawns them in the first few chunks I can see). Squid also don't spawn unless I relog. F/A version 1.12.2 - 8.0.5 and ZAWA version 1.12.2 - 2.1.1
I don't know if I should have replied here or opened a new issue

**Comment by Uwanami** [comment]
I have same problem - only nautilus spawn - I tried to disable it in the config and change rarity to max but doesn't work. Actually nothing spawn in the ocean except nautilus and guardians from vanilla - any other aquatic vanilla or modded don't spawn (no fish or squid from vanilla, mod Aquaculture 2 doesn't spawn anything as well).
Fossil ver. 8.0.5
ZAWA ver. 2.1.3
