### ISSUE TITLE
I cant Install forge

### ISSUE THREAD

**Issue by Crooook** [FossilsArcheologyRevival/FossilsArcheologyRevival#1846]
Due to the instructions it asks me to install Forge, however when I try to it wont open properly

**Comment by lindstheginj** [comment]
What does this mean? Is it crashing? If so, we need a crash report in order to help.

**Comment by Crooook** [comment]
I install forge and then it asks me how I'd like to open it instead of just heading straight to the install options. No matter how I open it Forge itself wont open.

**Comment by lindstheginj** [comment]
I’m closing this because it is not a mod issue. I’ll try to help as best as I can, though. What happens when you open Minecraft?

**Comment by Crooook** [comment]
Its nothing to do with Minecraft, its Forge itself, when I've downloaded the files it asks me how I want to open it, no matter how I choose to open it I cant access the install options

**Comment by lindstheginj** [comment]
Could you post a screenshot of what you’re clicking on on the Forge website?

**Comment by Crooook** [comment]
Its not on the Forge website, I've downloaded the files from forge but as I've downloaded the files I need to open the installer to install it. When I go to open it, it asks how I want to open it, no matter how I open it, it just opens the files, not the installer

**Comment by lindstheginj** [comment]
Please show me where you are downloading them from.

**Comment by Crooook** [comment]
https://files.minecraftforge.net/

**Comment by lindstheginj** [comment]
![B49F6E94-9E98-4446-93F9-8BE97614EFA3](https://user-images.githubusercontent.com/15497127/105187600-f399c280-5b00-11eb-9f50-6fee7b3d29ec.jpeg)
This is what you are clicking on, correct? Nothing else?

**Comment by Crooook** [comment]
correct

**Comment by lindstheginj** [comment]
Is there a chance that your antivirus software is getting in the way?

**Comment by Crooook** [comment]
possibly
