### ISSUE TITLE
mosasaur eat and not fill hunger

### ISSUE THREAD

**Issue by gabrielnido** [FossilsArcheologyRevival/FossilsArcheologyRevival#1848]
I give him food and nothing works

**Comment by SoraTogaGaming** [comment]
Hi I have had this issue for a long time also I have just tried a few things and found out that if you go down to version fossilsarcheology-8.0.4.jar they will start eating again you might lost some stuff as they might of added some new things to the newest version but this will fix your issue hope this helps.
