### ISSUE TITLE
Mosasaur hunger bar doesn't fill up

### ISSUE THREAD

**Issue by accountforcommenting23** [FossilsArcheologyRevival/FossilsArcheologyRevival#1854]
Version: 1.12.2 / 8.0.5
I filled up a feeder until its maximum capacity and spawned my mosasaur sac. It began to eat but I noticed it took a really long time so I checked its status and it was still at hunger: 1/125 even though it had already "eaten" half of the food in the feeder.

**Comment by SoraTogaGaming** [comment]
Hi I have had this issue for a long time also I have just tried a few things and found out that if you go down to version fossilsarcheology-8.0.4.jar they will start eating again you might lost some stuff as they might of added some new things to the newest version but this will fix your issue hope this helps.
