### ISSUE TITLE
Mosasaur constant 1/125 hunger and bad mood

### ISSUE THREAD

**Issue by badavis77** [FossilsArcheologyRevival/FossilsArcheologyRevival#1855]
When I spawned in the mosasaur first it was hostile and starving. No matter how much food it eats or how much it hunts it always remained hungry and in a bad mood. Setting dino starvation off in config does nothing and the balls or tethered log do nothing to help.

**Comment by SoraTogaGaming** [comment]
Hi I have had this issue for a long time also I have just tried a few things and found out that if you go down to version fossilsarcheology-8.0.4.jar they will start eating again you might lost some stuff as they might of added some new things to the newest version but this will fix your issue hope this helps.
