### ISSUE TITLE
mod doesn´t work at all

### ISSUE THREAD

**Issue by JoStorys** [FossilsArcheologyRevival/FossilsArcheologyRevival#1857]
Hello,
I´ve tried so many different sites (and mod packs) and this mod just won´t work. A similar mod does work, but this one doesn´t. This is the fifth website I´ve tried to download and play this mod. I´ve tried three different "launcher" thingys that are normally able to run the mods. 
This is my last try, if no one has an idea what the issue might be, then I won´t try downloading this mod again. Which is really sad since this is by far my favourite dinosaur mod.
I really hope you can help me, thank you for reading!

**Comment by MartiRex** [comment]
have you installed llibrary and forge 1.12.2?

**Comment by JoStorys** [comment]
Yes, I have. But I found a modpack that seems to work a few minutes ago. 
Thank you very much for your time ^^
