### ISSUE TITLE
Plesiosaur AI Bugged

### ISSUE THREAD

**Issue by GalacticNarwhal** [FossilsArcheologyRevival/FossilsArcheologyRevival#1860]
My Plesiosaur keeps returning to the same corner of his enclosure no matter what I try to do. I've used a lead to bring it out, it just swims right back. I've killed it and replaced it, and that worked for a bit, but after a while, it just went right back. I broke blocks around it to see if it was stuck, but it just kept swimming in the same place. Thankfully, it doesn't seem like he'll starve as a result, since it seems like he's still eating, but it's still pretty annoying. (Note, the enclosure is much bigger than that, it's in a U shape)
![2021-04-12_16 52 01](https://user-images.githubusercontent.com/40198984/114499844-c595bd00-9bdb-11eb-96fc-febb88fc2416.png)

**Comment by Rattlesnake551** [comment]
a lot of mobs are having this issue too with me, like sometimes my Tiktaalik
