### ISSUE TITLE
Dinosaurs not eating out of feeders in the enclosures 

### ISSUE THREAD

**Issue by Baylorj99** [FossilsArcheologyRevival/FossilsArcheologyRevival#1870]
So I have this problem and idk if others do too, but as of rn some of my dinosaurs don’t eat out of their feeders that are included in the enclosure but some do and I dunno why cuz there is nothing blocking the feeders and they just don’t eat them eventually get hungry and sad which annoys me because I made the feeders for a reason.

**Comment by ohyeahboieatmyfeijoada** [comment]
Well, some dinosaurs just don't eat from feeders. No idea why they made it that way, but... I  guess that's the devs fault?...
