### ISSUE TITLE
Suggestion - Breeding update

### ISSUE THREAD

**Issue by M4tss** [FossilsArcheologyRevival/FossilsArcheologyRevival#1874]
My suggestion, is that a system like max per chunk is added. example my raptor cage is in 4 chunks, and the raptor species has a 3 per chunk ratio.
Theres 3 raptors in one chunk. and the male and female raptor that were about to breed. wont, the 5 minute timer resets.

The next timer runs out, and they try to breed again. The other raptor left the chunk and its only them two. because its a 3-per-chunk for raptors, they will breed. 

This would vary for each species, example, confusciuros can have 15-per-chunk, because of their size.

Thank you! M4tss

**Comment by ohyeahboieatmyfeijoada** [comment]
How does that make sense?

**Comment by M4tss** [comment]
Babies can still be born, but they won't always, because sometimes there is a max per chunk. in the wild you wouldn't have a family off 300 pternadons aswell.
