### ISSUE TITLE
Mosasaurus literally starving to death

### ISSUE THREAD

**Issue by SantaBoy21** [FossilsArcheologyRevival/FossilsArcheologyRevival#1884]
in vr 8.0.5, Mosaurus spawns in already with its food very dangerously low and not full like all the others mobs and feeding the mosasaur would not fill up its hunger so it constantly keeps eating and still starving. I'm not sure whats wrong with it, all the others mobs are normal except for the mosa.

**Comment by LucarioRanger** [comment]
Same here. They spawn in at 1 food, and will never gain any no matter how much I feed it. Plus it seems you can't tame them anymore, because whenever I try to attack fully grown ones to make them go to sleep mode and use Aquatic Scarab gem on them, they just die
