### ISSUE TITLE
My dinosaurs are jumping up and down until they die from fall damage.

### ISSUE THREAD

**Issue by Cetoz8992** [FossilsArcheologyRevival/FossilsArcheologyRevival#1892]
3 dead Spinosaurus, 1 dead Liopleurodon. My Plesiosaurus is currently jumping, so I have it on stay. Version 1.12.2. The rest (Tyrannosaurus, Gallimimus, Velociraptor, Deliophosaurus, Compsognathus, Dryosaurus, Ankylosaurus) are fine.

Edit: Forgot about my recent additions, and one of my Henodus just died from jumping until it dies from fall damage like the rest. Currently awaiting the death of my other Henodus.

**Comment by lindstheginj** [comment]
This sounds like a conflict with LuCraft Core. It is a known issue. It only occurs w aquatic creatures. If you uninstall Lucraft core it should stop.

**Comment by Cetoz8992** [comment]
Alright. Thank you.

**Comment by lindstheginj** [comment]
#1226
