### ISSUE TITLE
It's imcopatible with epic siege mod

### ISSUE THREAD

**Issue by rebarakuk** [FossilsArcheologyRevival/FossilsArcheologyRevival#1896]
when installed with epic siege, entities frequently freeze

**Comment by Sunconure11** [comment]
Nothing that can be done here, as ESM is closed source

**Comment by rebarakuk** [comment]
OMG....

**Comment by rebarakuk** [comment]
Now I know, these 2 mods make tick problem. When I installed tickrate changer which synchronizes tickrates between server and cilent, entities move well.
