### ISSUE TITLE
Tinkers tools interacting with mod and causing server crash.

### ISSUE THREAD

**Issue by CatSongCrimson** [FossilsArcheologyRevival/FossilsArcheologyRevival#1902]
According to someone helping me, the mods are messing up by somehow returning -14 for an array element call 
Heres a pastebin to the most recent crash report.

https://pastebin.com/Aug3awCX

This has happened several times, and none of the tools used (a pickaxe and a shovel) have fossils archeology modifiers as a part of their modifiers and enhancements.

**Comment by brisingraerowing** [comment]
[Failing Line](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/blob/1.12.2/src/main/java/fossilsarcheology/server/compat/tinkers/ModifierArcheology.java#L51). I think the `indexOf` call needs to be checked for invalid return values.
