### ISSUE TITLE
InControl mod mobs incombaility 

### ISSUE THREAD

**Issue by GASPOUR** [FossilsArcheologyRevival/FossilsArcheologyRevival#1908]
the InControl mod is used by modpack creator to control mob spawning and i've recently try to use it to spawn mobs from F/A to another mod dimension and i didn't make any error but most mobs won't spawn only nautilus and alligator gar spawn and i guess it's because they can spawn in overworld if you put that in the config file, i've talked to the InControl creator and it really looks like it's an incomptability due to the way dinosaurs spawn is done, i don't really know what's the exact cause with that but that's an issue that could be really awesome to solve

**Comment by AechtRob** [comment]
Hi - I'm not a dev for FA, but I have used InControl extensively with FA and it really does all work just fine to spawn mobs anywhere you like (apart from in water, which InControl doesn't enable). You must be doing something wrong. I cant see anything on McJty's own discord about this issue recently, where was the conversation and attempts to fix it?

If you ping me on the InControl part of the McJty discord I am happy to help you over there tho? (Aecht_Rob)
