### ISSUE TITLE
Animals stuck pathing to enrichment items, starve to death.

### ISSUE THREAD

**Issue by ChristianBraswell** [FossilsArcheologyRevival/FossilsArcheologyRevival#1910]
I've noticed a bug where the animals will attempt to go towards a scratching post/ball/log and get caught on a block and are unable to navigate around it. This leads them to starve to death because they do not eat when attempting to path to the toy. The only way of fixing it is to break the toy, after which their pathing seems to fix itself. Is this a known bug?

**Comment by brandon7711** [comment]
B
