### ISSUE TITLE
SEVERE Performance Issues when mod is installed

### ISSUE THREAD

**Issue by Pseudonomenclature** [FossilsArcheologyRevival/FossilsArcheologyRevival#1913]
Simply having this mod installed causes severe performance issues. And I know it is this mod, because uninstalling it resolves all issues. I have a total of 113 mods installed besides this one, and none of them cause this sort of problem. I have disabled all world generation in this mod's config but it has had no beneficial effect.

I am using v8.0.5 of the mod for Minecraft 1.12.2, playing singleplayer.

When I say 'Performance Issues', I mean the following:
- The entire world — except for the player — freezes on world load, and stays that way perpetually.
- Chunks stop being loaded, and you can walk off the edge of the world and get stuck there.
- Entities and mobs stop moving, and take several seconds to respond after you hit them.
- Drinkable and edible items become impossible to consume (you can hold down right-click for as long as you want but it's never going to finish the animation / sound effect).
- Picking up and dropping items becomes extremely unresponsive, taking several seconds for anything to happen when you press the drop key or try to pick anything up.
- Probably more...

I can install several other mods which add more content and world gen etc. than this mod, but it will not cause any of these issues. It is only this mod that seems to cause this stuff to happen.

And it's not while doing anything specific to the mod either, or generating anything specific to the mod (as I said, I've disabled all of its world gen). Just having it installed instantly dumps performance significantly.

ALSO: This even seems to happen if I more or less ONLY have this mod installed, after uninstalling all other content mods.

Any idea what the issue could be, and how to fix it?

**Comment by Fluffy9911** [comment]
Can you post your log? (.minecraft/logs/latest_log), that may help fix the issue.

**Comment by Pseudonomenclature** [comment]
> Can you post your log? (.minecraft/logs/latest_log), that may help fix the issue.

Do you mean the entire log or just the parts between me entering the world and me disconnecting?
Because here's that log: 
[latest.log](https://gist.github.com/Pseudonomenclature/d6d8fcb6767b2ae528df13e4f76a757f)

(This is after I've disabled more or less every other content mod in the pack)

Pretty telling line:
`[08:55:35] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2472ms behind, skipping 49 tick(s)`

**Comment by aglarcz** [comment]
"Changing view distance to 16, from 10" from your log. 

Try lowering it to 6 or 4. More is just unreasonable and likely causes your modpack to crash.

**Comment by Pseudonomenclature** [comment]
> "Changing view distance to 16, from 10" from your log.
> 
> Try lowering it to 6 or 4. More is just unreasonable and likely causes your modpack to crash.

It doesn't cause any issues at all in my 100+ mods modpacks. Only when Fossils & Archeology is installed.

**Comment by rebarakuk** [comment]
epic siege mod and fossils and archaeology makes tps drop

delete one of them and I already posted this issue, but Sunconure11 said like this

#1896

**Comment by rebarakuk** [comment]
> epic siege mod and fossils and archaeology makes tps drop
> 
> delete one of them and I already posted this issue, but Sunconure11 said like this
> 
> #1896

Also, I tried epic siege 13.167, 13.169, 13.159 but they all made tps drop
