### ISSUE TITLE
A date for the release ?

### ISSUE THREAD

**Issue by JLSkyzer** [FossilsArcheologyRevival/FossilsArcheologyRevival#1921]
Hello, do you have a date for the 1.16.5 release ?

**Comment by Sunconure11** [comment]
No. However, an announcement for some news will come later in the day. Check #announcements, when it does happen.

**Comment by JLSkyzer** [comment]
can you send the discord please ?

**Comment by Sunconure11** [comment]
https://discord.gg/yWa7ZSe7
