### ISSUE TITLE
Thaumcraft Aspects are missing from items.

### ISSUE THREAD

**Issue by Handeril** [FossilsArcheologyRevival/FossilsArcheologyRevival#1929]
I will note that I'm using Thaumic Speedup if that effects anything in any major way, however...

The issue is that the Thaumcraft Aspects added by Fossils & Archaeology Revival appear to be missing any items that have those aspects. Interestingly enough, this mostly hurts research while the mod is installed, as I've encountered many times in which the research asked me to "Channel x Essentia" or "Concentrate" on a currently-unobtainable aspect from Fossils & Archaeology.

**Comment by Sunconure11** [comment]
1.12 is no longer supported, and TC support would likely not come back when the port happens, due to too many changes in the game, and TC being abandonware.
