### ISSUE TITLE
Natural enemies are "friends"

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheologyRevival#416]
While I do admit that the picture attached is pretty cute, I'm pretty sure that the Dilophosaurus and Stegosaurus - both from the Jurassic, should've beat the crap out of each other, but instead they fell asleep at the same time. Amazingly close...

![2016-07-12_16 27 12](https://cloud.githubusercontent.com/assets/16602481/16898965/a21924bc-4bb7-11e6-8c4d-0dfe9d319448.png)
Picture is kinda cute though, right? ;)

**Comment by PCAwesomeness** [comment]
If Allosaurus happens to fail at hunting Stegosaurus every time it tries, I don't think Dilophosaurus would be willing to do so, either.

**Comment by Alex-the-666** [comment]
1. Dilophosaurus isn't hungry. It isn't some sort of killing machine from Jurassic Park
2. Dilophosaurus can judge that it could never win a fight against a creature twice it's size.
3. Stegosaurus is wary but knows the Dilophosaurus won't attack it.
4. They are all sleeping. Animals don't try and kill each other in their sleep.

**Comment by crakiMDH** [comment]
So... I can have Dilophosaurus pens and Stegosaurus pens right next to each other? Also, what animals DO the Dilos and Allos hunt if it isn't Stegosaurus or (obviously) Brachiosaurus?

**Comment by Alex-the-666** [comment]
Anything smaller than themselves.
