### ISSUE TITLE
Config glitch with Llibrary

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheologyRevival#419]
I was playing with 7.3.1, and I deleted my config just to make sure I can safely transition from 7.3.0 to 7.3.1. But I saw that the config was blank. I then switched to Llibrary 1.4.1, because I had updated Llibrary to 1.4.2. The config regenerated when it was deleted and the 7.3.0 was run with Llibrary 1.4.1. This means that Llibrary must prevent config from generating in its 1.4.2 release.

**Comment by crakiMDH** [comment]
Will Llibrary update so 1.4.3 or something to fix the glitch?

**Comment by iLexiconn** [comment]
"what? Maybe the download got corrupted try again. " - @4f6f3b

**Comment by crakiMDH** [comment]
So I need to download 7.3.1 again?

**Comment by iLexiconn** [comment]
Download LLibrary 1.4.2 again ;)

**Comment by crakiMDH** [comment]
oh OK!
Mind if I ask what Llibrary does? I'm curious to know ;D

**Comment by crakiMDH** [comment]
It says that the download for Llibrary 1.4.2 the page was not found

**Comment by iLexiconn** [comment]
Renders the models, handles the config, handles the animations, handles the packets, it does a lot

**Comment by iLexiconn** [comment]
It's not yet approved, wait 5 more mins

**Comment by crakiMDH** [comment]
OK! If it works and it actually makes config work and the dinosaurs no longer sit down when relogging, then I hope the server updates!

**Comment by iLexiconn** [comment]
> the dinosaurs no longer sit down when relogging
That's not LLibrary's fault :P

**Comment by crakiMDH** [comment]
Where did you get that info?
that they don't sit down when relogging?

**Comment by iLexiconn** [comment]
I didn't say they don't, I'm just saying that LLibrary doesn't cause that error. That's all F/A.

**Comment by crakiMDH** [comment]
But it says "the dinosaurs no longer sit down when relogging" **No longer** sit down.

**Comment by iLexiconn** [comment]
I'm confused

**Comment by crakiMDH** [comment]
You said that dinos no longer sit down when relogging! It looks copied and pasted, where did you get that info? BTW the Llibrary download in curse forge is still not available

**Comment by iLexiconn** [comment]
You said it yourself...
> OK! If it works and it actually makes config work and the dinosaurs no longer sit down when relogging, then I hope the server updates!

And you can download it here: http://minecraft.curseforge.com/projects/llibrary/files/2316760

**Comment by crakiMDH** [comment]
oh... OK... I'm guessing this new Llibrary is the "non-corrupted" one I'm guessing.
Thanks for the link BTW

**Comment by crakiMDH** [comment]
OMG it works! Thanks! Now, I can make my own survival stuff! As long as I tame my dinos i guess the sitting in relog thing won't bother me so much.

**Comment by iLexiconn** [comment]
"[01:21:01] Alenthe777: no
[01:21:07] Alenthe777: just means hunger wont go down
[01:21:13] Alenthe777: so one there at full hunger rip"
