### ISSUE TITLE
Therizinosaurus Skeleton

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheologyRevival#420]
I was playing around with the Therizinosaurus, and then I realized that the skeleton model had the living animation. This issue isn't present with the Parasaurolophus and Dryosaurus models

**Comment by Sunconure11** [comment]
Fixed by https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/b7e1ce771b94053cab0ac17a9e75578e94d8d862

**Comment by iLexiconn** [comment]
how is it invalid if it got fixed?
