### ISSUE TITLE
Mobs on stay upon relog

### ISSUE THREAD

**Issue by crakiMDH** [FossilsArcheologyRevival/FossilsArcheologyRevival#421]
When I relogged, all mobs of F/A where on the stay command, even though they were untamed. The only way to solve this problem, is to tame them and set their command to wander or follow.

**Comment by crakiMDH** [comment]
By the way, I've seen that this happens with mobs when you leave the chunk they are in and the chunk degenerates.

**Comment by Sunconure11** [comment]
Encountering the same issue too, and I used biometweaker to set a few to spawn naturally. They too are affected by this.

**Comment by crakiMDH** [comment]
I'm surprised that this issue came like 20 minutes after the release of 7.3.1. And so far, I'm not seeing anyone assigned to it. Poetplays reported a bug, and suddenly someone goes to fix it.

**Comment by iLexiconn** [comment]
Did you look at the issues page? There are a lot of bugs for us to fix.

**Comment by crakiMDH** [comment]
I'm saying this was one of the first issues reported. It wasn't fixed. But the later issues where fixed. Just pointing it out :P
