### ISSUE TITLE
Buggy oredictionary and noodle-legged elasmotheriums

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#422]
Many mobs do not recognize foods added via oredictionaries, only a few are recognized. Very few even appear in the dinopedia, and most animals will not take them.

Possible suggestion to get said items to appear in the dinopedia: Allow new food pages to be added depending on what mods with registered oredictionary food items you have.

Examples of foods not appearing in the dinopedia: (I have harvestcraft installed, so more should appear than this) https://www.dropbox.com/s/cyb3y3utbngqtcx/Screenshot%202016-07-17%2021.07.48.png?dl=0

https://www.dropbox.com/s/3l9iryidwohn7zt/Screenshot%202016-07-17%2022.47.23.png?dl=0 (They'll take EBXL strawberries, but not harvestcraft ones.)

Also, elasmotheriums have an incredibly odd running gait. Their legs spaz out as if they were made of noodles.

Edit 1: Items with metadata can be consumed, but won't show up in the dinopedia. A lot of the raw resources such as Yuzu in AMT2 use metadata, and yet only raw tea leaves will show up in the dinopedia. Same deal goes for BoP foods. Also, they will eat foods in such a system that do not have oredictionary definitions registered in this mod, such as Ambrosia from BoP, because their parent item (berries) have a definition registered by this mod.

Edit 2: Noodly elasmotheriums:

https://www.dropbox.com/s/pjrxv5q04dp2mw7/Screenshot%202016-07-18%2003.01.49.png?dl=0

**Comment by Sunconure11** [comment]
Is there anything that can be done about the described derpiness with oredictionary definitions?

Also when my computer is fixed, I plan to add definitions based on Forestry.

**Comment by Sunconure11** [comment]
It appears some items simply show up as unknown in the dinopedia.

https://www.dropbox.com/s/gqi0854t9ehkl39/Screenshot%202016-07-22%2014.16.11.png?dl=0

I installed Forestry in this instance to harvest oredictionary definitions

**Comment by Alex-the-666** [comment]
^ is because another mod, registered to the oredict, is a blank item, a "item.null.name" if you must. not our fault.
