### ISSUE TITLE
Pregnant mobs lose child when chunks unload

### ISSUE THREAD

**Issue by PoetPlays** [FossilsArcheologyRevival/FossilsArcheologyRevival#427]
I experienced an issue where if you impregnate a mob (pig, cow) with a mammoth or smilodon, etc, mob embryo then walk out of render distance to unload the chunk, when you go back to the "mother" it does not have a baby gestating inside of it.

This can also be reproduced by simply logging out and back in (which unloads chunks).

I tested with both pig and cow mother types, and with both mammoth and smilodon child types. Same issue occurs.

World was generated pre 7.3.1.

**Comment by Alex-the-666** [comment]
Fossils Version? 7.2, 7.3, 7.3.1?

**Comment by PoetPlays** [comment]
Sorry, typo. Meant pre- 7.3.1. Version is updated to the latest 7.3.1

**Comment by Alex-the-666** [comment]
Ok.
