### ISSUE TITLE
Skeletons grow

### ISSUE THREAD

**Issue by smallpred** [FossilsArcheologyRevival/FossilsArcheologyRevival#432]
they grow like a living thing i've noticed this with the mammoth,cerato and dilo fossils

**Comment by lindstheginj** [comment]
What do you mean? Like after a few days, they're noticeably bigger?

**Comment by smallpred** [comment]
Yea

**Comment by smallpred** [comment]
Especially if you restart the server, I had the skeletons with no bones and when I came back on the Cerato was at max height

**Comment by PoetPlays** [comment]
Confirmed this with Carno skeleton also. Suddenly the skeleton is huge, however it seems to be growing much faster than the actual dinosaurs in the same loaded chunks as the dinosaurs in the surrounding areas are only 3-5 days old, yet the skeleton is max size.

**Comment by crakiMDH** [comment]
Poet... Carno skeleton? You mean Allosaurus! xD
