### ISSUE TITLE
block and item textures messed up for some items

### ISSUE THREAD

**Issue by Archosaur1** [FossilsArcheologyRevival/FossilsArcheologyRevival#433]
i only have Llibrary and fossil archeology installed and if i remove fossil archeology and just run Minecraft with Llibrary the textures are still messed up. some textures completely disappear and others turn into fuzzy squares how can i fix this

**Comment by lindstheginj** [comment]
can you tell us some of the textures you're having trouble with?

**Comment by iLexiconn** [comment]
Disable the splash screen
