### ISSUE TITLE
T.rex taming glitch

### ISSUE THREAD

**Issue by PoetPlays** [FossilsArcheologyRevival/FossilsArcheologyRevival#435]
A tamed t.rex does not seem to react whatsoever to a skull stick order. No dialog is given in the chat area, and the t.rex does not follow, stay, etc, regardless. Other order items such as the regular stick and bone do nothing also, for experiment's sake.

A tamed t.rex appears to go into Stay command (sitting) and does not move from that point forward.

Of course I know that the ordering of dinosaurs is relatively buggy right now but this particular issue only seems to affect the t.rex.

v. 7.3.1

**Comment by PinkSalamander** [comment]
I also have this exact problem

**Comment by 4f6f3b** [comment]
Fresh world with a newly spawned/tamed tyrannosaurus; skull stick works for me. Is this a pre 7.3 t.rex/skull stick?

**Comment by PoetPlays** [comment]
Pre-7.3 world, but the t.rex was hatched (not spawned) and new skull stick spawned in, still no control.

It could be that the t.rex was just too young, however, since now that it is 12 days old I can control it. So despite it being "tamed" and having an order item, it appears that younger t.rex can't be controlled? The problem fixed itself as the t.rex aged.

However, this still feels like a bug. If a t.rex can be tamed at all, you should be able to control it, unless the idea is that it CANNOT be tamed until it's older.

**Comment by 4f6f3b** [comment]
It's not possible to gem-tame a t.rex before it is 12 years old so you shouldn't be able to control/tame a younger t.rex anyways, and in my testing everything is working correctly.

Was this t.rex updated from pre-7.3 that was already tamed with its age reset to 0? This is the only reason I can think of that you'd see this happen, and if that's the case it's a one-off quirk from updating from pre-7.3.

**Comment by PoetPlays** [comment]
No, the t.rex was tamed via feeding it when it was young, new from a hatchling in 7.3.1. No gem taming was done at all.

**Comment by PoetPlays** [comment]
I made a video detailing replication of this taming glitch. Infant t.rex should not be able to be tamed via feeding (ie: the usual way).

https://youtu.be/eFI8RHQ6N_8

This shows both taming in the usual way, and taming the incorrect way.
However, it should again be noted that the skull stick DOES start working once you've logged back out and in again. This glitch therefore circumvents scarab gem taming.
