### ISSUE TITLE
Sifter not consuming materials when looking inside them

### ISSUE THREAD

**Issue by JacobP12** [FossilsArcheologyRevival/FossilsArcheologyRevival#440]
When im sifting dirt sand or gravel and right click the sifter to view whats inside the sifter will look like its still working but wont consume or output any materials this video shows it better then i can explain it 

https://www.youtube.com/watch?v=F4mlW3vDM_Y

**Comment by 4f6f3b** [comment]
Sifter isn't consuming input block if it fails to drop loot.
