### ISSUE TITLE
Dinos breeding despite config

### ISSUE THREAD

**Issue by PoetPlays** [FossilsArcheologyRevival/FossilsArcheologyRevival#441]
I have noticed velociraptors laying eggs when they "go near" other raptors. 

SUDDENLY Whitney Houston's "I will always love you" starts playing around the raptors. This is bad... I mean it's super funny, but I personally can't have copyrighted music suddenly start playing for any reason.

Either way, it shouldn't be happening because breeding was supposed to be turned off.

I double-checked config to make sure breeding was turned off.
I can't be certain that it only affects raptors, but it has affected raptors for sure in my case. It's hard to tell what other dinos it affects so far because of the "all female" glitch going on with previously spawned in dinos.

**Comment by iLexiconn** [comment]
Update to LLibrary 1.4.2

**Comment by PoetPlays** [comment]
I do have LLibrary 1.4.2......

**Comment by iLexiconn** [comment]
Uh.. if the update doesn't fix it there's another issue, I'll reopen it.

**Comment by 4f6f3b** [comment]
Fixed in 6672fdca0a6a029a2144ca6a695159f5d5ae72a0

**Comment by crakiMDH** [comment]
Poet, you can fix this by making sure all dinos in the paddock are only one gender! xD

**Comment by iLexiconn** [comment]
that's not a fix
