### ISSUE TITLE
gastornis is a herbivore while the other terror birds are carnivores

### ISSUE THREAD

**Issue by Thedinotamer** [FossilsArcheologyRevival/FossilsArcheologyRevival#442]
i´ve researched so i wouldn´t write a non problem but i can´t find anything good so i´m going with my own knowledge and i don´t think it´s supposed to be like this :)

**Comment by lindstheginj** [comment]
Gastornis is a herbivore.

**Comment by Thedinotamer** [comment]
ohhhhh... sorry :D
