### ISSUE TITLE
Fossil come to life

### ISSUE THREAD

**Issue by Sanesinceyear2002** [FossilsArcheologyRevival/FossilsArcheologyRevival#445]
Fossils both tar and bio come to life when hitted with snowball. P.s. Therizinosaurus fossils seems to be alive without any snowballs.

**Comment by Sunconure11** [comment]
Therizinosaur issue was fixed a while back, as well as many other issues relating to fossils.

**Comment by Sanesinceyear2002** [comment]
No they  are not fixed.

**Comment by iLexiconn** [comment]
They are, just not in the current release
