### ISSUE TITLE
Javelin durability

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#450]
Both the code and the wiki say wooden javelins should only have 5 uses, but I've fired mine about 64 times now.

**Comment by iLexiconn** [comment]
the code says 40

**Comment by lindstheginj** [comment]
Well then, it's still wrong... And someone needs to help me find the corret durability for all the types then bc I obviously can't read code and no one helped me when I asked :$
