### ISSUE TITLE
Twitter bug dump

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#466]
"ALERT!: new update breaks the game! Eating, zombies don't die with all the weapons give 1 damage, need another update!!!"
"there is ANOTHER problem. Dinos move like 1 foot per hour."
"ANOTHER one! Flying dinosaurs sometimes don't play flying animation"
-@bahayazici5
Apparently doesn't have any other mods installed, but I can't recreate ANY of these bugs

**Comment by Alex-the-666** [comment]
If they are un-recreateable, and there is no evidence, then it is not valid

**Comment by crakiMDH** [comment]
Let me help:
1. Zombies don't die? There are so many kinds of zombies in the game, clearly made up. (Zombie, zombie pigman, sentry pigman (technically a zombie)
2. Dinos move one foot per hour? How does he know they move only one foot, if the only thing in MC we know the length and height of are blocks, 1 meter long. It could also be his computer has a lot of lag.
3. Pterosaurs, not flying dinosaurs. Most likely saw the bug in 7.3 or 7.3.1 and ended up reporting it alongside the 7.3.2 bugs. If they even are bugs. Also, I think the Pteranodon one is more of a leave-chunk-to-fix sort of bug. If Pteranodons try to fly, succeed, but then come across terrain that makes them land too many times, they may not play the flying animation but will still attempt to fly. Hope this helped!
