### ISSUE TITLE
Archaeology Workbench recipe not working

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#482]
I can craft the bench perfectly fine, but for some reason I have heard a handful of reports that the recipe doesn't work (no other mods installed, all other recipes are fine).

**Comment by iLexiconn** [comment]
if you can craft it everyone can

**Comment by Brownie2002** [comment]
I cannot craft it on my side ...
 fossilsarcheology-7.3.2.jar
