### ISSUE TITLE
Baby sarco has same death roll range as adult

### ISSUE THREAD

**Issue by ItsTimeToStop** [FossilsArcheologyRevival/FossilsArcheologyRevival#484]
I'm not sure if you're already aware of this but baby sarcosuchus can death roll you from like 7 blocks away (its hit range for it is as big as adult) and it's really annoying since that means a baby can pick you up from like 3 blocks above it in my viewing platform

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
