### ISSUE TITLE
Eggs only spawn female creatures

### ISSUE THREAD

**Issue by Microraptors4Life** [FossilsArcheologyRevival/FossilsArcheologyRevival#486]
Titanis, Dodos, Confuciusornis, etc.
Whenever you throw the eggs at the ground near you, the animal might not be tamed, and it's always a female. It's never a male. I tested out in survival, and getting it genuinely but still only females came out of the eggs. I tried in creative mode, and I just got a bunch of baby females. Please fix this if/when you can!
Thank you for your time.
P.S.
Maybe add a microraptor zhaoianus? x3

**Comment by lindstheginj** [comment]
Are you in 7.3.1 or 7.3.2? Also, pls don't make suggestions here

**Comment by Microraptors4Life** [comment]
I apologize. I was recently in 7.3.1, but it was fixed in 7.3.2. Thank you for the reply :)
