### ISSUE TITLE
Spinosarus Path Finding Error? 

### ISSUE THREAD

**Issue by ShadowLink2016** [FossilsArcheologyRevival/FossilsArcheologyRevival#487]
I'm not really sure if this is a problem or not, but the Spinosaurus seems to not be able to leave a body of water after it has gotten into one. It's as if it's not in their path finding to be able to climb out of the water. Like I said, I don't know if this is a problem, just wanted to point it out. 
![2016-09-01_17 32 43](https://cloud.githubusercontent.com/assets/21695110/18185628/9575d6fe-706c-11e6-8cef-164cf0ecccc4.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
