### ISSUE TITLE
Tethered Log (Toy) Buggy

### ISSUE THREAD

**Issue by ArielAndDaniel** [FossilsArcheologyRevival/FossilsArcheologyRevival#489]
Well, I have 2 Ankylosaurus in an enclosure and I have one Tethered Log for them to share. And always when I give the enclosure a check, the log seems to turn into a black color and seems to constantly swing back and forth. Please fix this bug. Thank you!

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
