### ISSUE TITLE
The cause of absurd spawn rates in specific modded biomes

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#491]
Just stumbled upon this... https://www.dropbox.com/s/9dgmefwi4le1np2/Screenshot%202016-10-02%2019.55.19.png?dl=0

Talking it over with Alex, he thinks it is related to another mod. What kind of mods could affect the spawn rate like this? I am using BoP.

**Comment by Sunconure11** [comment]
Using /cofh killall alligator (From CoFHCore) has yielded some... interesting results for the numbers.

https://www.dropbox.com/s/jwsy0qsqgp793pr/Screenshot%202016-10-02%2020.01.11.png?dl=0

**Comment by Sunconure11** [comment]
I think I know why this happens. It is related to biomes where not many mobs spawn at all in the first place, allowing for the mobs from F&A to take over rapidly.

The biomes in question usually use WASTELAND, SPOOKY, or DEAD BiomeDictionary definitions.

**Comment by Alex-the-666** [comment]
You are leaving out one definition - It has to be swamp, the only definition Alligator Gars are set to spawn in.

**Comment by Sunconure11** [comment]
The biome in the picture also uses a swamp definition.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
