### ISSUE TITLE
Mipmap broken

### ISSUE THREAD

**Issue by midorlo** [FossilsArcheologyRevival/FossilsArcheologyRevival#493]
FossilsArcheologyRevival uses a 2x2 texture somewhere. This causes the vanilla rendering system to forcefully and permanently disable mipmapping, resulting in grainy, flickering far away terrain rendering. Fastcraft notifies of that (note that fastcraft just prints the log entry. It's still the vanilla behavior):

```
[08:34:21] [Client thread/WARN] [FastCraft/]: The sprite fossil:plants/plant_sunflower caused the mipmap level to drop from 4 to 1 because it's too small (2x2 px).
```

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
