### ISSUE TITLE
Dinosaurs ???Glitch???

### ISSUE THREAD

**Issue by NoodleBucket** [FossilsArcheologyRevival/FossilsArcheologyRevival#494]
I really don't know if its a glitch or not but its annoying if your a poor guy in your Minecraft world and have a little bit of steak and check your Dinos hunger. Then you see it hungry and feed it but that thing its it all until its full. I wish it was like old times when you have to click many times to feed it cause I run out of alllooot of my steak due to this "???  Glitch  ?? "".  Well bye Bye Now xD

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
