### ISSUE TITLE
A version of fossil and archeology WITHOUT LLibrary needed

### ISSUE THREAD

**Issue by TataTawa** [FossilsArcheologyRevival/FossilsArcheologyRevival#495]
fossil is a great mod !!! i love it.But the requirement of llibrary is not that good for me and all people in india . I don't need to update the mods, We have a bad internet and when initializing the game, it took a hundred years to load with llibrary and fossil, and usually stuck. Disable update feature in config of llibary is useless. When in 7.2 version of fossil it loads pretty fast because there is no llibrary. So Will it be possilble that there is a version of fossil and archeology WITHOUT llibrary?

PS:  We cannot get Internet , so when the game preinitializing LLibrary it freezes. I guess LLibrary is requiring internet over and over. Will it easy to play fossil and archeology without internet?

**Comment by iLexiconn** [comment]
you already made an issue about this
