### ISSUE TITLE
I can apparently sleep on beds made of analyzers and palaeoraphe planks

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#498]
https://www.dropbox.com/s/ff89rvnr55c18n5/Screenshot%202017-01-07%2007.54.22.png?dl=0

This weird recipe should be axed in 1.10.2.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
