### ISSUE TITLE
Baby mammoths can toss other mobs into the air

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#499]
I'm gonna guess that this is a bug instead of intentional, because it's pretty strange seeing a tiny tuskless baby mammoth tossing a Sarcosuchus 10 blocks into the air and killing it. 

![2017-01-13_19 06 41](https://cloud.githubusercontent.com/assets/11862143/21951887/9c0cc11a-d9c3-11e6-967d-010232d355ca.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
