### ISSUE TITLE
Shin Guard and Feet Recipe Borked

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#502]
It appears that only certain feet/leg bones/claws work in the recipes. Not only that, but tails and gastralias are able to work in the recipe for the Feet?

**Comment by lindstheginj** [comment]
Thought I would note that a friend of mine was not able to recreate the shin guard portion of this bug.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
