### ISSUE TITLE
Tooth dagger recipe is broken

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#506]
I looked through the NotEnoughItems recipe feature (thank god for it), and there appears to be no way to craft a tooth dagger.
![2017-02-21_20 37 19](https://cloud.githubusercontent.com/assets/11862143/23197523/bd7b45b2-f875-11e6-84f0-23536902abfc.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
