### ISSUE TITLE
Palaeoraphe slab recipe broken

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#508]
When you try to craft a palaeoraphe slab with paleo planks, you get some oak wood slabs instead.

![2017-02-22_17 06 59](https://cloud.githubusercontent.com/assets/11862143/23240276/7c74e332-f921-11e6-9a3a-628ce236d218.png)

Also volcanic slabs still give back stone slabs when you middle-click them in creative mode. My old issue thread got closed, I'd just like to reiterate.

![2017-02-22_17 09 10](https://cloud.githubusercontent.com/assets/11862143/23240372/ff24adf8-f921-11e6-8d42-f1c63072961c.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
