### ISSUE TITLE
Tar slime spawning rate is way too high

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#509]
With the almost unavoidable blindness effect that comes with fighting them, it's pretty much impossible to traverse a swamp biome after a few ingame days of letting them fester. They also seem to spawn in random water holes as well as tar pits, which I think is another bug.

![2017-02-23_18 10 55](https://cloud.githubusercontent.com/assets/11862143/23287656/91d3cf18-f9f3-11e6-9969-22fd2869441e.png)

![2017-02-23_18 15 10](https://cloud.githubusercontent.com/assets/11862143/23287732/0afc2958-f9f4-11e6-8025-231fd596fe3e.png)

![2017-02-23_18 36 24](https://cloud.githubusercontent.com/assets/11862143/23288217/0bc7c9ac-f9f7-11e6-96f8-916856ab7480.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
