### ISSUE TITLE
Tamed dinosaurs fall asleep in the middle of fights

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#510]
They also fall asleep while given the follow command (even though they stay up while under the stay command), which is really annoying when you're trying to move them from one place to the other and you have to wait 10 minutes for them to be done. The only way I've seen to stop this from happening is by riding them everywhere.

![2017-02-23_18 21 41](https://cloud.githubusercontent.com/assets/11862143/23288059/06140792-f9f6-11e6-9a7c-c5bae4b2fd6d.png)

" _Yeah, let's massacre these shitty zombies, I'm the motherfuckin **T.REX!!!** I am supreme, I am legion, nothing can defeat_ --- oh sorry buddy, moon's up, I gotta get my beauty sleep now, you kids have fun."

_Snores as I'm eaten alive_

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
