### ISSUE TITLE
Dinosaurs don't seem to take damage when starving

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#511]
So I've tested this on the t. rex, parasaur, and smilo by essence of chickening them (some more than others) to the point where they have zero hunger, and the default newborn health. About 5 ingame days have passed, I've given them no food, but their health has remained static with none of them taking any damage from starving, and their moods aren't affected either (the t. rexes mood even went to the top for seemingly no reason, it had no toys). I eventually fed the t. rex a pteranodon, so that's why it says it has some hunger (even though it's been starving all the rest of it's life). I've also checked to make sure starving is enabled on the config, and the game is on hard mode in case that would affect anything. I'm not sure if this applies to everyone or just me, but if it's everyone, then... well, yeah.

![2017-02-23_20 00 39](https://cloud.githubusercontent.com/assets/11862143/23290242/35a27bac-fa04-11e6-9533-31549a6b396a.png)

![2017-02-23_20 01 13](https://cloud.githubusercontent.com/assets/11862143/23290259/4dc45f98-fa04-11e6-9213-f9d8ebd89087.png)

![2017-02-23_20 01 21](https://cloud.githubusercontent.com/assets/11862143/23290264/57d1a392-fa04-11e6-9322-c235adca1431.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
