### ISSUE TITLE
Scratching post disappeared

### ISSUE THREAD

**Issue by zenieldanaku** [FossilsArcheologyRevival/FossilsArcheologyRevival#513]
It happened once to me. I had a dino in a small enclosure with a Scratching post for it to play with. I went to sleep the night away, and when I woke up and went to see my dino, the toy had disappeared, both from the Rei's Minimap and from the game, but it was still there (the collision worked and the dino was still interacting with it) although I couldn't select it in any way (I couldn't select the dino either). I closed and reopened the game, and the toy turned visible again, but I still want to inform what happened. I'm using the lastest build (7.3.2) and, among other mods, OptiFine_1.7.10_HD_D1.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
