### ISSUE TITLE
Palaeoraphe wood can't be turned into charcoal

### ISSUE THREAD

**Issue by zenieldanaku** [FossilsArcheologyRevival/FossilsArcheologyRevival#514]
I don't know if it is the intended feature, but I can't turn palaeoraphe wood into charcoal in a furnance (I have to note here that I'm using IndustrialCraft Experimental's Electric furnance). NEI tells me that I can turn it into charcoal in a Railcraft's Coke Oven, but I think it should be possible to make charcoal out of palaeoraphe wood in any furnance as with any other wood. I'm using the lastest build (7.3.2)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
