### ISSUE TITLE
Quaggas Don't Drop Meat Or Leather Or Bones

### ISSUE THREAD

**Issue by MidnightvonCorgstein** [FossilsArcheologyRevival/FossilsArcheologyRevival#517]
I'm using 7.3.1, and when i kill a quagga it does not drop meat, leather, or any bones.

**Comment by MidnightvonCorgstein** [comment]
actually, i'm using 7.3.2*

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
