### ISSUE TITLE
Game crashes from ankylosaurus egg hatching, world can't be loaded again

### ISSUE THREAD

**Issue by acbroussard** [FossilsArcheologyRevival/FossilsArcheologyRevival#518]
Specs: F&A v. 7.3.2, Llibrary, llibrary 1.5.1, forge 10.13.4.1614, only other mod is optifine. 
Placed anky egg on the ground, after awhile it became clear that gameticks had stopped (forge won't burn, sifter won't sift, analyzer won't analyze, crops won't grow, anky isn't hatching, everything is frozen) but I can still move around and interact with objects. Quit game to save, hoping that a restart would fix the problem. The world will no longer load, I get a crash after the "generating terrain" screen.

**Comment by 4f6f3b** [comment]
Any crash report?

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
