### ISSUE TITLE
Making my skin transparent?

### ISSUE THREAD

**Issue by Stealthlykilla** [FossilsArcheologyRevival/FossilsArcheologyRevival#519]
The Llibrary from the thread for some reason makes me transparent in my game I'm not sure if it's the combination of those mods or if it's just Llibrary

**Comment by EtheralSnake** [comment]
Yeah, the same thing happens to me too.
Also, is that Pip Bernadotte from Hellsing I see in your profile picture?

**Comment by Stealthlykilla** [comment]
Yes it is Pip and sorry I haven't been playing minecraft lately

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
