### ISSUE TITLE
Tar is invisible through tar slimes

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#521]
![2017-06-13_16 51 42](https://user-images.githubusercontent.com/11862143/27109568-a4f349e6-5058-11e7-85d4-e48ebdc7a96a.png)

From what I've seen it's only through the side of them. No idea if this is the same for any other blocks.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
