### ISSUE TITLE
Plesiosaurus despite being passive acts hostile

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#522]
They continually chase after and crowd around smaller animals like henodus or nautilus as if they've been aggroed even though they're passive and cannot do any damage.

![2017-06-13_20 17 08](https://user-images.githubusercontent.com/11862143/27114036-a8c0ff2e-5075-11e7-85b8-f68a626b9379.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
