### ISSUE TITLE
Natura mod breaks the Archeology Workbench Recipe

### ISSUE THREAD

**Issue by Wolf7104** [FossilsArcheologyRevival/FossilsArcheologyRevival#523]
I found this while playing in my survival world - apparently, when you use Natura Mod, the recipe for the Archeology Workbench changes to no longer be able to be crafted with normal Crafting Table. I found it through Not Enough Items and tested it. Here's some pictures:
![fossilrecipewrong2](https://user-images.githubusercontent.com/29438742/27146433-fa56d44a-5141-11e7-9145-14878e6b45f8.PNG)
![fossilrecipe3](https://user-images.githubusercontent.com/29438742/27146444-01e0c522-5142-11e7-9410-110206b20f0b.PNG)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
