### ISSUE TITLE
Dinosaurs/Creatures obeying orders, but not making any physical movement.

### ISSUE THREAD

**Issue by THEREALTOLMO** [FossilsArcheologyRevival/FossilsArcheologyRevival#524]
SOOOO
I think i found a bug in the mod. Since I'm constantly adventuring and not building habitats for my created creatures, i set them on the "Stay" command.
It turns out that whenever I leave the game with my creatures on "Stay", they wont follow me or move if I order them to .

However, when I re-enter the world with them on follow or wander, they would start to move as usual

Since I am playing a multiplayer world with my bro, it would be very inconvenient to constantly exit and enter the world

Please, fix this bug.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
