### ISSUE TITLE
Pteranodon's Glitchy Flying Animation

### ISSUE THREAD

**Issue by epicslayer999** [FossilsArcheologyRevival/FossilsArcheologyRevival#525]
The Pteranodon in the mod return to their walking position and animation if they even slightly brush a block, the A.I seems to think they landed and plays the animation for when they transfer into their standing pose, but due to the fact that they're air born they proceed to "run" in the air.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
