### ISSUE TITLE
Animals not moving and trying to eat food outside of their exhibits.

### ISSUE THREAD

**Issue by NicCF** [FossilsArcheologyRevival/FossilsArcheologyRevival#526]
So problem one is when some dinos (just saying that to be short I know they all aren't dinos) who are not around their owners on a server won't move even if someone else is in the chunk. I have two deinonychus a friend gave me that he hatched and they don't move. They sit in their pen idle. While the gallis he gave me are running around their exhibit. I have seen the problems in trikes, stegos, ankys, pachys, brachis, dryos and parasaurs.

Second problem is my dinos always are more attracted to food outside their pens than inside even if a solid wall of 5 blocks tall is in front of them. This has been a problem for all the dinos in the mod on my server. 

If you have any more questions I am Nic on the discord. (I have a raptor smoking a pipe for a profile picture)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
