### ISSUE TITLE
A few more bugs

### ISSUE THREAD

**Issue by NicCF** [FossilsArcheologyRevival/FossilsArcheologyRevival#527]
1. Dodos age 2 are bigger than dodos age 3
2. Tar Slimes sometime show up invisible.
3. I have had my kelenkens have poof out of existence. (Though may be from one of the mods I have installed)
4. Confuciusornis not being able to eat from feeders.
5. Fish despawning when not name tagged, nautilus despawning regardless.

Sorry for stating any bugs you guys already knew of! If you need anymore insight I'm Nic on the discord.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
