### ISSUE TITLE
Server Crashes when Dinos hatch.

### ISSUE THREAD

**Issue by Reece-B** [FossilsArcheologyRevival/FossilsArcheologyRevival#528]
I tried hatching 2 pachycephalosaurs and when they were about to spawn in the server my friends and I are in crashed. They can get back in fine, but whenever the chunks that the dinos are in load (aka whenever I get back on the server) the server crashes again. The server owner told me he got the error below. Any and all information you can tell us is appreciated. Thank you!

Location:
    fossilsarcheology/server/entity/EntityPrehistoric.createEgg(Lnet/minecraft/entity/EntityAgeable;)Lnet/minecraft/entity/Entity; @179: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'net/minecraft/entity/Entity' (from method signature)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
