### ISSUE TITLE
Deinonychus does not deal damage to donkeys

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#529]
Pulled this off the wiki:
"I found a glitch. When a deinonychus attacks a horse, it would jump onto it's back, but not deal any damage. Instead it just sits on it and flail around like a rather large chicken until the horse bucks it off or it jumps off. It'd keep trying until you kill the horse, and it's rather amusing to watch."

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
