### ISSUE TITLE
Gallimimus can't use toys.

### ISSUE THREAD

**Issue by epicslayer999** [FossilsArcheologyRevival/FossilsArcheologyRevival#530]
Simple.

Gallimimus try to use toys, such as the Scratching Post and Rubber Ball, but they don't seem to inflict the damage that registers it as "playing". This results in them infinitely performing their attack animation on the toys.

**Comment by Matty0066** [comment]
I’m having the same issue

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
