### ISSUE TITLE
Constant Crash on start up.

### ISSUE THREAD

**Issue by ClaireinSorcia** [FossilsArcheologyRevival/FossilsArcheologyRevival#535]
I've installed forge version 10.13.2.1291 and have the most current Fossil Acheology Revival, 7.3.2. With the Llibrary 1.7.7-1.12.1 in the folder labeled 'mods' i get an instant crash with no log, but without out it, I just get this. What the heck do I do?
The game crashed whilst initializing game The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: fossilsarcheology/client/model/prehistoric/ModelTriceratops

**Comment by lindstheginj** [comment]
F/A 7.3.2 requires Llib 1.5.1 for 1.7.10.
