### ISSUE TITLE
A suggestion for cathemeral AI

### ISSUE THREAD

**Issue by PCAwesomeness** [FossilsArcheologyRevival/FossilsArcheologyRevival#536]
Since my suggestion document is too clumped up, I'll just leave this here.

I remember how you removed cathemeral sleeping AI because all Sarcosuchus did was sleep all day long. However, this could fix stuff up a bit.

You can make it so, at random, cathemeral creatures could sleep for a period of time roughly equivalent to a whole day or night. After this period of time, they could wake up and start moving around; in order to prevent constant sleeping, you can make it so cathemeral sleeping has a cooldown of 7.5 real-time minutes.

Oh, and marine reptiles should be able to sleep in the water.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
