### ISSUE TITLE
Issue with dinos using toys

### ISSUE THREAD

**Issue by liquorice-wb** [FossilsArcheologyRevival/FossilsArcheologyRevival#537]
For some reason my aquatic creatures (henodus, ichthyosaurus) interact with the bubbler (and the ball) by just sitting on the bottom of the pool near it. They don't swim around it or anything, and when I break/disable it they go back to swimming around normally. I have no land creatures yet so I can't test the toys on them to see if it has the same problem.

**Comment by ToaFeron** [comment]
I too have this problem with my aquatics, very annoying.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
