### ISSUE TITLE
Dinosaurs not obeying the follow command.

### ISSUE THREAD

**Issue by EtheralSnake** [FossilsArcheologyRevival/FossilsArcheologyRevival#539]
Sometimes when I command a dinosaur to stay and leave the game, I come back the next day to find that it won't follow my commands. The dinosaur stays in a sitting position and will not follow or teleport to me, even if I go more than 50 blocks away.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
