### ISSUE TITLE
dinosaurs trying to eat the roof

### ISSUE THREAD

**Issue by Robomnz** [FossilsArcheologyRevival/FossilsArcheologyRevival#541]
this picture explains everything...
they basically try and climb out of their habitat so i had to build a roof to stop them from climbing out and now they're eating the roof

![2017-12-28_17 04 22](https://user-images.githubusercontent.com/34904608/34400104-f5cef0c8-ebf2-11e7-83f7-1629db7c8cc3.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
