### ISSUE TITLE
Dilophosaurus stands & opens eyes while asleep

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#546]
![2018-01-17_21 08 43](https://user-images.githubusercontent.com/15497127/35077342-ca7bc0e4-fbca-11e7-8f99-32b3e90ce94a.png)
Hard to see, but it's got the sleepy z's yet it's standing with its eyes open.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
