### ISSUE TITLE
Cannot climb Tempskya from south side

### ISSUE THREAD

**Issue by ThatOneGaymer** [FossilsArcheologyRevival/FossilsArcheologyRevival#547]
So normally the plant Tempskya can be climbed from the sides, but I've found that it cannot be climbed from the South side, which isn't too big of a problem (aside from ways my base is set up, but that can be easily fixed :P ) but I just wanted to make sure it wasn't meant to be that way

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
