### ISSUE TITLE
Ridiculous Gar Spawn Rate

### ISSUE THREAD

**Issue by ToaFeron** [FossilsArcheologyRevival/FossilsArcheologyRevival#549]
I managed to take these screens before my game lagged to death...
![2018-03-01_09 04 20](https://user-images.githubusercontent.com/36965520/36859091-3a827ce2-1d32-11e8-96e8-4bd262c40166.png)

![2018-03-01_09 04 08](https://user-images.githubusercontent.com/36965520/36859121-483caf4c-1d32-11e8-80e3-8cecc535119a.png)

![2018-03-01_09 04 07](https://user-images.githubusercontent.com/36965520/36859131-502fc8d8-1d32-11e8-8bb3-412faaa7d880.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
