### ISSUE TITLE
Feeders not working

### ISSUE THREAD

**Issue by Hibanan** [FossilsArcheologyRevival/FossilsArcheologyRevival#550]
I have a Spinosaurus and a Brachiosaurus, but no matter where I put the feeders the dinos don't eat from them. I tried in level with their head, lower, higher, next to a wall, in the ground but nothing seems to work. (They are filled up with food). Also might not be a bug but my spino isn't eating meat droppend on the ground.

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
