### ISSUE TITLE
Hatching progress more than 100% and keeps going

### ISSUE THREAD

**Issue by Hibanan** [FossilsArcheologyRevival/FossilsArcheologyRevival#552]
![image](https://user-images.githubusercontent.com/38100503/38367074-f9a72fbc-38e1-11e8-8c6e-1ad89f547905.png)

Happens when I keep looking at the egg using the DinoPedia when it's about to hatch

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being

**Comment by GarchompGirl** [comment]
Oof i keep getting this too, sad that the thread is closed
