### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Arre2000** [FossilsArcheologyRevival/FossilsArcheologyRevival#556]
The game crashed whilst unexpected error
Error: java.lang.IndexOutOfBoundsException

The game starts perfect and then when i start a world it says shutting down internal server

**Comment by 4f6f3b** [comment]
Please provide a full crash log.

**Comment by Arre2000** [comment]
sorry but the view crash report does not work for me

**Comment by 4f6f3b** [comment]
Navigate to where your Minecraft/profile location where you installed F/A into, find the /crash-reports folder, open up the latest crash report in a text editor and copy the contents from there. Let me know if you need help finding the folder location.

![image](https://user-images.githubusercontent.com/1882828/38820764-5f04a83c-4164-11e8-9573-de9eeb998907.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
