### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by FatherMars** [FossilsArcheologyRevival/FossilsArcheologyRevival#571]
I have Fossils installed through forge, and I can't even play because I can't get it to load. 

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: fossilsarcheology/client/model/prehistoric/ModelTriceratops"

There's the crash report.
Trying to to play on 1.7.10

**Comment by lindstheginj** [comment]
You haven’t installed Llibrary 1.5.1 for 1.7.10, which is required to play. 

https://minecraft.curseforge.com/projects/llibrary/files/2319767
