### ISSUE TITLE
Balls do not show up in creative except for the F&A tab

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#577]
Other items might be affected as well.

**Comment by gegy1000** [comment]
What's the issue?

**Comment by Sunconure11** [comment]
Try searching for the colored toy balls in creative.

They don't show up

**Comment by gegy1000** [comment]
Ah. I see the issue. I fixed that here: https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/ef587a77d443ae6d5e2a836f0db498ccf7877fd1#diff-81866cab3b896c1388a655d0c3dedb5cR47

**Comment by Sunconure11** [comment]
Make sure no other items aren't affected, as I feel others could be and I simply did not notice.
