### ISSUE TITLE
Meat, bones, and various other Enum-based items need aspects

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#578]
Due to the apparent difficulty of doing so, I am unable to figure out how to apply Thaumcraft aspects to them.

**Comment by Sunconure11** [comment]
Furthermore, existing things need a bit more revision to their aspects.

**Comment by Sunconure11** [comment]
Due to the lower amount of aspects Thaumcraft has compared to older versions, I will list what aspects are being used for what in some scenarios:

Alchemy - Poison, Venom, Any chemical substance
Air - Presence of feathers
Protect - Armor, chitin, carapace
Aversion - Large teeth, large horns, large antlers, anything that can poke holes in you
Senses - Animals with notable calls, visual patterns, etc

Feel free to come up with more uses for TC's aspects

**Comment by Alex-the-666** [comment]
@Sunconure11 ok
