### ISSUE TITLE
Some aquatics not swimming

### ISSUE THREAD

**Issue by GalacticNarwhal** [FossilsArcheologyRevival/FossilsArcheologyRevival#583]
I've noticed that my Sarcosuchus will stay at the bottom of his pool and not swim up to his little island. I asked ASDFGirl about it, and she said the aquatics were all broken. I thought "well shit, I guess I'll have to wait until it gets ported to 1.12.2," but then I got a Liopluerodon, and he seems to swim just fine.

**Comment by mcnetherbeast** [comment]
same I don't know why liopluerodon seems to be swimming fine, so is plesiosaurus for me. However, the mosasaurs and ichthyosaur as expected are not

**Comment by Alex-the-666** [comment]
will be fixed in 8.0.0
