### ISSUE TITLE
Bugs including water and tar.

### ISSUE THREAD

**Issue by DevilKitten** [FossilsArcheologyRevival/FossilsArcheologyRevival#586]
![2018-06-18_09 39 12](https://user-images.githubusercontent.com/31811686/41543042-c236b3f2-72db-11e8-929a-5708b5a0e76b.png)
This is pretty self-explanatory.

**Comment by lindstheginj** [comment]
It really isn’t. Please explain what is wrong in your photo.

**Comment by Alex-the-666** [comment]
will be fixed in 8.0.0
