### ISSUE TITLE
End item (syringes, eggs) don't render inside the culture vat.

### ISSUE THREAD

**Issue by tyranno66** [FossilsArcheologyRevival/FossilsArcheologyRevival#606]
You can still click on the slot to get your items out.

**Comment by Alex-the-666** [comment]
i dont get what you mean

**Comment by lindstheginj** [comment]
So, when you cultivate something, and it finishes cultivating, it vanishes. There's nothing in the result slot. BUT if you click on it, surprise! It appears in your inventory.

**Comment by Alex-the-666** [comment]
oh
