### ISSUE TITLE
Other zombie pigman issues

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#632]
There is no way to heal them
They aren't undead mob
They doesn't have the 2 armor points like normal zombie pigman

https://minecraft.gamepedia.com/Zombie_Pigman

**Comment by mser7** [comment]
Your mobs have a tendency of never having armor point yet higher hp, please actually add in the points while remain the hp amount for them.

**Comment by Alex-the-666** [comment]
i added armor to them dude. I do read the description of issues

**Comment by mser7** [comment]
I see, just want to make sure.
