### ISSUE TITLE
JEI Plugin, HWYLA shenanigans

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#633]
This could come in handy, since we are low on cross-mod compat

**Comment by Alex-the-666** [comment]
Analyzer portion already complete

**Comment by Sunconure11** [comment]
You said modpack devs eat cross-mod support for breakfast, which you are not incorrect on. Crafttweaker support would be the holy grail for them.

https://github.com/CraftTweaker/CraftTweaker/tree/1.12/CraftTweaker2-API

**Comment by Alex-the-666** [comment]
not viable for this update as I'd have to completely change how the machines work

**Comment by gegy1000** [comment]
Let's not close this as it is still a possibility for future versions.
