### ISSUE TITLE
Baby and enchanted golden sword

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#634]
Tamed zombie zombie pigman should have a 5% chance to spawn as a baby, with higher speed, and sometimes hold golden sword with enchantment, following the vanilla mechanic.
https://minecraft.gamepedia.com/Zombie_Pigman

**Comment by Alex-the-666** [comment]
no

**Comment by mser7** [comment]
Atleast I tried
