### ISSUE TITLE
structures

### ISSUE THREAD

**Issue by StarWarsDinosaur** [FossilsArcheologyRevival/FossilsArcheologyRevival#649]
Not all structures spawn naturally.

**Comment by tyranno66** [comment]
Is this in 1.7?

**Comment by StarWarsDinosaur** [comment]
Yes, sorry forgot to put 7.3.2 1.7.10

**Comment by tyranno66** [comment]
1.7.10 is a deprecated version that we won't be updating further. It's fixed in the port.

**Comment by tyranno66** [comment]
1.7.10 is a deprecated version that we won't be updating further. It's fixed in the port.
