### ISSUE TITLE
Mobs don't interact with toys... but seem to enjoy their presence anyway

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#651]

**Comment by Alex-the-666** [comment]
not able to duplicate. tested with dodos pachycephelosaurus and megalania all play with ball, scratching post and tethered log

**Comment by Alex-the-666** [comment]
yep, closing this since its definitely related to the no ai for mobs raised as babies bug.
