### ISSUE TITLE
Culture vat sharing the podium problem

### ISSUE THREAD

**Issue by mser7** [FossilsArcheologyRevival/FossilsArcheologyRevival#654]
Put something inside the vat as well as the secondary item to vegin the progress
Exit the gui, a floaty embryo model can be seen inside the vat
Relog
Embryo model is now gone, right clicking it again for it to appear.
If you leave the chunks or relog again, then it happen.

Still reporting despite it is 1.7.10 since this exist in the 1.12.2 version of another similar coded mod.

**Comment by mser7** [comment]
Correction: the model doesnt appear immediately after you exit the gui, open and close it one more time and it will appear

Also: P O D I U M

**Comment by Alex-the-666** [comment]
fix
