### ISSUE TITLE
Turning into mobs on morph retains more of the animal's traits than in 1.7.10

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#657]
I don't recall this happening in 1.7.10, but when I transformed into a megaloceros and gallimimus, I occasionally made sounds appropriate to both animals and ate grass. Grass eating didn't happen when my hunger was low, but seemed to be on its own (the mobs?) schedule. If this is some new feature of morph, ignore me, but if not this is sort of weird.

**Comment by Alex-the-666** [comment]
intended, this feature was added to morph
