### ISSUE TITLE
Broken Sarracenia texture

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#675]
![screenshot 2018-07-11 00 14 36](https://user-images.githubusercontent.com/15497127/42550392-798db486-849f-11e8-89ee-6ef06bbe614c.png)

**Comment by Alex-the-666** [comment]
not able to replicate... try breaking them and placing them again, could be hold overs from when they used to be broken @lindstheginj
