### ISSUE TITLE
Bug testing: Batch 1

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#685]
- [x] Bug 1: Ancient ferns pop out
When placed next to each other while on dirt, coarse dirt or podzol, ancient ferns break.
This also occurs on grass, though somehow the ferns seem to spread fast enough there to keep up. Specifically, on grass they are able to be beside each other in the first few growth stages, but they seem to break once they reach a certain size.

* Side-note 1: Ancient ferns cannot be placed on modded types of dirt, such as sandy dirt from Biomes O' Plenty

- [x] Bug 2: Animals can be fed food items even when not hungry.

- [x] Bug/observation 3: Speedy water creatures
All aquatic creatures (incl. Spino) seem incredibly fast in the water. Megalograptus is a challenge to keep up with even in creative mode!

- [x] Bug 4: Spino's head doesn't quite line up with the fish during the shaking animation.

- [x] Bug 5: Deinonychus's "latching onto prey" animation looks strange when attacking a large creature (in this case a Megalania).
The animation seems to be designed for small prey, and the Deinonychus essentially zooms "inside" the larger model

Crash report 1 (occured after a Deinonychus attacked and latched onto its third Megalania):
https://pastebin.com/VfFV8ybk

**Comment by lindstheginj** [comment]
I’d recommend reporting bugs separately, so that way people can respond and close them individually. Great example: For bug 2, I think you’re seeing the taming by hand feeding, not a bug - tamed animals stop eating when full, but untamed ones will keep eating until they’re tamed, I think.

**Comment by Totemaster** [comment]
Yes. From now on they'll be separate.
And ah I see. makes sense.

**Comment by Alex-the-666** [comment]
one more to go
