### ISSUE TITLE
Dodos and stegos hardly move 

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#693]
The only other terrestrial mobs we have right now that are regularly encountered by players is the mammoth, but that moves around fine. I'm guessing the herd ai has the mammoth mobile, while the stegos and dodos don't feel like moving anywhere

**Comment by Alex-the-666** [comment]
@lindstheginj actually this is because I spawned the mamoths in as adults, where as the dodos and stegosaurus were raised from the egg, back when baby mobs didnt have AI. Now they do, but these mobs are still bugged. If you grow new ones youll see they arent as buggy
