### ISSUE TITLE
Growth issues

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#696]
- [ ] Bug 14: Stegosaurus that was hatched from an egg and then quickly raised using chicken essence moves incredibly fast, and then spins uncontrollably in one spot once nearing and then reaching adulthood.
A Gastornis hatched and raised in the same enclosure in the exact same way seemingly behaves and moves more or less normally.
A second Stegosaurus spawned in as an adult moves and behaves normally.
A second Gastornis spawned in as an adult moves and behaves mostly like the first one.

**Comment by Alex-the-666** [comment]
updot
