### ISSUE TITLE
Feeder issues 1

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#697]
- [ ] Bug 15: Feeder GUI kicks you out if you try to insert a whole stack of food items at once. It also doesn't consume the stack.
However, adding the items one by one seems to work, at least most of the time. Occasionally however, the food value doesn't increase when an item is placed in the feeder.

**Comment by Alex-the-666** [comment]
ffixed by geg
