### ISSUE TITLE
Aquatic reptiles phase through glass and travel huge distances

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#698]
- [ ] Bug 16: Aquatic creatures somehow disappear almost immediately from tanks, even when the player is within the same chunk.
Addendum: Bizarrely, they then somehow end up to several chunks away. One Plesiosaurus travelled 33 blocks when measured from the closest corner of the tank (the reptile was seemingly stopped by a fence corner in that location), and an Ichthyosaurus travelled a whopping 110 blocks from the corner!
A similar thing happened with a Liopleurodon yesterday.

**Comment by Alex-the-666** [comment]
should be fixed
