### ISSUE TITLE
Megalania doesn't sleep

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#701]
- [ ] Bug 19: Megalania are listed as diurnal, but although they stand still at night, they don't seem to have a sleeping animation, and they still make sound.
Also they don't start moving again once the night is over.

**Comment by Alex-the-666** [comment]
![2018-07-20_08 56 39](https://user-images.githubusercontent.com/8662109/43012303-d45914b6-8bfa-11e8-80b0-27bc99499423.png)
sleeps fine for me, maybe update to latest build?
