### ISSUE TITLE
Sounds have yet to be updated

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#702]
- [ ] Bug/issue 20: Creatures lacking updated sounds:
* Ankylosaurus (sounds are in the Dropbox)
* Spinosaurus (sounds are in the Dropbox)
* Pteranodon (sounds are in the Dropbox)
* Quagga (sounds are in the Dropbox)

**Comment by Alex-the-666** [comment]
@Totemaster do you think you could convert them all into oggs with the proper name format? ex(spinosaurus_hurt0.ogg, spinosaurus_hurt1.ogg, spinosaurus_living3.ogg, spinosaurus_death1.ogg, etc..)

**Comment by Totemaster** [comment]
Sure.

**Comment by Totemaster** [comment]
Done.

**Comment by Alex-the-666** [comment]
danke
