### ISSUE TITLE
Texture accuracy updates

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#707]
Checklist for Lindsay mostly:

- [x] Reduce compy feathers

- [x] Reduce rex feathers

- [x] Remove external allo teeth

- [x] Remove extra brachi claws

- [x] Reskin confuci

- [x] Remove para feet (front)

- [x] Remove external spino teeth

- [x] Fix stego plate dimorphism

- [x] Remove gastornis bill tip

- [x] Create feathered dryo option

**Comment by Alex-the-666** [comment]
added the tyrannosaurus ones

**Comment by lindstheginj** [comment]
I believe raptor's revised terror bird textures (he made changes to all four) are all done and in the dropbox.
