### ISSUE TITLE
Village structure issues

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#709]
- [ ] Bug/issue 25: Archaeologist village structure is always made of oak, even in spruce villages.
Haven't yet found a desert or savanna village, but in all likelihood the same issue is probably present there.
Would be nice to see some other variants.

**Comment by Alex-the-666** [comment]
![works fo me](https://user-images.githubusercontent.com/8662109/42977729-c5938ec0-8b7d-11e8-8e25-c54bc3080075.png)

**Comment by Alex-the-666** [comment]
worketh for me
