### ISSUE TITLE
Dinopedia text is offcenter

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#719]
![screenshot 2018-07-21 21 29 55](https://user-images.githubusercontent.com/15497127/43041411-78d0a44a-8d2d-11e8-8599-9d70f0616a59.png)

**Comment by lindstheginj** [comment]
Also pregnancies seem to take f o r e v e r compared to egg hatching

**Comment by Alex-the-666** [comment]
fx
