### ISSUE TITLE
Horse giving birth to llama crashed the server

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#720]
"The game crashed whilst ticking entity
Error: java.lang.ClassCastException: net.minecraft.entity.passive.EntityHorse cannot be cast to net.minecraft.entity.passive.EntityLlama"
[crash-2018-07-21_21.34.37-client.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/2216653/crash-2018-07-21_21.34.37-client.txt)

**Comment by lindstheginj** [comment]
Also occurred when a cow gave birth to a llama

**Comment by lindstheginj** [comment]
[crash-2018-07-21_22.24.20-client.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/2216713/crash-2018-07-21_22.24.20-client.txt)

**Comment by lindstheginj** [comment]
[crash-2018-07-21_23.56.19-client.txt](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/2216714/crash-2018-07-21_23.56.19-client.txt)

**Comment by Alex-the-666** [comment]
focksed
