### ISSUE TITLE
Animania Support is probably needed

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#723]
Due to it overriding most vanilla livestock, it might be a good idea to implement support.

Despite the fact that Alex got banned from their discord for shitposting too much, he can still figure out how anyways. Animania is visible source.

https://github.com/capnkirok/animaniamod

In addition, Totemic managed to pull it off for one of the rituals.

https://github.com/TeamTotemic/Totemic/blob/1.12.2/src/main/java/pokefenn/totemic/ceremony/CeremonyBuffaloDance.java

**Comment by Alex-the-666** [comment]
Already encorperated and configurable

**Comment by Sunconure11** [comment]
I was referring to placement of embryos into animania animals. I'll test this.

**Comment by Alex-the-666** [comment]
make sure you build the latest build cause I only did this a few commits ago

**Comment by Raptorofwar** [comment]
More Animania support requests; goat's milk cannot be used for the cultivator.
