### ISSUE TITLE
Dependency functionality might need some adjustments

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilsArcheologyRevival#724]
https://pastebin.com/FjBMg7v2

**Comment by Alex-the-666** [comment]
install llib

**Comment by Sunconure11** [comment]
By default, the mod should not throw an error if you do not have LLib.

Try toying around with this, so it merely throws a message saying to install said mod.

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/mapping-and-modding-tutorials/2866817-setting-up-dependencies-in-minecraft-forge-with

**Comment by Alex-the-666** [comment]
dunge

**Comment by Sunconure11** [comment]
Testing does not cause a message to fire. I think the nautilus model might have something going on preventing this.

**Comment by Alex-the-666** [comment]
fixed
