### ISSUE TITLE
Ichthyosaurus all swam great for a while, then got stuck at the top of the tank

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#732]
![screenshot 2018-07-22 19 45 11](https://user-images.githubusercontent.com/15497127/43051437-d1d557ec-8de7-11e8-81b2-d0f490e7df57.png)
They each decided that the glowstone made a good backscratcher I guess. Build 335

**Comment by lindstheginj** [comment]
Aquatics just don't seem to do well with a roof. Is this intentional bc they can't get to air?

**Comment by Alex-the-666** [comment]
#1511
