### ISSUE TITLE
Megalograptus should not give you potion effects

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#733]
Also why does this hellspawn attack ichthyosaurs, they’re too big

**Comment by Bluestreak52** [comment]
Also, why is it so aggressive and so fast in water?

**Comment by Alex-the-666** [comment]
@lindstheginj it doesnt give you potion effects. Do you mean megalania?

**Comment by lindstheginj** [comment]
No, red was attacked by a megalograptus and it gave him poison and some other effects, and it also poisoned and killed my ichthys. Is it possible there was a mix up in the code?
