### ISSUE TITLE
pteranodon open up their wings to fly but don't get off the ground

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#744]
I have to punch them for them to achieve liftoff!
Build 353

**Comment by lindstheginj** [comment]
Okay, they CAN achieve liftoff if they jump off the edge of a block, but they should be able to get off of a flat surface too.

**Comment by tyranno66** [comment]
New liftoff anims?

**Comment by Alex-the-666** [comment]
fixed
