### ISSUE TITLE
When Pteranodon fly a certain distance away, they stop moving

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#746]
This is hard to describe, especially because I can't get close enough to tell how far away they are.
Basically, when Pteranodon fly a certain distance away (I'm guessing like a chunk?) they freeze in midair. No animation, no movement, but they are still visible. When I try to approach them, they start moving again, until they fly too far and freeze again.
Build 349

**Comment by lindstheginj** [comment]
Weirdly enough, this is also happening for my megalodons - they freeze when I get a certain distance away but start moving again when I get closer. However, it was NOT happening with the fish, who continue to do the swim anim anyway. Build 377

**Comment by lindstheginj** [comment]
Issue is still happening on 391, with spinos and sarcos too. I tried to measure it out as best as i could - it seems to happen when you're at least 40 blocks away

**Comment by lindstheginj** [comment]
They're rendering, but not moving. And it's not happening with every species. So its definitely not just my render distance.

**Comment by tyranno66** [comment]
Just test it out to be certain.

**Comment by lindstheginj** [comment]
The issue still occurs. It may be slightly farther away but it's such a short distance that I can't be certain that it actually got farther at all.

**Comment by Alex-the-666** [comment]
those chunks arent loaded on the server but are on the client. The only solution would be to make dinosaurs load chunks but that would be, in terms of Alan Grant, "A very bad idea"
