### ISSUE TITLE
Villager house doesn't change biome types

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#787]
I'm really confused because I JUST SAW a sandstone one the other day, so it was working. But now it's spawning between houses and not changing types again. Build 389
![screenshot 2018-08-02 19 38 18](https://user-images.githubusercontent.com/15497127/43616694-ce7ac076-968b-11e8-9a98-9f21b94dacf4.png)

**Comment by Alex-the-666** [comment]
fied
