### ISSUE TITLE
Gastornis' hitbox is like 3x3x3

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#801]
It's way too big for a creature that's like 1.5 blocks tall. Build 391

**Comment by Alex-the-666** [comment]
fixed, apparently.
![2019-01-21_11 08 48](https://user-images.githubusercontent.com/8662109/51494298-0429cd80-1d6d-11e9-8c97-252702bed96c.png)
