### ISSUE TITLE
Small aquatics are now speedy gonzales.

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#808]
They seem to have inherited some of megalograptus's speed...

**Comment by Adsper** [comment]
Actually now that I test this some more, it seems like all the small aquatics (Lio, henodus, plesiosaurus, baby meganeura, and the fish) are affected besides ichthyosaur.

**Comment by Adsper** [comment]
Added baby megalodon

**Comment by Alex-the-666** [comment]
fixed
