### ISSUE TITLE
Spawn Eggs in alphabetical order?

### ISSUE THREAD

**Issue by Mushroomsock** [FossilsArcheologyRevival/FossilsArcheologyRevival#812]
Vanilla spawn eggs have been in alphabetical order for a while now. It might be easier to find certain mobs in this mod if they were arranged this way too.

**Comment by Alex-the-666** [comment]
nope. I'd have to restructure the PrehistoricEntityTypes and this would cause so many mind boggling issues that its honestly not worth it.
