### ISSUE TITLE
Academy breaks into village structures

### ISSUE THREAD

**Issue by Mushroomsock** [FossilsArcheologyRevival/FossilsArcheologyRevival#817]
Not sure if this was worth opening a new issue for since there's already a couple for the Archeologist villager house, but this is a different structure so...
![2018-08-18_10 59 01](https://user-images.githubusercontent.com/8728038/44292172-2065a200-a2d7-11e8-95c9-d900df8a87a3.png)

**Comment by Alex-the-666** [comment]
nothing I can do about this. there's no way too tell if the sandstone has been generated by a village or naturally.
