### ISSUE TITLE
Raptor climbing is broken

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#822]
I've had these guys in small two block high pens for about five minutes now with food outside and none of them have climbed out. Every so often, they'll push each other into the wall and they'll almost climb out, but then they just slide back in.
![deinoandveloclimbing](https://user-images.githubusercontent.com/11862143/44294404-607f4300-a24b-11e8-96e2-0cd290a588ea.png)

**Comment by Alex-the-666** [comment]
fixed
