### ISSUE TITLE
Sifter is broken

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#823]
It'll sift the first block in a stack just fine, but after that it just keeps sifting the same block over and over and not giving any result.
Tested with sand, red sand, and clay.

**Comment by Mushroomsock** [comment]
Seems they occasionally work, but when the sifter is supposed to return no items it doesn't use any items either.

**Comment by Alex-the-666** [comment]
fixed
