### ISSUE TITLE
[Suggestion]Extra evil tar slimes

### ISSUE THREAD

**Issue by lucgerim** [FossilsArcheologyRevival/FossilsArcheologyRevival#824]
Suggestion for tar slimes go for any other mobs, no matter what type of mob it is, and not just players

**Comment by lindstheginj** [comment]
Since we’re currently bug testing the 1.12.2 port, we’re trying to keep this for bug testing only. Please direct any further explanations or suggestions here:
https://fossils-archeology.wikia.com/wiki/Board:Suggestions
