### ISSUE TITLE
Soulsand should be able to be sifted

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#825]
Since it's a type of sand, it could be sifted and possibly return a mutant plant or some type of Anu related thing.

**Comment by Sunconure11** [comment]
![screenshot 2018-08-17 23 50 33](https://user-images.githubusercontent.com/5614902/44295517-6ccdc500-a278-11e8-815a-446280f7e29f.png)

**Comment by Sunconure11** [comment]
Implemented, but the sifter is currently broken

**Comment by Alex-the-666** [comment]
fixed
