### ISSUE TITLE
Crash when right-clicking dilophosaurus with a dinopedia

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#827]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 8/17/18 9:26 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/server/integrated/IntegratedServer$3
	at net.minecraft.server.integrated.IntegratedServer.func_71263_m(IntegratedServer.java:497)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:854)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 650725688 bytes (620 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2720 Optifine OptiFine_1.12.2_HD_U_E1 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID           | Version       | Source                                               | Signature                                |
	|:--------- |:------------ |:------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft    | 1.12.2        | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | mcp          | 9.42          | minecraft.jar                                        | None                                     |
	| UCHIJAAAA | FML          | 8.0.99.99     | modpack.jar                                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge        | 14.23.4.2720  | modpack.jar                                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | llibrary     | 1.7.14        | llibrary-1.7.14-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | fossil       | 8.0.0-develop | fossilsarcheology-8.0.0-develop-JenkinsBuild_412.jar | None                                     |
	| UCHIJAAAA | ichunutil    | 7.1.4         | iChunUtil-1.12.2-7.1.4.jar                           | None                                     |
	| UCHIJAAAA | morph        | 7.1.2         | Morph-1.12.2-7.1.2.jar                               | None                                     |
	| UCHIJAAAA | harvestcraft | 1.12.2u       | Pam's+HarvestCraft+1.12.2u.jar                       | None                                     |
	| UCHIJAAAA | tabula       | 7.0.0         | Tabula-1.12.2-7.0.0.jar                              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 390.65
	OpenGlRenderer: GeForce GT 720/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Alex-the-666** [comment]
fixed
