### ISSUE TITLE
Pouncer Bug

### ISSUE THREAD

**Issue by Noonyeyz** [FossilsArcheologyRevival/FossilsArcheologyRevival#833]
Whenever a pouncer (deinonychus/velociraptor) attacks, they lunge at you, never mount on top of you and then freeze in mid-air. They still deal the damage although they are not on top of you and are stuck in the position they "successful" mounted on. They are still there and everything, you can hit them and no matter how far away you get from their location they still deal damage. They don't perform an animation when attacking mid-air. I haven't seen this glitch with mobs yet because they can't aim for a running mob.

**Comment by Alex-the-666** [comment]
fixed
