### ISSUE TITLE
Female Tyrannosaurus texture is missing teeth

### ISSUE THREAD

**Issue by Mushroomsock** [FossilsArcheologyRevival/FossilsArcheologyRevival#836]
Both feathered and scaly female Tyrannosaurus are missing any teeth on the upper jaw.

Also the males have a single tooth at the middle of the front jaw which looks a bit odd, but is probably fine.

**Comment by lindstheginj** [comment]
https://www.dropbox.com/sh/qo3sly5lijd6yj7/AABbUPbRm6L7xUFlujsJUagBa?dl=0
Feathered and scaled of both sexes have been updated, they just need replaced. Babies don't need touched.
