### ISSUE TITLE
Essence of chicken shouldn't work on the apex predators

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#853]
Tyrannosaurus, allosaurus, spinosaurus, mosasaurus, sarcosuchus, and megalodon.

**Comment by jman12351** [comment]
Why not, exactly?

**Comment by Adsper** [comment]
Because 1. balance and 2. that’s how it worked in every single other build.

**Comment by Alex-the-666** [comment]
fix
