### ISSUE TITLE
Mysterious sarcophagus, ancient treasure chest, and Anu Totem's item textures look like obsidian

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#854]
If you get them in creative mode, it just looks like you're holding obsidian until you put it down.

**Comment by Adsper** [comment]
![2018-09-01_21 32 56](https://user-images.githubusercontent.com/11862143/44952222-1abba080-ae2f-11e8-8e78-81736796b22d.png)

**Comment by Alex-the-666** [comment]
bug caused by optifine. please update your optifine
