### ISSUE TITLE
Megaloceros fossil model is the same size as the mammoth fossil model

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#872]
This is without any bones put into either of them.
![2018-08-20_20 26 06](https://user-images.githubusercontent.com/11862143/44378687-582b4000-a4b7-11e8-8949-dd276c879f94.png)

**Comment by Alex-the-666** [comment]
this is because both of their babys are the same size. nothing wrong here
