### ISSUE TITLE
Anu shouldn't be able to be poisoned/weakened by potions

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#887]
I doubt a prophetical warlord/ancient god would have a weak immune system.

**Comment by Raptorofwar** [comment]
You can poison the Ender Dragon. You can weaken the Wither. I honestly think splashing Anu is fine.

**Comment by Adsper** [comment]
According to the mc wiki, you can't poison either of those things.

**Comment by Raptorofwar** [comment]
Welp. I am horribly misinformed.
