### ISSUE TITLE
Aggressive mobs won't attack the following hostile mobs:

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#901]
Decided to compile the whole list: 

Anubites, endermites, evokers, husks, sentry pigmen, shulkers, skeletons, wither skeletons, silverfish, slimes, nether slimes, tar slimes, spiders, cave spiders, strays, vexes, vindicators, witches, and zombie villagers.

**Comment by Alex-the-666** [comment]
fixed
