### ISSUE TITLE
Mammoth herds doing their circling of death

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#907]
A lot of the time (though not all the time), mammoths will just stand still in one spot in a flat plain and keep circling around and around forever, literally never breaking out of it until they eventually sleep, similar to the galli.

I've only ever seen this happen in herds, but that could be unrelated.

**Comment by Sunconure11** [comment]
I'm having a hard time replicating this with the two offending mobs. Can you provide more details?

**Comment by Sunconure11** [comment]
I may have replicated this with the Paras, by two of them getting stuck together. Requesting more aid.

**Comment by Alex-the-666** [comment]
fixed
