### ISSUE TITLE
Mutant plants arent changing colour

### ISSUE THREAD

**Issue by CactusKingIII** [FossilsArcheologyRevival/FossilsArcheologyRevival#908]

**Comment by Alex-the-666** [comment]
are you using optifine?

**Comment by CactusKingIII** [comment]
Actually yes

**Comment by Alex-the-666** [comment]
make sure you enable block animations in optifine. then see again

**Comment by CactusKingIII** [comment]
Reinstalled Optifine.  seems like it was an Optifine issue, working normally now.
