### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by RoboticBulbasaur** [FossilsArcheologyRevival/FossilsArcheologyRevival#919]
It crashes when i try to load and i get this message. Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: fossilsarcheology/client/model/prehistoric/ModelTriceratops

Here's the whole crash report if it helps.
[Untitled document.docx](https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/files/2322120/Untitled.document.docx)

Please Help!

**Comment by 4f6f3b** [comment]
You just install Library 1.5.1 for Minecraft 1.7.10.

https://minecraft.curseforge.com/projects/llibrary/files/2319767

Please make sure you use the gray download button.
