### ISSUE TITLE
Quagga despawned

### ISSUE THREAD

**Issue by CactusKingIII** [FossilsArcheologyRevival/FossilsArcheologyRevival#920]

**Comment by Alex-the-666** [comment]
Are you sure it wasnt killed by natural causes? Vanilla animals can't despawn naturally, and the quagga extends one of those.

**Comment by CactusKingIII** [comment]
Quagga were kept in an enclosed pen without a way to escape.  they aren't in the surrounding area so they didn't escape.  the only thing i can think of is that a hostile mob killed them, but i set the time to day every night and i don't think any monsters attack horses.

**Comment by Sunconure11** [comment]
Unsure as to the possible cause of this, plus even vanilla-style mobs can despawn at random, for seemingly no reason. Unless it can be replicated and is clearly a broken function, I will close this.
