### ISSUE TITLE
Build #427 bug: Various item/block names need adjusting

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#926]
- Cultivators/Culture vats are listed as "{color} Cultivator".
- Palaeoraphe (leaves, logs, wood, saplings, etc.) is referred to as "Palm".

**Comment by Alex-the-666** [comment]
I'm not seeing this. could you screenshot it?

**Comment by Alex-the-666** [comment]
closing do to not being able to see any information
