### ISSUE TITLE
Build #427 bug: Cultivator won't accept certain foods as fuel

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#927]
- The cultivator won't accept: Apples, carrots, potatoes, baked potatoes, seeds, melon, wheat, bread, cookies, cake, cocoa beans, cooked fish or cooked salmon (it has no issue with raw fish or raw salmon though, or any meat).

**Comment by Raptorofwar** [comment]
I thought they were only supposed to accept protein objects.

**Comment by Totemaster** [comment]
Ah I see. Well in that case, cooked fish and salmon would definitely qualify as protein.

**Comment by Alex-the-666** [comment]
fixed
