### ISSUE TITLE
Guardians still don't attack aquatic mobs

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#932]
So now aquatic carnivores can eat guardians, but guardians still won't actually attack any of the aquatic mobs like heno or itchy. It makes sense for them to attack the mod sea creatures first, since they're hostile to every vanilla aquatic mob.

**Comment by mser7** [comment]
Only to squids in particular, in 1.13 they leave fishes, turtles and dolphins alone

**Comment by Alex-the-666** [comment]
yeah its not their intended behavior
