### ISSUE TITLE
Hunger seems to slow waaaaaaaaaaaaaaaaaaaaaaaay down when a dinosaur sleeps

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#935]
It's like they're in a coma. Don't know if this is intended or not, but if it is, it shouldn't be nearly this slow

**Comment by Alex-the-666** [comment]
do you know of any way to reproduce this?

**Comment by Adsper** [comment]
Put a rex down in an iron cage, set the time to night, and watch the hunger bar with a dinopedia.
