### ISSUE TITLE
Tyrannosaurus appears to be awake even though the DinoPedia shows it sleeping

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#936]
![2018-09-03_01 59 53](https://user-images.githubusercontent.com/11862143/44977514-140b5700-af1d-11e8-8ccf-6df9bd173570.png)
![2018-09-03_01 59 56](https://user-images.githubusercontent.com/11862143/44977519-17064780-af1d-11e8-8d88-73bb1f080043.png)

**Comment by lindstheginj** [comment]
Refer to #1407
