### ISSUE TITLE
Build #464 bug/enhancement: Quaggas still make ordinary horse sounds

### ISSUE THREAD

**Issue by Totemaster** [FossilsArcheologyRevival/FossilsArcheologyRevival#941]
- The sound library of the quagga (still) has yet to be updated with the more zebra-like sounds.

**Comment by 4f6f3b** [comment]
#859

**Comment by Adsper** [comment]
I think there was a little mistake here. All of the new quagga sounds (which are great btw) ended up being hurt sounds, there's no idle or death one.

**Comment by 4f6f3b** [comment]
I'm getting the expected sounds in my testing. Some of them sound similar.

@Totemaster Can you verify the sounds are what you intended or not?
