### ISSUE TITLE
Is it just me or is megalania's venom way too weak?

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#958]
It only does 1.5 hearts of damage, compared to its regular attack that takes half the healthbar.

**Comment by CactusKingIII** [comment]
Monitor lizard venom doesn’t work the same way spider or snake venom works.  It’s not there as a weapon.  1.5 hp seems perfectly reasonable to me.

**Comment by Adsper** [comment]
At the very least the other potion effects should be extended. It only has slowness for 8 seconds and weakness for about 5 seconds, that's barely enough to notice it.

**Comment by Raptorofwar** [comment]
But wouldn't it keep hitting you, so you couldn't get away?

**Comment by Adsper** [comment]
Yeah, probably.
Maybe don't get yourself in a situation where you approach a megalania.

**Comment by Raptorofwar** [comment]
Then it really serves as a pinning-down thing for prey; long term poison just becomes really annoying. It'd really suck to be slow for an extended period of time, even if it does make the need for milk more prominent. While it'd be more realistic, it'd be less fun as a game.

**Comment by CactusKingIII** [comment]
@Adsper 100 seconds

**Comment by CactusKingIII** [comment]
Or up to 250 seconds depending on how many is several

**Comment by Adsper** [comment]
Now _that_ would be way too long game-play wise. 25-30 seconds is fine.

**Comment by CactusKingIII** [comment]
Which, because you weren’t wondering, is slightly over half an hour.

**Comment by Alex-the-666** [comment]
fixed
