### ISSUE TITLE
Megalodon on Land Moving

### ISSUE THREAD

**Issue by OwenGradyI999** [FossilsArcheologyRevival/FossilsArcheologyRevival#963]
So I got the Beta of F/A without permission (from someone from discord). I already talked with a Dev to see if the bugs I got were already reported before. There was one bug in the middle of a talk, which I found that Megalodon moves back to water for some reason, and moving.

https://gyazo.com/9364c21aa55e1d8877bf2bfe49e74338

Also it takes damage at the surface of the water.
Also im not sure if dinosaurs are suppose to have a resting animation, but from 1.7.10, I don't think so.

Feeders don't drop any items within it either

**Comment by Adsper** [comment]
I think this is intentional. It slowly wiggles its way back into the water.

**Comment by CactusKingIII** [comment]
Because that’s totally a thing whale sized animals do regularly.

**Comment by CactusKingIII** [comment]
Mosa and lio shouldn’t be able to hang out on beaches at all.  But that’s also intended for some reason.

**Comment by OwenGradyI999** [comment]
Unless they get beached, but usually they die or somehow get dragged back in. None of the seacreatures (Mosasaurus, Lioplerdon, Megalodon) shouldn't at all move on land

**Comment by DeinoRaptor** [comment]
Unless, of course, they forgot to implement the same AI for Megalodon that does not allow them to move on land

**Comment by Alex-the-666** [comment]
fixed
