### ISSUE TITLE
Baby megalania don't sleep; adults do

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#968]

**Comment by Sunconure11** [comment]
I believe this to be an animation issue, as they are motionless at night, but do not enter the sleeping animation.

**Comment by Sunconure11** [comment]
Babies appear to do basically nothing the more and more I toy around with the mob.

**Comment by lindstheginj** [comment]
baby anky also won't sleep

**Comment by Sunconure11** [comment]
Check if it actually moves around or does anything during the day as well. Megalania has that issue.

**Comment by lindstheginj** [comment]
The anky now sleeps, but doesnt move

**Comment by lindstheginj** [comment]
Suddenly it isn't sleeping again. Sleeping seems broken/inconsistent

**Comment by Alex-the-666** [comment]
fixed
