### ISSUE TITLE
Can sift Beetroot seeds in the sifter

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#973]

**Comment by Sunconure11** [comment]
![screenshot 2018-10-14 09 27 58](https://user-images.githubusercontent.com/5614902/46917297-7e3eff00-cf93-11e8-8de8-8ec913a6de1a.png)
It's affecting most items. @Alex-the-666 @gegy1000, see if one of you can figure out what is going on when given the chance.

**Comment by Sunconure11** [comment]
Concrete powder seems to be valid according to JEI, which does not exactly make any sense.

**Comment by Alex-the-666** [comment]
fixed
