### ISSUE TITLE
Tar bucket is in the wrong spot in the creative menu

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#979]
It's in Miscellaneous when it should be in Fossils Revival Items.

**Comment by Adsper** [comment]
Well by that logic, all of the plant stuff needs to go in decoration, the scarab tools need to go in tools, the armor needs to go in weapons, etc.

**Comment by Alex-the-666** [comment]
forge does this automatically to fluids, just as it does to spawn eggs.
