### ISSUE TITLE
[1.12.2] Repairing Pottery Duplication

### ISSUE THREAD

**Issue by Gift-of-Names** [FossilsArcheologyRevival/FossilsArcheologyRevival#983]
Repairing pottery in the archaeology workbench yields an amount or repaired pottery equal to the stack being repaired per unit fuel. If you start with 10, the first pottery shard yields 10 repaired pottery. However, the next shard does not appear to increase the amount in the yield slot at all, and the initial slot decreases properly. If the yield slot is removed before the initial slot is empty, this causes duplication as the next shard will again produce a number equal to the initial slot.

**Comment by Alex-the-666** [comment]
fixed
