### ISSUE TITLE
Sifter does not sift dirt

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#985]

**Comment by CactusKingIII** [comment]
Well have YOU tried sifting a block of dirt so solid it can be suspended in the air without anything underneath?

**Comment by Sunconure11** [comment]
I can sift anything BUT appropriate items, such as dirt. WTF?

**Comment by Sunconure11** [comment]
Looks like concrete powder is also somehow, siftable, at least, according to JEI, which shouldn't be a thing.

**Comment by Alex-the-666** [comment]
fixed
