### ISSUE TITLE
Can't climb tempskya from any side

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#988]

**Comment by Sunconure11** [comment]
This is partially fixed in dev, but one can only climb it from two sides. Why not just can this feature?

**Comment by Gift-of-Names** [comment]
From experimentation, it seems that it can be climbed on all sides by nearly anything with a small hitbox (seemingly less than 1X1).

**Comment by Alex-the-666** [comment]
removed this feature. causing too much truoble
