### ISSUE TITLE
baby anky is hungry, runs up to feeder, but doesnt eat

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#993]
Feeder value does not go down, hunger value does not increase, and he returns straight back to the feeder when you push him away

**Comment by lindstheginj** [comment]
After taking him outside, it seems that they CAN EAT because he's eating grass but just can't eat from the feeder

**Comment by lindstheginj** [comment]
#1046 #1049

**Comment by Alex-the-666** [comment]
fixed
