### ISSUE TITLE
Structures (besides the library, moais and arch house) still don't/barely spawn

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#994]
IIRC Mush managed to find a temple once, but that's pretty much it from all my testing and what I've seen.

It doesn't really help with how rare jungles are now. I know this would probably be for something beyond the port, but would it be possible to have the jungle-only Aztec stuff spawn in other similar biomes like the roofed forest?

**Comment by Alex-the-666** [comment]
fixed
