### ISSUE TITLE
Obsidian spikes recipe broken

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilsArcheologyRevival#998]

**Comment by Sunconure11** [comment]
I can fix this, will work on it later

**Comment by Sunconure11** [comment]
Unable to replicate in a dev environment.

![screenshot 2018-10-24 19 38 06](https://user-images.githubusercontent.com/5614902/47467457-669e1c80-d7c4-11e8-8a4a-f984766c65a2.png)

**Comment by Adsper** [comment]
Oh, it was changed. It used to be that it was two obsidian on the left and two on the right.

**Comment by CactusKingIII** [comment]
Adsper the NOOB

**Comment by Sunconure11** [comment]
User error.
